<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GrpcEvitaTrafficRecordingAPI.proto

namespace Wtsvk\EvitaDbClient\Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Response to GetTrafficRecordingLabelsValuesOrderedByCardinality request.
 *
 * Generated from protobuf message <code>io.evitadb.externalApi.grpc.generated.GetTrafficRecordingValuesNamesRequest</code>
 */
class GetTrafficRecordingValuesNamesRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * The limit of records to return
     *
     * Generated from protobuf field <code>int32 limit = 1;</code>
     */
    protected $limit = 0;
    /**
     * The name of the label to get the values for
     *
     * Generated from protobuf field <code>string labelName = 2;</code>
     */
    protected $labelName = '';
    /**
     * Allows to filter the returned labels by the name prefix
     *
     * Generated from protobuf field <code>.google.protobuf.StringValue valueStartsWith = 3;</code>
     */
    protected $valueStartsWith = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $limit
     *           The limit of records to return
     *     @type string $labelName
     *           The name of the label to get the values for
     *     @type \Google\Protobuf\StringValue $valueStartsWith
     *           Allows to filter the returned labels by the name prefix
     * }
     */
    public function __construct($data = NULL) {
        \Wtsvk\EvitaDbClient\Protocol\GPBMetadata\GrpcEvitaTrafficRecordingAPI::initOnce();
        parent::__construct($data);
    }

    /**
     * The limit of records to return
     *
     * Generated from protobuf field <code>int32 limit = 1;</code>
     * @return int
     */
    public function getLimit()
    {
        return $this->limit;
    }

    /**
     * The limit of records to return
     *
     * Generated from protobuf field <code>int32 limit = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setLimit($var)
    {
        GPBUtil::checkInt32($var);
        $this->limit = $var;

        return $this;
    }

    /**
     * The name of the label to get the values for
     *
     * Generated from protobuf field <code>string labelName = 2;</code>
     * @return string
     */
    public function getLabelName()
    {
        return $this->labelName;
    }

    /**
     * The name of the label to get the values for
     *
     * Generated from protobuf field <code>string labelName = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setLabelName($var)
    {
        GPBUtil::checkString($var, True);
        $this->labelName = $var;

        return $this;
    }

    /**
     * Allows to filter the returned labels by the name prefix
     *
     * Generated from protobuf field <code>.google.protobuf.StringValue valueStartsWith = 3;</code>
     * @return \Google\Protobuf\StringValue|null
     */
    public function getValueStartsWith()
    {
        return $this->valueStartsWith;
    }

    public function hasValueStartsWith()
    {
        return isset($this->valueStartsWith);
    }

    public function clearValueStartsWith()
    {
        unset($this->valueStartsWith);
    }

    /**
     * Returns the unboxed value from <code>getValueStartsWith()</code>

     * Allows to filter the returned labels by the name prefix
     *
     * Generated from protobuf field <code>.google.protobuf.StringValue valueStartsWith = 3;</code>
     * @return string|null
     */
    public function getValueStartsWithUnwrapped()
    {
        return $this->readWrapperValue("valueStartsWith");
    }

    /**
     * Allows to filter the returned labels by the name prefix
     *
     * Generated from protobuf field <code>.google.protobuf.StringValue valueStartsWith = 3;</code>
     * @param \Google\Protobuf\StringValue $var
     * @return $this
     */
    public function setValueStartsWith($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\StringValue::class);
        $this->valueStartsWith = $var;

        return $this;
    }

    /**
     * Sets the field by wrapping a primitive type in a Google\Protobuf\StringValue object.

     * Allows to filter the returned labels by the name prefix
     *
     * Generated from protobuf field <code>.google.protobuf.StringValue valueStartsWith = 3;</code>
     * @param string|null $var
     * @return $this
     */
    public function setValueStartsWithUnwrapped($var)
    {
        $this->writeWrapperValue("valueStartsWith", $var);
        return $this;}

}

