<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GrpcEvitaSessionAPI.proto

namespace Wtsvk\EvitaDbClient\Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Response to GetTransactionOverview request.
 *
 * Generated from protobuf message <code>io.evitadb.externalApi.grpc.generated.GetTransactionOverviewResponse</code>
 */
class GetTransactionOverviewResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * The list of transaction overviews that match the requested catalog versions
     *
     * Generated from protobuf field <code>repeated .io.evitadb.externalApi.grpc.generated.GrpcTransactionOverview transactionOverviews = 1;</code>
     */
    private $transactionOverviews;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\Wtsvk\EvitaDbClient\Protocol\GrpcTransactionOverview>|\Google\Protobuf\Internal\RepeatedField $transactionOverviews
     *           The list of transaction overviews that match the requested catalog versions
     * }
     */
    public function __construct($data = NULL) {
        \Wtsvk\EvitaDbClient\Protocol\GPBMetadata\GrpcEvitaSessionAPI::initOnce();
        parent::__construct($data);
    }

    /**
     * The list of transaction overviews that match the requested catalog versions
     *
     * Generated from protobuf field <code>repeated .io.evitadb.externalApi.grpc.generated.GrpcTransactionOverview transactionOverviews = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTransactionOverviews()
    {
        return $this->transactionOverviews;
    }

    /**
     * The list of transaction overviews that match the requested catalog versions
     *
     * Generated from protobuf field <code>repeated .io.evitadb.externalApi.grpc.generated.GrpcTransactionOverview transactionOverviews = 1;</code>
     * @param array<\Wtsvk\EvitaDbClient\Protocol\GrpcTransactionOverview>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTransactionOverviews($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Wtsvk\EvitaDbClient\Protocol\GrpcTransactionOverview::class);
        $this->transactionOverviews = $arr;

        return $this;
    }

}

