<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GrpcEvitaTrafficRecordingAPI.proto

namespace Wtsvk\EvitaDbClient\Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Request to GetTrafficHistoryList request.
 *
 * Generated from protobuf message <code>io.evitadb.externalApi.grpc.generated.GetTrafficHistoryListRequest</code>
 */
class GetTrafficHistoryListRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * The limit of records to return
     *
     * Generated from protobuf field <code>int32 limit = 1;</code>
     */
    protected $limit = 0;
    /**
     * The criteria of the traffic recording, allows to define constraints on the returned records
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcTrafficRecordingCaptureCriteria criteria = 2;</code>
     */
    protected $criteria = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $limit
     *           The limit of records to return
     *     @type \Wtsvk\EvitaDbClient\Protocol\GrpcTrafficRecordingCaptureCriteria $criteria
     *           The criteria of the traffic recording, allows to define constraints on the returned records
     * }
     */
    public function __construct($data = NULL) {
        \Wtsvk\EvitaDbClient\Protocol\GPBMetadata\GrpcEvitaTrafficRecordingAPI::initOnce();
        parent::__construct($data);
    }

    /**
     * The limit of records to return
     *
     * Generated from protobuf field <code>int32 limit = 1;</code>
     * @return int
     */
    public function getLimit()
    {
        return $this->limit;
    }

    /**
     * The limit of records to return
     *
     * Generated from protobuf field <code>int32 limit = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setLimit($var)
    {
        GPBUtil::checkInt32($var);
        $this->limit = $var;

        return $this;
    }

    /**
     * The criteria of the traffic recording, allows to define constraints on the returned records
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcTrafficRecordingCaptureCriteria criteria = 2;</code>
     * @return \Wtsvk\EvitaDbClient\Protocol\GrpcTrafficRecordingCaptureCriteria|null
     */
    public function getCriteria()
    {
        return $this->criteria;
    }

    public function hasCriteria()
    {
        return isset($this->criteria);
    }

    public function clearCriteria()
    {
        unset($this->criteria);
    }

    /**
     * The criteria of the traffic recording, allows to define constraints on the returned records
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcTrafficRecordingCaptureCriteria criteria = 2;</code>
     * @param \Wtsvk\EvitaDbClient\Protocol\GrpcTrafficRecordingCaptureCriteria $var
     * @return $this
     */
    public function setCriteria($var)
    {
        GPBUtil::checkMessage($var, \Wtsvk\EvitaDbClient\Protocol\GrpcTrafficRecordingCaptureCriteria::class);
        $this->criteria = $var;

        return $this;
    }

}

