<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GrpcEnums.proto

namespace Wtsvk\EvitaDbClient\Protocol;

use UnexpectedValueException;

/**
 * Enum describes possible classifier types used in reserved keywords listing
 *
 * Protobuf type <code>io.evitadb.externalApi.grpc.generated.GrpcClassifierType</code>
 */
class GrpcClassifierType
{
    /**
     **
     * Identification of the server instance.
     *
     * Generated from protobuf enum <code>CLASSIFIER_TYPE_SERVER_NAME = 0;</code>
     */
    const CLASSIFIER_TYPE_SERVER_NAME = 0;
    /**
     **
     * Identification of the catalog.
     *
     * Generated from protobuf enum <code>CLASSIFIER_TYPE_CATALOG = 1;</code>
     */
    const CLASSIFIER_TYPE_CATALOG = 1;
    /**
     **
     * Identification of the entity type.
     *
     * Generated from protobuf enum <code>CLASSIFIER_TYPE_ENTITY = 2;</code>
     */
    const CLASSIFIER_TYPE_ENTITY = 2;
    /**
     **
     * Identification of the attribute.
     *
     * Generated from protobuf enum <code>CLASSIFIER_TYPE_ATTRIBUTE = 3;</code>
     */
    const CLASSIFIER_TYPE_ATTRIBUTE = 3;
    /**
     **
     * Identification of the associated data (rich content).
     *
     * Generated from protobuf enum <code>CLASSIFIER_TYPE_ASSOCIATED_DATA = 4;</code>
     */
    const CLASSIFIER_TYPE_ASSOCIATED_DATA = 4;
    /**
     **
     * Identification of the reference.
     *
     * Generated from protobuf enum <code>CLASSIFIER_TYPE_REFERENCE = 5;</code>
     */
    const CLASSIFIER_TYPE_REFERENCE = 5;
    /**
     **
     * Identification of the reference attribute.
     *
     * Generated from protobuf enum <code>CLASSIFIER_TYPE_REFERENCE_ATTRIBUTE = 6;</code>
     */
    const CLASSIFIER_TYPE_REFERENCE_ATTRIBUTE = 6;

    private static $valueToName = [
        self::CLASSIFIER_TYPE_SERVER_NAME => 'CLASSIFIER_TYPE_SERVER_NAME',
        self::CLASSIFIER_TYPE_CATALOG => 'CLASSIFIER_TYPE_CATALOG',
        self::CLASSIFIER_TYPE_ENTITY => 'CLASSIFIER_TYPE_ENTITY',
        self::CLASSIFIER_TYPE_ATTRIBUTE => 'CLASSIFIER_TYPE_ATTRIBUTE',
        self::CLASSIFIER_TYPE_ASSOCIATED_DATA => 'CLASSIFIER_TYPE_ASSOCIATED_DATA',
        self::CLASSIFIER_TYPE_REFERENCE => 'CLASSIFIER_TYPE_REFERENCE',
        self::CLASSIFIER_TYPE_REFERENCE_ATTRIBUTE => 'CLASSIFIER_TYPE_REFERENCE_ATTRIBUTE',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

