<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GrpcEvitaDataTypes.proto

namespace Wtsvk\EvitaDbClient\Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Structure that holds a complex object. It can be either a map or an array of values.
 *
 * Generated from protobuf message <code>io.evitadb.externalApi.grpc.generated.GrpcDataItem</code>
 */
class GrpcDataItem extends \Google\Protobuf\Internal\Message
{
    protected $value;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Wtsvk\EvitaDbClient\Protocol\GrpcEvitaValue $primitiveValue
     *           Primitive value.
     *     @type \Wtsvk\EvitaDbClient\Protocol\GrpcDataItemArray $arrayValue
     *           The array of values.
     *     @type \Wtsvk\EvitaDbClient\Protocol\DataItemMap $mapValue
     *           The map of values.
     * }
     */
    public function __construct($data = NULL) {
        \Wtsvk\EvitaDbClient\Protocol\GPBMetadata\GrpcEvitaDataTypes::initOnce();
        parent::__construct($data);
    }

    /**
     * Primitive value.
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcEvitaValue primitiveValue = 1;</code>
     * @return \Wtsvk\EvitaDbClient\Protocol\GrpcEvitaValue|null
     */
    public function getPrimitiveValue()
    {
        return $this->readOneof(1);
    }

    public function hasPrimitiveValue()
    {
        return $this->hasOneof(1);
    }

    /**
     * Primitive value.
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcEvitaValue primitiveValue = 1;</code>
     * @param \Wtsvk\EvitaDbClient\Protocol\GrpcEvitaValue $var
     * @return $this
     */
    public function setPrimitiveValue($var)
    {
        GPBUtil::checkMessage($var, \Wtsvk\EvitaDbClient\Protocol\GrpcEvitaValue::class);
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * The array of values.
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcDataItemArray arrayValue = 4;</code>
     * @return \Wtsvk\EvitaDbClient\Protocol\GrpcDataItemArray|null
     */
    public function getArrayValue()
    {
        return $this->readOneof(4);
    }

    public function hasArrayValue()
    {
        return $this->hasOneof(4);
    }

    /**
     * The array of values.
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcDataItemArray arrayValue = 4;</code>
     * @param \Wtsvk\EvitaDbClient\Protocol\GrpcDataItemArray $var
     * @return $this
     */
    public function setArrayValue($var)
    {
        GPBUtil::checkMessage($var, \Wtsvk\EvitaDbClient\Protocol\GrpcDataItemArray::class);
        $this->writeOneof(4, $var);

        return $this;
    }

    /**
     * The map of values.
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.DataItemMap mapValue = 5;</code>
     * @return \Wtsvk\EvitaDbClient\Protocol\DataItemMap|null
     */
    public function getMapValue()
    {
        return $this->readOneof(5);
    }

    public function hasMapValue()
    {
        return $this->hasOneof(5);
    }

    /**
     * The map of values.
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.DataItemMap mapValue = 5;</code>
     * @param \Wtsvk\EvitaDbClient\Protocol\DataItemMap $var
     * @return $this
     */
    public function setMapValue($var)
    {
        GPBUtil::checkMessage($var, \Wtsvk\EvitaDbClient\Protocol\DataItemMap::class);
        $this->writeOneof(5, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getValue()
    {
        return $this->whichOneof("value");
    }

}

