<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GrpcEvitaAPI.proto

namespace Wtsvk\EvitaDbClient\Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Request to apply mutation on engine level.
 *
 * Generated from protobuf message <code>io.evitadb.externalApi.grpc.generated.GrpcApplyMutationRequest</code>
 */
class GrpcApplyMutationRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Single engine level mutation to be applied.
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcEngineMutation mutation = 1;</code>
     */
    protected $mutation = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Wtsvk\EvitaDbClient\Protocol\GrpcEngineMutation $mutation
     *           Single engine level mutation to be applied.
     * }
     */
    public function __construct($data = NULL) {
        \Wtsvk\EvitaDbClient\Protocol\GPBMetadata\GrpcEvitaAPI::initOnce();
        parent::__construct($data);
    }

    /**
     * Single engine level mutation to be applied.
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcEngineMutation mutation = 1;</code>
     * @return \Wtsvk\EvitaDbClient\Protocol\GrpcEngineMutation|null
     */
    public function getMutation()
    {
        return $this->mutation;
    }

    public function hasMutation()
    {
        return isset($this->mutation);
    }

    public function clearMutation()
    {
        unset($this->mutation);
    }

    /**
     * Single engine level mutation to be applied.
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcEngineMutation mutation = 1;</code>
     * @param \Wtsvk\EvitaDbClient\Protocol\GrpcEngineMutation $var
     * @return $this
     */
    public function setMutation($var)
    {
        GPBUtil::checkMessage($var, \Wtsvk\EvitaDbClient\Protocol\GrpcEngineMutation::class);
        $this->mutation = $var;

        return $this;
    }

}

