<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GrpcEvitaManagementAPI.proto

namespace Wtsvk\EvitaDbClient\Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Request to list files to fetch in paginated form.
 *
 * Generated from protobuf message <code>io.evitadb.externalApi.grpc.generated.GrpcFilesToFetchRequest</code>
 */
class GrpcFilesToFetchRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Page number of the task statuses to be listed.
     *
     * Generated from protobuf field <code>int32 pageNumber = 1;</code>
     */
    protected $pageNumber = 0;
    /**
     * Number of task statuses per page.
     *
     * Generated from protobuf field <code>int32 pageSize = 2;</code>
     */
    protected $pageSize = 0;
    /**
     * Optional origin of the files (derived from taskType), passing non-null value
     * in this argument filters the returned files to only those that are related to the specified origin
     *
     * Generated from protobuf field <code>repeated .google.protobuf.StringValue origin = 3;</code>
     */
    private $origin;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $pageNumber
     *           Page number of the task statuses to be listed.
     *     @type int $pageSize
     *           Number of task statuses per page.
     *     @type array<\Google\Protobuf\StringValue>|\Google\Protobuf\Internal\RepeatedField $origin
     *           Optional origin of the files (derived from taskType), passing non-null value
     *           in this argument filters the returned files to only those that are related to the specified origin
     * }
     */
    public function __construct($data = NULL) {
        \Wtsvk\EvitaDbClient\Protocol\GPBMetadata\GrpcEvitaManagementAPI::initOnce();
        parent::__construct($data);
    }

    /**
     * Page number of the task statuses to be listed.
     *
     * Generated from protobuf field <code>int32 pageNumber = 1;</code>
     * @return int
     */
    public function getPageNumber()
    {
        return $this->pageNumber;
    }

    /**
     * Page number of the task statuses to be listed.
     *
     * Generated from protobuf field <code>int32 pageNumber = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setPageNumber($var)
    {
        GPBUtil::checkInt32($var);
        $this->pageNumber = $var;

        return $this;
    }

    /**
     * Number of task statuses per page.
     *
     * Generated from protobuf field <code>int32 pageSize = 2;</code>
     * @return int
     */
    public function getPageSize()
    {
        return $this->pageSize;
    }

    /**
     * Number of task statuses per page.
     *
     * Generated from protobuf field <code>int32 pageSize = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setPageSize($var)
    {
        GPBUtil::checkInt32($var);
        $this->pageSize = $var;

        return $this;
    }

    /**
     * Optional origin of the files (derived from taskType), passing non-null value
     * in this argument filters the returned files to only those that are related to the specified origin
     *
     * Generated from protobuf field <code>repeated .google.protobuf.StringValue origin = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getOrigin()
    {
        return $this->origin;
    }

    /**
     * Optional origin of the files (derived from taskType), passing non-null value
     * in this argument filters the returned files to only those that are related to the specified origin
     *
     * Generated from protobuf field <code>repeated .google.protobuf.StringValue origin = 3;</code>
     * @param array<\Google\Protobuf\StringValue>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setOrigin($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Google\Protobuf\StringValue::class);
        $this->origin = $arr;

        return $this;
    }

}

