<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GrpcEnums.proto

namespace Wtsvk\EvitaDbClient\Protocol;

use UnexpectedValueException;

/**
 * This enumeration controls behavior of the {&#64;link ReferenceContent} related to managed entities.
 * If the target entity is not (yet) present in the database and {&#64;link ManagedReferencesBehaviour#EXISTING} is set,
 * the reference will not be returned as if it does not exist.
 * If {&#64;link ManagedReferencesBehaviour#ANY} is set (default behavior), the reference will be returned if defined regardless
 * of its target entity existence.
 *
 * Protobuf type <code>io.evitadb.externalApi.grpc.generated.GrpcManagedReferencesBehaviour</code>
 */
class GrpcManagedReferencesBehaviour
{
    /**
     * The reference to managed entity will always be returned regardless of the target entity existence.
     *
     * Generated from protobuf enum <code>ANY = 0;</code>
     */
    const ANY = 0;
    /**
     * The reference to managed entity will be returned only if the target entity exists in the database.
     *
     * Generated from protobuf enum <code>EXISTING = 1;</code>
     */
    const EXISTING = 1;

    private static $valueToName = [
        self::ANY => 'ANY',
        self::EXISTING => 'EXISTING',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

