<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GrpcEvitaManagementAPI.proto

namespace Wtsvk\EvitaDbClient\Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Response to a task status request.
 *
 * Generated from protobuf message <code>io.evitadb.externalApi.grpc.generated.GrpcFetchFileResponse</code>
 */
class GrpcFetchFileResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * chunk of the file content
     *
     * Generated from protobuf field <code>bytes fileContents = 1;</code>
     */
    protected $fileContents = '';
    /**
     * total size of the file
     *
     * Generated from protobuf field <code>int64 totalSizeInBytes = 2;</code>
     */
    protected $totalSizeInBytes = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $fileContents
     *           chunk of the file content
     *     @type int|string $totalSizeInBytes
     *           total size of the file
     * }
     */
    public function __construct($data = NULL) {
        \Wtsvk\EvitaDbClient\Protocol\GPBMetadata\GrpcEvitaManagementAPI::initOnce();
        parent::__construct($data);
    }

    /**
     * chunk of the file content
     *
     * Generated from protobuf field <code>bytes fileContents = 1;</code>
     * @return string
     */
    public function getFileContents()
    {
        return $this->fileContents;
    }

    /**
     * chunk of the file content
     *
     * Generated from protobuf field <code>bytes fileContents = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setFileContents($var)
    {
        GPBUtil::checkString($var, False);
        $this->fileContents = $var;

        return $this;
    }

    /**
     * total size of the file
     *
     * Generated from protobuf field <code>int64 totalSizeInBytes = 2;</code>
     * @return int|string
     */
    public function getTotalSizeInBytes()
    {
        return $this->totalSizeInBytes;
    }

    /**
     * total size of the file
     *
     * Generated from protobuf field <code>int64 totalSizeInBytes = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTotalSizeInBytes($var)
    {
        GPBUtil::checkInt64($var);
        $this->totalSizeInBytes = $var;

        return $this;
    }

}

