<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GrpcChangeCapture.proto

namespace Wtsvk\EvitaDbClient\Protocol;

use UnexpectedValueException;

/**
 * Enumeration of possible mutation types handled by evitaDB.
 *
 * Protobuf type <code>io.evitadb.externalApi.grpc.generated.GrpcChangeCaptureOperation</code>
 */
class GrpcChangeCaptureOperation
{
    /**
     * Create or update operation - i.e. there was data with such identity before, and it was updated.
     *
     * Generated from protobuf enum <code>UPSERT = 0;</code>
     */
    const UPSERT = 0;
    /**
     * Remove operation - i.e. there was data with such identity before, and it was removed.
     *
     * Generated from protobuf enum <code>REMOVE = 1;</code>
     */
    const REMOVE = 1;
    /**
     * Delimiting operation signaling the beginning of a transaction.
     *
     * Generated from protobuf enum <code>TRANSACTION = 2;</code>
     */
    const TRANSACTION = 2;

    private static $valueToName = [
        self::UPSERT => 'UPSERT',
        self::REMOVE => 'REMOVE',
        self::TRANSACTION => 'TRANSACTION',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

