<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GrpcEntitySchema.proto

namespace Wtsvk\EvitaDbClient\Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * This is the definition object for attributes that are stored along with
 * entity. Definition objects allow to describe the structure of the entity type so that
 * in any time everyone can consult complete structure of the entity type. Definition object is similar to Java reflection
 * process where you can also at any moment see which fields and methods are available for the class.
 * Entity attributes allows defining set of data that are fetched in bulk along with the entity body.
 * Attributes may be indexed for fast filtering (`AttributeSchema.filterable`) or can be used to sort along
 * (`AttributeSchema.sortable`). Attributes are not automatically indexed in order not to waste precious
 * memory space for data that will never be used in search queries.
 * Filtering in attributes is executed by using constraints like `and`,
 * `not`, `attributeEquals`, `attributeContains`
 * and many others. Sorting can be achieved with `attributeNatural` or others.
 * Attributes are not recommended for bigger data as they are all loaded at once requested.
 * Large data that are occasionally used store in `associatedData`.
 *
 * Generated from protobuf message <code>io.evitadb.externalApi.grpc.generated.GrpcAttributeSchema</code>
 */
class GrpcAttributeSchema extends \Google\Protobuf\Internal\Message
{
    /**
     * Contains unique name of the model. Case-sensitive. Distinguishes one model item from another
     * within single entity instance.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     */
    protected $name = '';
    /**
     * When this attribute schema belongs to a catalog - it is global and can have globally unique attributes enforced across whole catalog.
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcAttributeSchemaType schemaType = 2;</code>
     */
    protected $schemaType = 0;
    /**
     * Contains description of the model is optional but helps authors of the schema / client API to better
     * explain the original purpose of the model to the consumers.
     *
     * Generated from protobuf field <code>.google.protobuf.StringValue description = 3;</code>
     */
    protected $description = null;
    /**
     * Deprecation notice contains information about planned removal of this entity from the model / client API.
     * This allows to plan and evolve the schema allowing clients to adapt early to planned breaking changes.
     * If notice is `null`, this schema is considered not deprecated.
     *
     * Generated from protobuf field <code>.google.protobuf.StringValue deprecationNotice = 4;</code>
     */
    protected $deprecationNotice = null;
    /**
     * When attribute is unique it is automatically filterable, and it is ensured there is exactly one single entity
     * having certain value of this attribute among other entities in the same collection.
     * As an example of unique attribute can be EAN - there is no sense in having two entities with same EAN, and it's
     * better to have this ensured by the database engine.
     * deprecated in favor of `uniqueInScopes`
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcAttributeUniquenessType unique = 5 [deprecated = true];</code>
     * @deprecated
     */
    protected $unique = 0;
    /**
     * When attribute is unique globally it is automatically filterable, and it is ensured there is exactly one single
     * entity having certain value of this attribute in entire {&#64;link CatalogContract}.
     * {&#64;link AttributeSchemaContract#getType() Type} of the unique attribute must implement {&#64;link Comparable} interface.
     * As an example of unique attribute can be URL - there is no sense in having two entities with same URL, and it's
     * better to have this ensured by the database engine.
     * deprecated in favor of `uniqueGloballyInScopes`
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcGlobalAttributeUniquenessType uniqueGlobally = 6 [deprecated = true];</code>
     * @deprecated
     */
    protected $uniqueGlobally = 0;
    /**
     * When attribute is filterable, it is possible to filter entities by this attribute. Do not mark attribute
     * as filterable unless you know that you'll search entities by this attribute. Each filterable attribute occupies
     * (memory/disk) space in the form of index.
     * When attribute is filterable, extra result `attributeHistogram`
     * can be requested for this attribute.
     * deprecated in favor of `filterableInScopes`
     *
     * Generated from protobuf field <code>bool filterable = 7 [deprecated = true];</code>
     * @deprecated
     */
    protected $filterable = false;
    /**
     * When attribute is sortable, it is possible to sort entities by this attribute. Do not mark attribute
     * as sortable unless you know that you'll sort entities along this attribute. Each sortable attribute occupies
     * (memory/disk) space in the form of index.
     * deprecated in favor of `sortableInScopes`
     *
     * Generated from protobuf field <code>bool sortable = 8 [deprecated = true];</code>
     * @deprecated
     */
    protected $sortable = false;
    /**
     * When attribute is localized, it has to be ALWAYS used in connection with specific `Locale`.
     *
     * Generated from protobuf field <code>bool localized = 9;</code>
     */
    protected $localized = false;
    /**
     * When attribute is nullable, its values may be missing in the entities. Otherwise, the system will enforce
     * non-null checks upon upserting of the entity.
     *
     * Generated from protobuf field <code>bool nullable = 10;</code>
     */
    protected $nullable = false;
    /**
     * Representative flag marks the attribute as one of the most important attributes in the entity, or when used
     * on reference level in the {&#64;link ReferenceSchemaContract} it marks attributes distinguishing duplicated
     * references to the same entity and is a key attribute for creating distinct indexes for such references.
     * In overall, representative attributes should be used in developer tools along with the entity's primary key to
     * describe the entity or reference to that entity. If the flag is used correctly, it can be very helpful to
     * developers in quickly finding their way around the data. There should be very few representative attributes
     * in the entity / reference type, and the ones with uniqueness significance are usually the best to choose.
     *
     * Generated from protobuf field <code>bool representative = 11;</code>
     */
    protected $representative = false;
    /**
     * Data type of the attribute. Must be one of Evita-supported values.
     * Internally the scalar is converted into Java-corresponding data type.
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcEvitaDataType type = 12;</code>
     */
    protected $type = 0;
    /**
     * Default value is used when the entity is created without this attribute specified. Default values allow to pass
     * non-null checks even if no attributes of such name are specified.
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcEvitaValue defaultValue = 13;</code>
     */
    protected $defaultValue = null;
    /**
     * Determines how many fractional places are important when entities are compared during filtering or sorting. It is
     * significant to know that all values of this attribute will be converted to `Int`, so the attribute
     * number must not ever exceed maximum limits of `Int` type when scaling the number by the power
     * of ten using `indexedDecimalPlaces` as exponent.
     *
     * Generated from protobuf field <code>int32 indexedDecimalPlaces = 14;</code>
     */
    protected $indexedDecimalPlaces = 0;
    /**
     * Contains attribute name converted to different naming conventions.
     *
     * Generated from protobuf field <code>repeated .io.evitadb.externalApi.grpc.generated.GrpcNameVariant nameVariant = 15;</code>
     */
    private $nameVariant;
    /**
     * Contains true if the attribute was inherited from the original object via reflected reference relation
     *
     * Generated from protobuf field <code>bool inherited = 16;</code>
     */
    protected $inherited = false;
    /**
     * When attribute is unique it is automatically filterable, and it is ensured there is exactly one single entity
     * having certain value of this attribute among other entities in the same collection.
     * As an example of unique attribute can be EAN - there is no sense in having two entities with same EAN, and it's
     * better to have this ensured by the database engine.
     *
     * Generated from protobuf field <code>repeated .io.evitadb.externalApi.grpc.generated.GrpcScopedAttributeUniquenessType uniqueInScopes = 17;</code>
     */
    private $uniqueInScopes;
    /**
     * When attribute is unique globally it is automatically filterable, and it is ensured there is exactly one single
     * entity having certain value of this attribute in entire {&#64;link CatalogContract}.
     * {&#64;link AttributeSchemaContract#getType() Type} of the unique attribute must implement {&#64;link Comparable} interface.
     * As an example of unique attribute can be URL - there is no sense in having two entities with same URL, and it's
     * better to have this ensured by the database engine.
     *
     * Generated from protobuf field <code>repeated .io.evitadb.externalApi.grpc.generated.GrpcScopedGlobalAttributeUniquenessType uniqueGloballyInScopes = 18;</code>
     */
    private $uniqueGloballyInScopes;
    /**
     * When attribute is filterable, it is possible to filter entities by this attribute. Do not mark attribute
     * as filterable unless you know that you'll search entities by this attribute. Each filterable attribute occupies
     * (memory/disk) space in the form of index.
     * When attribute is filterable, extra result `attributeHistogram`
     * can be requested for this attribute.
     *
     * Generated from protobuf field <code>repeated .io.evitadb.externalApi.grpc.generated.GrpcEntityScope filterableInScopes = 19;</code>
     */
    private $filterableInScopes;
    /**
     * When attribute is sortable, it is possible to sort entities by this attribute. Do not mark attribute
     * as sortable unless you know that you'll sort entities along this attribute. Each sortable attribute occupies
     * (memory/disk) space in the form of index.
     *
     * Generated from protobuf field <code>repeated .io.evitadb.externalApi.grpc.generated.GrpcEntityScope sortableInScopes = 20;</code>
     */
    private $sortableInScopes;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *           Contains unique name of the model. Case-sensitive. Distinguishes one model item from another
     *           within single entity instance.
     *     @type int $schemaType
     *           When this attribute schema belongs to a catalog - it is global and can have globally unique attributes enforced across whole catalog.
     *     @type \Google\Protobuf\StringValue $description
     *           Contains description of the model is optional but helps authors of the schema / client API to better
     *           explain the original purpose of the model to the consumers.
     *     @type \Google\Protobuf\StringValue $deprecationNotice
     *           Deprecation notice contains information about planned removal of this entity from the model / client API.
     *           This allows to plan and evolve the schema allowing clients to adapt early to planned breaking changes.
     *           If notice is `null`, this schema is considered not deprecated.
     *     @type int $unique
     *           When attribute is unique it is automatically filterable, and it is ensured there is exactly one single entity
     *           having certain value of this attribute among other entities in the same collection.
     *           As an example of unique attribute can be EAN - there is no sense in having two entities with same EAN, and it's
     *           better to have this ensured by the database engine.
     *           deprecated in favor of `uniqueInScopes`
     *     @type int $uniqueGlobally
     *           When attribute is unique globally it is automatically filterable, and it is ensured there is exactly one single
     *           entity having certain value of this attribute in entire {&#64;link CatalogContract}.
     *           {&#64;link AttributeSchemaContract#getType() Type} of the unique attribute must implement {&#64;link Comparable} interface.
     *           As an example of unique attribute can be URL - there is no sense in having two entities with same URL, and it's
     *           better to have this ensured by the database engine.
     *           deprecated in favor of `uniqueGloballyInScopes`
     *     @type bool $filterable
     *           When attribute is filterable, it is possible to filter entities by this attribute. Do not mark attribute
     *           as filterable unless you know that you'll search entities by this attribute. Each filterable attribute occupies
     *           (memory/disk) space in the form of index.
     *           When attribute is filterable, extra result `attributeHistogram`
     *           can be requested for this attribute.
     *           deprecated in favor of `filterableInScopes`
     *     @type bool $sortable
     *           When attribute is sortable, it is possible to sort entities by this attribute. Do not mark attribute
     *           as sortable unless you know that you'll sort entities along this attribute. Each sortable attribute occupies
     *           (memory/disk) space in the form of index.
     *           deprecated in favor of `sortableInScopes`
     *     @type bool $localized
     *           When attribute is localized, it has to be ALWAYS used in connection with specific `Locale`.
     *     @type bool $nullable
     *           When attribute is nullable, its values may be missing in the entities. Otherwise, the system will enforce
     *           non-null checks upon upserting of the entity.
     *     @type bool $representative
     *           Representative flag marks the attribute as one of the most important attributes in the entity, or when used
     *           on reference level in the {&#64;link ReferenceSchemaContract} it marks attributes distinguishing duplicated
     *           references to the same entity and is a key attribute for creating distinct indexes for such references.
     *           In overall, representative attributes should be used in developer tools along with the entity's primary key to
     *           describe the entity or reference to that entity. If the flag is used correctly, it can be very helpful to
     *           developers in quickly finding their way around the data. There should be very few representative attributes
     *           in the entity / reference type, and the ones with uniqueness significance are usually the best to choose.
     *     @type int $type
     *           Data type of the attribute. Must be one of Evita-supported values.
     *           Internally the scalar is converted into Java-corresponding data type.
     *     @type \Wtsvk\EvitaDbClient\Protocol\GrpcEvitaValue $defaultValue
     *           Default value is used when the entity is created without this attribute specified. Default values allow to pass
     *           non-null checks even if no attributes of such name are specified.
     *     @type int $indexedDecimalPlaces
     *           Determines how many fractional places are important when entities are compared during filtering or sorting. It is
     *           significant to know that all values of this attribute will be converted to `Int`, so the attribute
     *           number must not ever exceed maximum limits of `Int` type when scaling the number by the power
     *           of ten using `indexedDecimalPlaces` as exponent.
     *     @type array<\Wtsvk\EvitaDbClient\Protocol\GrpcNameVariant>|\Google\Protobuf\Internal\RepeatedField $nameVariant
     *           Contains attribute name converted to different naming conventions.
     *     @type bool $inherited
     *           Contains true if the attribute was inherited from the original object via reflected reference relation
     *     @type array<\Wtsvk\EvitaDbClient\Protocol\GrpcScopedAttributeUniquenessType>|\Google\Protobuf\Internal\RepeatedField $uniqueInScopes
     *           When attribute is unique it is automatically filterable, and it is ensured there is exactly one single entity
     *           having certain value of this attribute among other entities in the same collection.
     *           As an example of unique attribute can be EAN - there is no sense in having two entities with same EAN, and it's
     *           better to have this ensured by the database engine.
     *     @type array<\Wtsvk\EvitaDbClient\Protocol\GrpcScopedGlobalAttributeUniquenessType>|\Google\Protobuf\Internal\RepeatedField $uniqueGloballyInScopes
     *           When attribute is unique globally it is automatically filterable, and it is ensured there is exactly one single
     *           entity having certain value of this attribute in entire {&#64;link CatalogContract}.
     *           {&#64;link AttributeSchemaContract#getType() Type} of the unique attribute must implement {&#64;link Comparable} interface.
     *           As an example of unique attribute can be URL - there is no sense in having two entities with same URL, and it's
     *           better to have this ensured by the database engine.
     *     @type array<int>|\Google\Protobuf\Internal\RepeatedField $filterableInScopes
     *           When attribute is filterable, it is possible to filter entities by this attribute. Do not mark attribute
     *           as filterable unless you know that you'll search entities by this attribute. Each filterable attribute occupies
     *           (memory/disk) space in the form of index.
     *           When attribute is filterable, extra result `attributeHistogram`
     *           can be requested for this attribute.
     *     @type array<int>|\Google\Protobuf\Internal\RepeatedField $sortableInScopes
     *           When attribute is sortable, it is possible to sort entities by this attribute. Do not mark attribute
     *           as sortable unless you know that you'll sort entities along this attribute. Each sortable attribute occupies
     *           (memory/disk) space in the form of index.
     * }
     */
    public function __construct($data = NULL) {
        \Wtsvk\EvitaDbClient\Protocol\GPBMetadata\GrpcEntitySchema::initOnce();
        parent::__construct($data);
    }

    /**
     * Contains unique name of the model. Case-sensitive. Distinguishes one model item from another
     * within single entity instance.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Contains unique name of the model. Case-sensitive. Distinguishes one model item from another
     * within single entity instance.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * When this attribute schema belongs to a catalog - it is global and can have globally unique attributes enforced across whole catalog.
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcAttributeSchemaType schemaType = 2;</code>
     * @return int
     */
    public function getSchemaType()
    {
        return $this->schemaType;
    }

    /**
     * When this attribute schema belongs to a catalog - it is global and can have globally unique attributes enforced across whole catalog.
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcAttributeSchemaType schemaType = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setSchemaType($var)
    {
        GPBUtil::checkEnum($var, \Wtsvk\EvitaDbClient\Protocol\GrpcAttributeSchemaType::class);
        $this->schemaType = $var;

        return $this;
    }

    /**
     * Contains description of the model is optional but helps authors of the schema / client API to better
     * explain the original purpose of the model to the consumers.
     *
     * Generated from protobuf field <code>.google.protobuf.StringValue description = 3;</code>
     * @return \Google\Protobuf\StringValue|null
     */
    public function getDescription()
    {
        return $this->description;
    }

    public function hasDescription()
    {
        return isset($this->description);
    }

    public function clearDescription()
    {
        unset($this->description);
    }

    /**
     * Returns the unboxed value from <code>getDescription()</code>

     * Contains description of the model is optional but helps authors of the schema / client API to better
     * explain the original purpose of the model to the consumers.
     *
     * Generated from protobuf field <code>.google.protobuf.StringValue description = 3;</code>
     * @return string|null
     */
    public function getDescriptionUnwrapped()
    {
        return $this->readWrapperValue("description");
    }

    /**
     * Contains description of the model is optional but helps authors of the schema / client API to better
     * explain the original purpose of the model to the consumers.
     *
     * Generated from protobuf field <code>.google.protobuf.StringValue description = 3;</code>
     * @param \Google\Protobuf\StringValue $var
     * @return $this
     */
    public function setDescription($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\StringValue::class);
        $this->description = $var;

        return $this;
    }

    /**
     * Sets the field by wrapping a primitive type in a Google\Protobuf\StringValue object.

     * Contains description of the model is optional but helps authors of the schema / client API to better
     * explain the original purpose of the model to the consumers.
     *
     * Generated from protobuf field <code>.google.protobuf.StringValue description = 3;</code>
     * @param string|null $var
     * @return $this
     */
    public function setDescriptionUnwrapped($var)
    {
        $this->writeWrapperValue("description", $var);
        return $this;}

    /**
     * Deprecation notice contains information about planned removal of this entity from the model / client API.
     * This allows to plan and evolve the schema allowing clients to adapt early to planned breaking changes.
     * If notice is `null`, this schema is considered not deprecated.
     *
     * Generated from protobuf field <code>.google.protobuf.StringValue deprecationNotice = 4;</code>
     * @return \Google\Protobuf\StringValue|null
     */
    public function getDeprecationNotice()
    {
        return $this->deprecationNotice;
    }

    public function hasDeprecationNotice()
    {
        return isset($this->deprecationNotice);
    }

    public function clearDeprecationNotice()
    {
        unset($this->deprecationNotice);
    }

    /**
     * Returns the unboxed value from <code>getDeprecationNotice()</code>

     * Deprecation notice contains information about planned removal of this entity from the model / client API.
     * This allows to plan and evolve the schema allowing clients to adapt early to planned breaking changes.
     * If notice is `null`, this schema is considered not deprecated.
     *
     * Generated from protobuf field <code>.google.protobuf.StringValue deprecationNotice = 4;</code>
     * @return string|null
     */
    public function getDeprecationNoticeUnwrapped()
    {
        return $this->readWrapperValue("deprecationNotice");
    }

    /**
     * Deprecation notice contains information about planned removal of this entity from the model / client API.
     * This allows to plan and evolve the schema allowing clients to adapt early to planned breaking changes.
     * If notice is `null`, this schema is considered not deprecated.
     *
     * Generated from protobuf field <code>.google.protobuf.StringValue deprecationNotice = 4;</code>
     * @param \Google\Protobuf\StringValue $var
     * @return $this
     */
    public function setDeprecationNotice($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\StringValue::class);
        $this->deprecationNotice = $var;

        return $this;
    }

    /**
     * Sets the field by wrapping a primitive type in a Google\Protobuf\StringValue object.

     * Deprecation notice contains information about planned removal of this entity from the model / client API.
     * This allows to plan and evolve the schema allowing clients to adapt early to planned breaking changes.
     * If notice is `null`, this schema is considered not deprecated.
     *
     * Generated from protobuf field <code>.google.protobuf.StringValue deprecationNotice = 4;</code>
     * @param string|null $var
     * @return $this
     */
    public function setDeprecationNoticeUnwrapped($var)
    {
        $this->writeWrapperValue("deprecationNotice", $var);
        return $this;}

    /**
     * When attribute is unique it is automatically filterable, and it is ensured there is exactly one single entity
     * having certain value of this attribute among other entities in the same collection.
     * As an example of unique attribute can be EAN - there is no sense in having two entities with same EAN, and it's
     * better to have this ensured by the database engine.
     * deprecated in favor of `uniqueInScopes`
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcAttributeUniquenessType unique = 5 [deprecated = true];</code>
     * @return int
     * @deprecated
     */
    public function getUnique()
    {
        @trigger_error('unique is deprecated.', E_USER_DEPRECATED);
        return $this->unique;
    }

    /**
     * When attribute is unique it is automatically filterable, and it is ensured there is exactly one single entity
     * having certain value of this attribute among other entities in the same collection.
     * As an example of unique attribute can be EAN - there is no sense in having two entities with same EAN, and it's
     * better to have this ensured by the database engine.
     * deprecated in favor of `uniqueInScopes`
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcAttributeUniquenessType unique = 5 [deprecated = true];</code>
     * @param int $var
     * @return $this
     * @deprecated
     */
    public function setUnique($var)
    {
        @trigger_error('unique is deprecated.', E_USER_DEPRECATED);
        GPBUtil::checkEnum($var, \Wtsvk\EvitaDbClient\Protocol\GrpcAttributeUniquenessType::class);
        $this->unique = $var;

        return $this;
    }

    /**
     * When attribute is unique globally it is automatically filterable, and it is ensured there is exactly one single
     * entity having certain value of this attribute in entire {&#64;link CatalogContract}.
     * {&#64;link AttributeSchemaContract#getType() Type} of the unique attribute must implement {&#64;link Comparable} interface.
     * As an example of unique attribute can be URL - there is no sense in having two entities with same URL, and it's
     * better to have this ensured by the database engine.
     * deprecated in favor of `uniqueGloballyInScopes`
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcGlobalAttributeUniquenessType uniqueGlobally = 6 [deprecated = true];</code>
     * @return int
     * @deprecated
     */
    public function getUniqueGlobally()
    {
        @trigger_error('uniqueGlobally is deprecated.', E_USER_DEPRECATED);
        return $this->uniqueGlobally;
    }

    /**
     * When attribute is unique globally it is automatically filterable, and it is ensured there is exactly one single
     * entity having certain value of this attribute in entire {&#64;link CatalogContract}.
     * {&#64;link AttributeSchemaContract#getType() Type} of the unique attribute must implement {&#64;link Comparable} interface.
     * As an example of unique attribute can be URL - there is no sense in having two entities with same URL, and it's
     * better to have this ensured by the database engine.
     * deprecated in favor of `uniqueGloballyInScopes`
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcGlobalAttributeUniquenessType uniqueGlobally = 6 [deprecated = true];</code>
     * @param int $var
     * @return $this
     * @deprecated
     */
    public function setUniqueGlobally($var)
    {
        @trigger_error('uniqueGlobally is deprecated.', E_USER_DEPRECATED);
        GPBUtil::checkEnum($var, \Wtsvk\EvitaDbClient\Protocol\GrpcGlobalAttributeUniquenessType::class);
        $this->uniqueGlobally = $var;

        return $this;
    }

    /**
     * When attribute is filterable, it is possible to filter entities by this attribute. Do not mark attribute
     * as filterable unless you know that you'll search entities by this attribute. Each filterable attribute occupies
     * (memory/disk) space in the form of index.
     * When attribute is filterable, extra result `attributeHistogram`
     * can be requested for this attribute.
     * deprecated in favor of `filterableInScopes`
     *
     * Generated from protobuf field <code>bool filterable = 7 [deprecated = true];</code>
     * @return bool
     * @deprecated
     */
    public function getFilterable()
    {
        @trigger_error('filterable is deprecated.', E_USER_DEPRECATED);
        return $this->filterable;
    }

    /**
     * When attribute is filterable, it is possible to filter entities by this attribute. Do not mark attribute
     * as filterable unless you know that you'll search entities by this attribute. Each filterable attribute occupies
     * (memory/disk) space in the form of index.
     * When attribute is filterable, extra result `attributeHistogram`
     * can be requested for this attribute.
     * deprecated in favor of `filterableInScopes`
     *
     * Generated from protobuf field <code>bool filterable = 7 [deprecated = true];</code>
     * @param bool $var
     * @return $this
     * @deprecated
     */
    public function setFilterable($var)
    {
        @trigger_error('filterable is deprecated.', E_USER_DEPRECATED);
        GPBUtil::checkBool($var);
        $this->filterable = $var;

        return $this;
    }

    /**
     * When attribute is sortable, it is possible to sort entities by this attribute. Do not mark attribute
     * as sortable unless you know that you'll sort entities along this attribute. Each sortable attribute occupies
     * (memory/disk) space in the form of index.
     * deprecated in favor of `sortableInScopes`
     *
     * Generated from protobuf field <code>bool sortable = 8 [deprecated = true];</code>
     * @return bool
     * @deprecated
     */
    public function getSortable()
    {
        @trigger_error('sortable is deprecated.', E_USER_DEPRECATED);
        return $this->sortable;
    }

    /**
     * When attribute is sortable, it is possible to sort entities by this attribute. Do not mark attribute
     * as sortable unless you know that you'll sort entities along this attribute. Each sortable attribute occupies
     * (memory/disk) space in the form of index.
     * deprecated in favor of `sortableInScopes`
     *
     * Generated from protobuf field <code>bool sortable = 8 [deprecated = true];</code>
     * @param bool $var
     * @return $this
     * @deprecated
     */
    public function setSortable($var)
    {
        @trigger_error('sortable is deprecated.', E_USER_DEPRECATED);
        GPBUtil::checkBool($var);
        $this->sortable = $var;

        return $this;
    }

    /**
     * When attribute is localized, it has to be ALWAYS used in connection with specific `Locale`.
     *
     * Generated from protobuf field <code>bool localized = 9;</code>
     * @return bool
     */
    public function getLocalized()
    {
        return $this->localized;
    }

    /**
     * When attribute is localized, it has to be ALWAYS used in connection with specific `Locale`.
     *
     * Generated from protobuf field <code>bool localized = 9;</code>
     * @param bool $var
     * @return $this
     */
    public function setLocalized($var)
    {
        GPBUtil::checkBool($var);
        $this->localized = $var;

        return $this;
    }

    /**
     * When attribute is nullable, its values may be missing in the entities. Otherwise, the system will enforce
     * non-null checks upon upserting of the entity.
     *
     * Generated from protobuf field <code>bool nullable = 10;</code>
     * @return bool
     */
    public function getNullable()
    {
        return $this->nullable;
    }

    /**
     * When attribute is nullable, its values may be missing in the entities. Otherwise, the system will enforce
     * non-null checks upon upserting of the entity.
     *
     * Generated from protobuf field <code>bool nullable = 10;</code>
     * @param bool $var
     * @return $this
     */
    public function setNullable($var)
    {
        GPBUtil::checkBool($var);
        $this->nullable = $var;

        return $this;
    }

    /**
     * Representative flag marks the attribute as one of the most important attributes in the entity, or when used
     * on reference level in the {&#64;link ReferenceSchemaContract} it marks attributes distinguishing duplicated
     * references to the same entity and is a key attribute for creating distinct indexes for such references.
     * In overall, representative attributes should be used in developer tools along with the entity's primary key to
     * describe the entity or reference to that entity. If the flag is used correctly, it can be very helpful to
     * developers in quickly finding their way around the data. There should be very few representative attributes
     * in the entity / reference type, and the ones with uniqueness significance are usually the best to choose.
     *
     * Generated from protobuf field <code>bool representative = 11;</code>
     * @return bool
     */
    public function getRepresentative()
    {
        return $this->representative;
    }

    /**
     * Representative flag marks the attribute as one of the most important attributes in the entity, or when used
     * on reference level in the {&#64;link ReferenceSchemaContract} it marks attributes distinguishing duplicated
     * references to the same entity and is a key attribute for creating distinct indexes for such references.
     * In overall, representative attributes should be used in developer tools along with the entity's primary key to
     * describe the entity or reference to that entity. If the flag is used correctly, it can be very helpful to
     * developers in quickly finding their way around the data. There should be very few representative attributes
     * in the entity / reference type, and the ones with uniqueness significance are usually the best to choose.
     *
     * Generated from protobuf field <code>bool representative = 11;</code>
     * @param bool $var
     * @return $this
     */
    public function setRepresentative($var)
    {
        GPBUtil::checkBool($var);
        $this->representative = $var;

        return $this;
    }

    /**
     * Data type of the attribute. Must be one of Evita-supported values.
     * Internally the scalar is converted into Java-corresponding data type.
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcEvitaDataType type = 12;</code>
     * @return int
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Data type of the attribute. Must be one of Evita-supported values.
     * Internally the scalar is converted into Java-corresponding data type.
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcEvitaDataType type = 12;</code>
     * @param int $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkEnum($var, \Wtsvk\EvitaDbClient\Protocol\GrpcEvitaDataType::class);
        $this->type = $var;

        return $this;
    }

    /**
     * Default value is used when the entity is created without this attribute specified. Default values allow to pass
     * non-null checks even if no attributes of such name are specified.
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcEvitaValue defaultValue = 13;</code>
     * @return \Wtsvk\EvitaDbClient\Protocol\GrpcEvitaValue|null
     */
    public function getDefaultValue()
    {
        return $this->defaultValue;
    }

    public function hasDefaultValue()
    {
        return isset($this->defaultValue);
    }

    public function clearDefaultValue()
    {
        unset($this->defaultValue);
    }

    /**
     * Default value is used when the entity is created without this attribute specified. Default values allow to pass
     * non-null checks even if no attributes of such name are specified.
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcEvitaValue defaultValue = 13;</code>
     * @param \Wtsvk\EvitaDbClient\Protocol\GrpcEvitaValue $var
     * @return $this
     */
    public function setDefaultValue($var)
    {
        GPBUtil::checkMessage($var, \Wtsvk\EvitaDbClient\Protocol\GrpcEvitaValue::class);
        $this->defaultValue = $var;

        return $this;
    }

    /**
     * Determines how many fractional places are important when entities are compared during filtering or sorting. It is
     * significant to know that all values of this attribute will be converted to `Int`, so the attribute
     * number must not ever exceed maximum limits of `Int` type when scaling the number by the power
     * of ten using `indexedDecimalPlaces` as exponent.
     *
     * Generated from protobuf field <code>int32 indexedDecimalPlaces = 14;</code>
     * @return int
     */
    public function getIndexedDecimalPlaces()
    {
        return $this->indexedDecimalPlaces;
    }

    /**
     * Determines how many fractional places are important when entities are compared during filtering or sorting. It is
     * significant to know that all values of this attribute will be converted to `Int`, so the attribute
     * number must not ever exceed maximum limits of `Int` type when scaling the number by the power
     * of ten using `indexedDecimalPlaces` as exponent.
     *
     * Generated from protobuf field <code>int32 indexedDecimalPlaces = 14;</code>
     * @param int $var
     * @return $this
     */
    public function setIndexedDecimalPlaces($var)
    {
        GPBUtil::checkInt32($var);
        $this->indexedDecimalPlaces = $var;

        return $this;
    }

    /**
     * Contains attribute name converted to different naming conventions.
     *
     * Generated from protobuf field <code>repeated .io.evitadb.externalApi.grpc.generated.GrpcNameVariant nameVariant = 15;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getNameVariant()
    {
        return $this->nameVariant;
    }

    /**
     * Contains attribute name converted to different naming conventions.
     *
     * Generated from protobuf field <code>repeated .io.evitadb.externalApi.grpc.generated.GrpcNameVariant nameVariant = 15;</code>
     * @param array<\Wtsvk\EvitaDbClient\Protocol\GrpcNameVariant>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setNameVariant($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Wtsvk\EvitaDbClient\Protocol\GrpcNameVariant::class);
        $this->nameVariant = $arr;

        return $this;
    }

    /**
     * Contains true if the attribute was inherited from the original object via reflected reference relation
     *
     * Generated from protobuf field <code>bool inherited = 16;</code>
     * @return bool
     */
    public function getInherited()
    {
        return $this->inherited;
    }

    /**
     * Contains true if the attribute was inherited from the original object via reflected reference relation
     *
     * Generated from protobuf field <code>bool inherited = 16;</code>
     * @param bool $var
     * @return $this
     */
    public function setInherited($var)
    {
        GPBUtil::checkBool($var);
        $this->inherited = $var;

        return $this;
    }

    /**
     * When attribute is unique it is automatically filterable, and it is ensured there is exactly one single entity
     * having certain value of this attribute among other entities in the same collection.
     * As an example of unique attribute can be EAN - there is no sense in having two entities with same EAN, and it's
     * better to have this ensured by the database engine.
     *
     * Generated from protobuf field <code>repeated .io.evitadb.externalApi.grpc.generated.GrpcScopedAttributeUniquenessType uniqueInScopes = 17;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getUniqueInScopes()
    {
        return $this->uniqueInScopes;
    }

    /**
     * When attribute is unique it is automatically filterable, and it is ensured there is exactly one single entity
     * having certain value of this attribute among other entities in the same collection.
     * As an example of unique attribute can be EAN - there is no sense in having two entities with same EAN, and it's
     * better to have this ensured by the database engine.
     *
     * Generated from protobuf field <code>repeated .io.evitadb.externalApi.grpc.generated.GrpcScopedAttributeUniquenessType uniqueInScopes = 17;</code>
     * @param array<\Wtsvk\EvitaDbClient\Protocol\GrpcScopedAttributeUniquenessType>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setUniqueInScopes($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Wtsvk\EvitaDbClient\Protocol\GrpcScopedAttributeUniquenessType::class);
        $this->uniqueInScopes = $arr;

        return $this;
    }

    /**
     * When attribute is unique globally it is automatically filterable, and it is ensured there is exactly one single
     * entity having certain value of this attribute in entire {&#64;link CatalogContract}.
     * {&#64;link AttributeSchemaContract#getType() Type} of the unique attribute must implement {&#64;link Comparable} interface.
     * As an example of unique attribute can be URL - there is no sense in having two entities with same URL, and it's
     * better to have this ensured by the database engine.
     *
     * Generated from protobuf field <code>repeated .io.evitadb.externalApi.grpc.generated.GrpcScopedGlobalAttributeUniquenessType uniqueGloballyInScopes = 18;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getUniqueGloballyInScopes()
    {
        return $this->uniqueGloballyInScopes;
    }

    /**
     * When attribute is unique globally it is automatically filterable, and it is ensured there is exactly one single
     * entity having certain value of this attribute in entire {&#64;link CatalogContract}.
     * {&#64;link AttributeSchemaContract#getType() Type} of the unique attribute must implement {&#64;link Comparable} interface.
     * As an example of unique attribute can be URL - there is no sense in having two entities with same URL, and it's
     * better to have this ensured by the database engine.
     *
     * Generated from protobuf field <code>repeated .io.evitadb.externalApi.grpc.generated.GrpcScopedGlobalAttributeUniquenessType uniqueGloballyInScopes = 18;</code>
     * @param array<\Wtsvk\EvitaDbClient\Protocol\GrpcScopedGlobalAttributeUniquenessType>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setUniqueGloballyInScopes($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Wtsvk\EvitaDbClient\Protocol\GrpcScopedGlobalAttributeUniquenessType::class);
        $this->uniqueGloballyInScopes = $arr;

        return $this;
    }

    /**
     * When attribute is filterable, it is possible to filter entities by this attribute. Do not mark attribute
     * as filterable unless you know that you'll search entities by this attribute. Each filterable attribute occupies
     * (memory/disk) space in the form of index.
     * When attribute is filterable, extra result `attributeHistogram`
     * can be requested for this attribute.
     *
     * Generated from protobuf field <code>repeated .io.evitadb.externalApi.grpc.generated.GrpcEntityScope filterableInScopes = 19;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getFilterableInScopes()
    {
        return $this->filterableInScopes;
    }

    /**
     * When attribute is filterable, it is possible to filter entities by this attribute. Do not mark attribute
     * as filterable unless you know that you'll search entities by this attribute. Each filterable attribute occupies
     * (memory/disk) space in the form of index.
     * When attribute is filterable, extra result `attributeHistogram`
     * can be requested for this attribute.
     *
     * Generated from protobuf field <code>repeated .io.evitadb.externalApi.grpc.generated.GrpcEntityScope filterableInScopes = 19;</code>
     * @param array<int>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setFilterableInScopes($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::ENUM, \Wtsvk\EvitaDbClient\Protocol\GrpcEntityScope::class);
        $this->filterableInScopes = $arr;

        return $this;
    }

    /**
     * When attribute is sortable, it is possible to sort entities by this attribute. Do not mark attribute
     * as sortable unless you know that you'll sort entities along this attribute. Each sortable attribute occupies
     * (memory/disk) space in the form of index.
     *
     * Generated from protobuf field <code>repeated .io.evitadb.externalApi.grpc.generated.GrpcEntityScope sortableInScopes = 20;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSortableInScopes()
    {
        return $this->sortableInScopes;
    }

    /**
     * When attribute is sortable, it is possible to sort entities by this attribute. Do not mark attribute
     * as sortable unless you know that you'll sort entities along this attribute. Each sortable attribute occupies
     * (memory/disk) space in the form of index.
     *
     * Generated from protobuf field <code>repeated .io.evitadb.externalApi.grpc.generated.GrpcEntityScope sortableInScopes = 20;</code>
     * @param array<int>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSortableInScopes($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::ENUM, \Wtsvk\EvitaDbClient\Protocol\GrpcEntityScope::class);
        $this->sortableInScopes = $arr;

        return $this;
    }

}

