<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GrpcAssociatedDataMutations.proto

namespace Wtsvk\EvitaDbClient\Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Remove associated data mutation will drop existing associatedData - ie.generates new version of the associated data
 * with tombstone on it.
 *
 * Generated from protobuf message <code>io.evitadb.externalApi.grpc.generated.GrpcRemoveAssociatedDataMutation</code>
 */
class GrpcRemoveAssociatedDataMutation extends \Google\Protobuf\Internal\Message
{
    /**
     * Unique name of the associatedData. Case-sensitive. Distinguishes one associated data item from another within
     * single entity instance.
     *
     * Generated from protobuf field <code>string associatedDataName = 1;</code>
     */
    protected $associatedDataName = '';
    /**
     * Contains locale in case the associatedData is locale specific.
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcLocale associatedDataLocale = 2;</code>
     */
    protected $associatedDataLocale = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $associatedDataName
     *           Unique name of the associatedData. Case-sensitive. Distinguishes one associated data item from another within
     *           single entity instance.
     *     @type \Wtsvk\EvitaDbClient\Protocol\GrpcLocale $associatedDataLocale
     *           Contains locale in case the associatedData is locale specific.
     * }
     */
    public function __construct($data = NULL) {
        \Wtsvk\EvitaDbClient\Protocol\GPBMetadata\GrpcAssociatedDataMutations::initOnce();
        parent::__construct($data);
    }

    /**
     * Unique name of the associatedData. Case-sensitive. Distinguishes one associated data item from another within
     * single entity instance.
     *
     * Generated from protobuf field <code>string associatedDataName = 1;</code>
     * @return string
     */
    public function getAssociatedDataName()
    {
        return $this->associatedDataName;
    }

    /**
     * Unique name of the associatedData. Case-sensitive. Distinguishes one associated data item from another within
     * single entity instance.
     *
     * Generated from protobuf field <code>string associatedDataName = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setAssociatedDataName($var)
    {
        GPBUtil::checkString($var, True);
        $this->associatedDataName = $var;

        return $this;
    }

    /**
     * Contains locale in case the associatedData is locale specific.
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcLocale associatedDataLocale = 2;</code>
     * @return \Wtsvk\EvitaDbClient\Protocol\GrpcLocale|null
     */
    public function getAssociatedDataLocale()
    {
        return $this->associatedDataLocale;
    }

    public function hasAssociatedDataLocale()
    {
        return isset($this->associatedDataLocale);
    }

    public function clearAssociatedDataLocale()
    {
        unset($this->associatedDataLocale);
    }

    /**
     * Contains locale in case the associatedData is locale specific.
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcLocale associatedDataLocale = 2;</code>
     * @param \Wtsvk\EvitaDbClient\Protocol\GrpcLocale $var
     * @return $this
     */
    public function setAssociatedDataLocale($var)
    {
        GPBUtil::checkMessage($var, \Wtsvk\EvitaDbClient\Protocol\GrpcLocale::class);
        $this->associatedDataLocale = $var;

        return $this;
    }

}

