<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GrpcReferenceSchemaMutations.proto

namespace Wtsvk\EvitaDbClient\Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Mutation is responsible for setting value to a `ReferenceSchema.referencedGroupType`in `EntitySchema`.
 *
 * Generated from protobuf message <code>io.evitadb.externalApi.grpc.generated.GrpcModifyReferenceSchemaRelatedEntityGroupMutation</code>
 */
class GrpcModifyReferenceSchemaRelatedEntityGroupMutation extends \Google\Protobuf\Internal\Message
{
    /**
     * Name of the reference the mutation is targeting.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     */
    protected $name = '';
    /**
     * Reference to `EntitySchema.name` of the referenced group entity. Might be also any `String`
     * that identifies type some external resource not maintained by Evita.
     *
     * Generated from protobuf field <code>.google.protobuf.StringValue referencedGroupType = 2;</code>
     */
    protected $referencedGroupType = null;
    /**
     * Whether `referencedGroupType` refers to any existing `EntitySchema.name` that is maintained by Evita.
     *
     * Generated from protobuf field <code>bool referencedGroupTypeManaged = 3;</code>
     */
    protected $referencedGroupTypeManaged = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *           Name of the reference the mutation is targeting.
     *     @type \Google\Protobuf\StringValue $referencedGroupType
     *           Reference to `EntitySchema.name` of the referenced group entity. Might be also any `String`
     *           that identifies type some external resource not maintained by Evita.
     *     @type bool $referencedGroupTypeManaged
     *           Whether `referencedGroupType` refers to any existing `EntitySchema.name` that is maintained by Evita.
     * }
     */
    public function __construct($data = NULL) {
        \Wtsvk\EvitaDbClient\Protocol\GPBMetadata\GrpcReferenceSchemaMutations::initOnce();
        parent::__construct($data);
    }

    /**
     * Name of the reference the mutation is targeting.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Name of the reference the mutation is targeting.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Reference to `EntitySchema.name` of the referenced group entity. Might be also any `String`
     * that identifies type some external resource not maintained by Evita.
     *
     * Generated from protobuf field <code>.google.protobuf.StringValue referencedGroupType = 2;</code>
     * @return \Google\Protobuf\StringValue|null
     */
    public function getReferencedGroupType()
    {
        return $this->referencedGroupType;
    }

    public function hasReferencedGroupType()
    {
        return isset($this->referencedGroupType);
    }

    public function clearReferencedGroupType()
    {
        unset($this->referencedGroupType);
    }

    /**
     * Returns the unboxed value from <code>getReferencedGroupType()</code>

     * Reference to `EntitySchema.name` of the referenced group entity. Might be also any `String`
     * that identifies type some external resource not maintained by Evita.
     *
     * Generated from protobuf field <code>.google.protobuf.StringValue referencedGroupType = 2;</code>
     * @return string|null
     */
    public function getReferencedGroupTypeUnwrapped()
    {
        return $this->readWrapperValue("referencedGroupType");
    }

    /**
     * Reference to `EntitySchema.name` of the referenced group entity. Might be also any `String`
     * that identifies type some external resource not maintained by Evita.
     *
     * Generated from protobuf field <code>.google.protobuf.StringValue referencedGroupType = 2;</code>
     * @param \Google\Protobuf\StringValue $var
     * @return $this
     */
    public function setReferencedGroupType($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\StringValue::class);
        $this->referencedGroupType = $var;

        return $this;
    }

    /**
     * Sets the field by wrapping a primitive type in a Google\Protobuf\StringValue object.

     * Reference to `EntitySchema.name` of the referenced group entity. Might be also any `String`
     * that identifies type some external resource not maintained by Evita.
     *
     * Generated from protobuf field <code>.google.protobuf.StringValue referencedGroupType = 2;</code>
     * @param string|null $var
     * @return $this
     */
    public function setReferencedGroupTypeUnwrapped($var)
    {
        $this->writeWrapperValue("referencedGroupType", $var);
        return $this;}

    /**
     * Whether `referencedGroupType` refers to any existing `EntitySchema.name` that is maintained by Evita.
     *
     * Generated from protobuf field <code>bool referencedGroupTypeManaged = 3;</code>
     * @return bool
     */
    public function getReferencedGroupTypeManaged()
    {
        return $this->referencedGroupTypeManaged;
    }

    /**
     * Whether `referencedGroupType` refers to any existing `EntitySchema.name` that is maintained by Evita.
     *
     * Generated from protobuf field <code>bool referencedGroupTypeManaged = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setReferencedGroupTypeManaged($var)
    {
        GPBUtil::checkBool($var);
        $this->referencedGroupTypeManaged = $var;

        return $this;
    }

}

