<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GrpcChangeCapture.proto

namespace Wtsvk\EvitaDbClient\Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Record for the criteria of the capture request allowing to limit mutations to specific area of interest an its
 * properties.
 *
 * Generated from protobuf message <code>io.evitadb.externalApi.grpc.generated.GrpcChangeCaptureCriteria</code>
 */
class GrpcChangeCaptureCriteria extends \Google\Protobuf\Internal\Message
{
    /**
     * The area of capture - either schema or data (correlates with the site)
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcChangeCaptureArea area = 1;</code>
     */
    protected $area = 0;
    protected $site;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $area
     *           The area of capture - either schema or data (correlates with the site)
     *     @type \Wtsvk\EvitaDbClient\Protocol\GrpcChangeCaptureSchemaSite $schemaSite
     *           Criteria for schema capture
     *     @type \Wtsvk\EvitaDbClient\Protocol\GrpcChangeCaptureDataSite $dataSite
     *           Criteria for data capture
     * }
     */
    public function __construct($data = NULL) {
        \Wtsvk\EvitaDbClient\Protocol\GPBMetadata\GrpcChangeCapture::initOnce();
        parent::__construct($data);
    }

    /**
     * The area of capture - either schema or data (correlates with the site)
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcChangeCaptureArea area = 1;</code>
     * @return int
     */
    public function getArea()
    {
        return $this->area;
    }

    /**
     * The area of capture - either schema or data (correlates with the site)
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcChangeCaptureArea area = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setArea($var)
    {
        GPBUtil::checkEnum($var, \Wtsvk\EvitaDbClient\Protocol\GrpcChangeCaptureArea::class);
        $this->area = $var;

        return $this;
    }

    /**
     * Criteria for schema capture
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcChangeCaptureSchemaSite schemaSite = 2;</code>
     * @return \Wtsvk\EvitaDbClient\Protocol\GrpcChangeCaptureSchemaSite|null
     */
    public function getSchemaSite()
    {
        return $this->readOneof(2);
    }

    public function hasSchemaSite()
    {
        return $this->hasOneof(2);
    }

    /**
     * Criteria for schema capture
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcChangeCaptureSchemaSite schemaSite = 2;</code>
     * @param \Wtsvk\EvitaDbClient\Protocol\GrpcChangeCaptureSchemaSite $var
     * @return $this
     */
    public function setSchemaSite($var)
    {
        GPBUtil::checkMessage($var, \Wtsvk\EvitaDbClient\Protocol\GrpcChangeCaptureSchemaSite::class);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * Criteria for data capture
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcChangeCaptureDataSite dataSite = 3;</code>
     * @return \Wtsvk\EvitaDbClient\Protocol\GrpcChangeCaptureDataSite|null
     */
    public function getDataSite()
    {
        return $this->readOneof(3);
    }

    public function hasDataSite()
    {
        return $this->hasOneof(3);
    }

    /**
     * Criteria for data capture
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcChangeCaptureDataSite dataSite = 3;</code>
     * @param \Wtsvk\EvitaDbClient\Protocol\GrpcChangeCaptureDataSite $var
     * @return $this
     */
    public function setDataSite($var)
    {
        GPBUtil::checkMessage($var, \Wtsvk\EvitaDbClient\Protocol\GrpcChangeCaptureDataSite::class);
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getSite()
    {
        return $this->whichOneof("site");
    }

}

