<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GrpcEvitaSessionAPI.proto

namespace Wtsvk\EvitaDbClient\Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Response to DeleteCollection request.
 *
 * Generated from protobuf message <code>io.evitadb.externalApi.grpc.generated.GrpcDeleteCollectionResponse</code>
 */
class GrpcDeleteCollectionResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * True, if the collection was deleted.
     *
     * Generated from protobuf field <code>bool deleted = 1;</code>
     */
    protected $deleted = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $deleted
     *           True, if the collection was deleted.
     * }
     */
    public function __construct($data = NULL) {
        \Wtsvk\EvitaDbClient\Protocol\GPBMetadata\GrpcEvitaSessionAPI::initOnce();
        parent::__construct($data);
    }

    /**
     * True, if the collection was deleted.
     *
     * Generated from protobuf field <code>bool deleted = 1;</code>
     * @return bool
     */
    public function getDeleted()
    {
        return $this->deleted;
    }

    /**
     * True, if the collection was deleted.
     *
     * Generated from protobuf field <code>bool deleted = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setDeleted($var)
    {
        GPBUtil::checkBool($var);
        $this->deleted = $var;

        return $this;
    }

}

