<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GrpcEnums.proto

namespace Wtsvk\EvitaDbClient\Protocol;

use UnexpectedValueException;

/**
 *Enum contains all query execution phases, that leads from request to response.
 *
 * Protobuf type <code>io.evitadb.externalApi.grpc.generated.GrpcQueryPhase</code>
 */
class GrpcQueryPhase
{
    /**
     * Entire query execution time.
     *
     * Generated from protobuf enum <code>OVERALL = 0;</code>
     */
    const OVERALL = 0;
    /**
     * Entire planning phase of the query execution.
     *
     * Generated from protobuf enum <code>PLANNING = 1;</code>
     */
    const PLANNING = 1;
    /**
     * Planning phase of the inner query execution.
     *
     * Generated from protobuf enum <code>PLANNING_NESTED_QUERY = 2;</code>
     */
    const PLANNING_NESTED_QUERY = 2;
    /**
     * Determining which indexes should be used.
     *
     * Generated from protobuf enum <code>PLANNING_INDEX_USAGE = 3;</code>
     */
    const PLANNING_INDEX_USAGE = 3;
    /**
     * Creating formula for filtering entities.
     *
     * Generated from protobuf enum <code>PLANNING_FILTER = 4;</code>
     */
    const PLANNING_FILTER = 4;
    /**
     * Creating formula for nested query.
     *
     * Generated from protobuf enum <code>PLANNING_FILTER_NESTED_QUERY = 5;</code>
     */
    const PLANNING_FILTER_NESTED_QUERY = 5;
    /**
     * Creating alternative formula for filtering entities.
     *
     * Generated from protobuf enum <code>PLANNING_FILTER_ALTERNATIVE = 6;</code>
     */
    const PLANNING_FILTER_ALTERNATIVE = 6;
    /**
     * Creating formula for sorting result entities.
     *
     * Generated from protobuf enum <code>PLANNING_SORT = 7;</code>
     */
    const PLANNING_SORT = 7;
    /**
     * Creating alternative formula for sorting result entities.
     *
     * Generated from protobuf enum <code>PLANNING_SORT_ALTERNATIVE = 8;</code>
     */
    const PLANNING_SORT_ALTERNATIVE = 8;
    /**
     * Creating factories for requested extra results.
     *
     * Generated from protobuf enum <code>PLANNING_EXTRA_RESULT_FABRICATION = 9;</code>
     */
    const PLANNING_EXTRA_RESULT_FABRICATION = 9;
    /**
     * Creating factories for requested extra results based on alternative indexes.
     *
     * Generated from protobuf enum <code>PLANNING_EXTRA_RESULT_FABRICATION_ALTERNATIVE = 10;</code>
     */
    const PLANNING_EXTRA_RESULT_FABRICATION_ALTERNATIVE = 10;
    /**
     * Entire query execution phase.
     *
     * Generated from protobuf enum <code>EXECUTION = 11;</code>
     */
    const EXECUTION = 11;
    /**
     * Prefetching entities that should be examined instead of consulting indexes.
     *
     * Generated from protobuf enum <code>EXECUTION_PREFETCH = 12;</code>
     */
    const EXECUTION_PREFETCH = 12;
    /**
     * Computing entities that should be returned in output (filtering).
     *
     * Generated from protobuf enum <code>EXECUTION_FILTER = 13;</code>
     */
    const EXECUTION_FILTER = 13;
    /**
     * Computing entities within nested query that should be returned in output (filtering).
     *
     * Generated from protobuf enum <code>EXECUTION_FILTER_NESTED_QUERY = 14;</code>
     */
    const EXECUTION_FILTER_NESTED_QUERY = 14;
    /**
     * Sorting output entities and slicing requested page.
     *
     * Generated from protobuf enum <code>EXECUTION_SORT_AND_SLICE = 15;</code>
     */
    const EXECUTION_SORT_AND_SLICE = 15;
    /**
     * Fabricating requested extra results.
     *
     * Generated from protobuf enum <code>EXTRA_RESULTS_FABRICATION = 16;</code>
     */
    const EXTRA_RESULTS_FABRICATION = 16;
    /**
     * Fabricating requested single extra result.
     *
     * Generated from protobuf enum <code>EXTRA_RESULT_ITEM_FABRICATION = 17;</code>
     */
    const EXTRA_RESULT_ITEM_FABRICATION = 17;
    /**
     * Fetching rich data from the storage based on computed entity primary keys.
     *
     * Generated from protobuf enum <code>FETCHING = 18;</code>
     */
    const FETCHING = 18;
    /**
     * Fetching referenced entities and entity groups from the storage based on referenced primary keys information.
     *
     * Generated from protobuf enum <code>FETCHING_REFERENCES = 19;</code>
     */
    const FETCHING_REFERENCES = 19;
    /**
     * Fetching parent entities from the storage based on parent primary keys information.
     *
     * Generated from protobuf enum <code>FETCHING_PARENTS = 20;</code>
     */
    const FETCHING_PARENTS = 20;

    private static $valueToName = [
        self::OVERALL => 'OVERALL',
        self::PLANNING => 'PLANNING',
        self::PLANNING_NESTED_QUERY => 'PLANNING_NESTED_QUERY',
        self::PLANNING_INDEX_USAGE => 'PLANNING_INDEX_USAGE',
        self::PLANNING_FILTER => 'PLANNING_FILTER',
        self::PLANNING_FILTER_NESTED_QUERY => 'PLANNING_FILTER_NESTED_QUERY',
        self::PLANNING_FILTER_ALTERNATIVE => 'PLANNING_FILTER_ALTERNATIVE',
        self::PLANNING_SORT => 'PLANNING_SORT',
        self::PLANNING_SORT_ALTERNATIVE => 'PLANNING_SORT_ALTERNATIVE',
        self::PLANNING_EXTRA_RESULT_FABRICATION => 'PLANNING_EXTRA_RESULT_FABRICATION',
        self::PLANNING_EXTRA_RESULT_FABRICATION_ALTERNATIVE => 'PLANNING_EXTRA_RESULT_FABRICATION_ALTERNATIVE',
        self::EXECUTION => 'EXECUTION',
        self::EXECUTION_PREFETCH => 'EXECUTION_PREFETCH',
        self::EXECUTION_FILTER => 'EXECUTION_FILTER',
        self::EXECUTION_FILTER_NESTED_QUERY => 'EXECUTION_FILTER_NESTED_QUERY',
        self::EXECUTION_SORT_AND_SLICE => 'EXECUTION_SORT_AND_SLICE',
        self::EXTRA_RESULTS_FABRICATION => 'EXTRA_RESULTS_FABRICATION',
        self::EXTRA_RESULT_ITEM_FABRICATION => 'EXTRA_RESULT_ITEM_FABRICATION',
        self::FETCHING => 'FETCHING',
        self::FETCHING_REFERENCES => 'FETCHING_REFERENCES',
        self::FETCHING_PARENTS => 'FETCHING_PARENTS',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

