<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GrpcEnums.proto

namespace Wtsvk\EvitaDbClient\Protocol;

use UnexpectedValueException;

/**
 * Represents constant or "special" value attribute can have (or has it implicitly, e.g. missing value is represented `null` that is not directly comparable).
 *
 * Protobuf type <code>io.evitadb.externalApi.grpc.generated.GrpcAttributeSpecialValue</code>
 */
class GrpcAttributeSpecialValue
{
    /**
     * Represents missing value.
     *
     * Generated from protobuf enum <code>NULL = 0;</code>
     */
    const NULL = 0;
    /**
     * Represents existing (not-null) value.
     *
     * Generated from protobuf enum <code>NOT_NULL = 1;</code>
     */
    const NOT_NULL = 1;

    private static $valueToName = [
        self::NULL => 'NULL',
        self::NOT_NULL => 'NOT_NULL',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

