<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GrpcAttributeMutations.proto

namespace Wtsvk\EvitaDbClient\Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Upsert attribute mutation will either update existing attribute or create new one.
 *
 * Generated from protobuf message <code>io.evitadb.externalApi.grpc.generated.GrpcUpsertAttributeMutation</code>
 */
class GrpcUpsertAttributeMutation extends \Google\Protobuf\Internal\Message
{
    /**
     * Unique name of the attribute. Case-sensitive. Distinguishes one associated data item from another within
     * single entity instance.
     *
     * Generated from protobuf field <code>string attributeName = 1;</code>
     */
    protected $attributeName = '';
    /**
     * Contains locale in case the attribute is locale specific.
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcLocale attributeLocale = 2;</code>
     */
    protected $attributeLocale = null;
    /**
     * New value of this attribute. Data type is expected to be the same as in schema or must be explicitly
     * set via `valueType`.
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcEvitaValue attributeValue = 3;</code>
     */
    protected $attributeValue = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $attributeName
     *           Unique name of the attribute. Case-sensitive. Distinguishes one associated data item from another within
     *           single entity instance.
     *     @type \Wtsvk\EvitaDbClient\Protocol\GrpcLocale $attributeLocale
     *           Contains locale in case the attribute is locale specific.
     *     @type \Wtsvk\EvitaDbClient\Protocol\GrpcEvitaValue $attributeValue
     *           New value of this attribute. Data type is expected to be the same as in schema or must be explicitly
     *           set via `valueType`.
     * }
     */
    public function __construct($data = NULL) {
        \Wtsvk\EvitaDbClient\Protocol\GPBMetadata\GrpcAttributeMutations::initOnce();
        parent::__construct($data);
    }

    /**
     * Unique name of the attribute. Case-sensitive. Distinguishes one associated data item from another within
     * single entity instance.
     *
     * Generated from protobuf field <code>string attributeName = 1;</code>
     * @return string
     */
    public function getAttributeName()
    {
        return $this->attributeName;
    }

    /**
     * Unique name of the attribute. Case-sensitive. Distinguishes one associated data item from another within
     * single entity instance.
     *
     * Generated from protobuf field <code>string attributeName = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setAttributeName($var)
    {
        GPBUtil::checkString($var, True);
        $this->attributeName = $var;

        return $this;
    }

    /**
     * Contains locale in case the attribute is locale specific.
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcLocale attributeLocale = 2;</code>
     * @return \Wtsvk\EvitaDbClient\Protocol\GrpcLocale|null
     */
    public function getAttributeLocale()
    {
        return $this->attributeLocale;
    }

    public function hasAttributeLocale()
    {
        return isset($this->attributeLocale);
    }

    public function clearAttributeLocale()
    {
        unset($this->attributeLocale);
    }

    /**
     * Contains locale in case the attribute is locale specific.
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcLocale attributeLocale = 2;</code>
     * @param \Wtsvk\EvitaDbClient\Protocol\GrpcLocale $var
     * @return $this
     */
    public function setAttributeLocale($var)
    {
        GPBUtil::checkMessage($var, \Wtsvk\EvitaDbClient\Protocol\GrpcLocale::class);
        $this->attributeLocale = $var;

        return $this;
    }

    /**
     * New value of this attribute. Data type is expected to be the same as in schema or must be explicitly
     * set via `valueType`.
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcEvitaValue attributeValue = 3;</code>
     * @return \Wtsvk\EvitaDbClient\Protocol\GrpcEvitaValue|null
     */
    public function getAttributeValue()
    {
        return $this->attributeValue;
    }

    public function hasAttributeValue()
    {
        return isset($this->attributeValue);
    }

    public function clearAttributeValue()
    {
        unset($this->attributeValue);
    }

    /**
     * New value of this attribute. Data type is expected to be the same as in schema or must be explicitly
     * set via `valueType`.
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcEvitaValue attributeValue = 3;</code>
     * @param \Wtsvk\EvitaDbClient\Protocol\GrpcEvitaValue $var
     * @return $this
     */
    public function setAttributeValue($var)
    {
        GPBUtil::checkMessage($var, \Wtsvk\EvitaDbClient\Protocol\GrpcEvitaValue::class);
        $this->attributeValue = $var;

        return $this;
    }

}

