<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GrpcAttributeSchemaMutations.proto

namespace Wtsvk\EvitaDbClient\Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Mutation is responsible for setting value to a `GlobalAttributeSchema.uniqueGlobally` in `EntitySchema`.
 * Mutation can be used for altering also the existing `GlobalAttributeSchema` alone.
 *
 * Generated from protobuf message <code>io.evitadb.externalApi.grpc.generated.GrpcSetAttributeSchemaGloballyUniqueMutation</code>
 */
class GrpcSetAttributeSchemaGloballyUniqueMutation extends \Google\Protobuf\Internal\Message
{
    /**
     * Name of the attribute the mutation is targeting.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     */
    protected $name = '';
    /**
     * When attribute is unique globally it is automatically filterable, and it is ensured there is exactly one single
     * entity having certain value of this attribute in entire catalog.
     * deprecated in favor of `uniqueGloballyInScopes`
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcGlobalAttributeUniquenessType uniqueGlobally = 2 [deprecated = true];</code>
     * @deprecated
     */
    protected $uniqueGlobally = 0;
    /**
     * When attribute is unique globally it is automatically filterable, and it is ensured there is exactly one single
     * entity having certain value of this attribute in entire catalog.
     *
     * Generated from protobuf field <code>repeated .io.evitadb.externalApi.grpc.generated.GrpcScopedGlobalAttributeUniquenessType uniqueGloballyInScopes = 15;</code>
     */
    private $uniqueGloballyInScopes;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *           Name of the attribute the mutation is targeting.
     *     @type int $uniqueGlobally
     *           When attribute is unique globally it is automatically filterable, and it is ensured there is exactly one single
     *           entity having certain value of this attribute in entire catalog.
     *           deprecated in favor of `uniqueGloballyInScopes`
     *     @type array<\Wtsvk\EvitaDbClient\Protocol\GrpcScopedGlobalAttributeUniquenessType>|\Google\Protobuf\Internal\RepeatedField $uniqueGloballyInScopes
     *           When attribute is unique globally it is automatically filterable, and it is ensured there is exactly one single
     *           entity having certain value of this attribute in entire catalog.
     * }
     */
    public function __construct($data = NULL) {
        \Wtsvk\EvitaDbClient\Protocol\GPBMetadata\GrpcAttributeSchemaMutations::initOnce();
        parent::__construct($data);
    }

    /**
     * Name of the attribute the mutation is targeting.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Name of the attribute the mutation is targeting.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * When attribute is unique globally it is automatically filterable, and it is ensured there is exactly one single
     * entity having certain value of this attribute in entire catalog.
     * deprecated in favor of `uniqueGloballyInScopes`
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcGlobalAttributeUniquenessType uniqueGlobally = 2 [deprecated = true];</code>
     * @return int
     * @deprecated
     */
    public function getUniqueGlobally()
    {
        @trigger_error('uniqueGlobally is deprecated.', E_USER_DEPRECATED);
        return $this->uniqueGlobally;
    }

    /**
     * When attribute is unique globally it is automatically filterable, and it is ensured there is exactly one single
     * entity having certain value of this attribute in entire catalog.
     * deprecated in favor of `uniqueGloballyInScopes`
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcGlobalAttributeUniquenessType uniqueGlobally = 2 [deprecated = true];</code>
     * @param int $var
     * @return $this
     * @deprecated
     */
    public function setUniqueGlobally($var)
    {
        @trigger_error('uniqueGlobally is deprecated.', E_USER_DEPRECATED);
        GPBUtil::checkEnum($var, \Wtsvk\EvitaDbClient\Protocol\GrpcGlobalAttributeUniquenessType::class);
        $this->uniqueGlobally = $var;

        return $this;
    }

    /**
     * When attribute is unique globally it is automatically filterable, and it is ensured there is exactly one single
     * entity having certain value of this attribute in entire catalog.
     *
     * Generated from protobuf field <code>repeated .io.evitadb.externalApi.grpc.generated.GrpcScopedGlobalAttributeUniquenessType uniqueGloballyInScopes = 15;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getUniqueGloballyInScopes()
    {
        return $this->uniqueGloballyInScopes;
    }

    /**
     * When attribute is unique globally it is automatically filterable, and it is ensured there is exactly one single
     * entity having certain value of this attribute in entire catalog.
     *
     * Generated from protobuf field <code>repeated .io.evitadb.externalApi.grpc.generated.GrpcScopedGlobalAttributeUniquenessType uniqueGloballyInScopes = 15;</code>
     * @param array<\Wtsvk\EvitaDbClient\Protocol\GrpcScopedGlobalAttributeUniquenessType>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setUniqueGloballyInScopes($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Wtsvk\EvitaDbClient\Protocol\GrpcScopedGlobalAttributeUniquenessType::class);
        $this->uniqueGloballyInScopes = $arr;

        return $this;
    }

}

