<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GrpcChangeCapture.proto

namespace Wtsvk\EvitaDbClient\Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Record describing the location and form of the CDC schema event in the evitaDB that should be captured.
 *
 * Generated from protobuf message <code>io.evitadb.externalApi.grpc.generated.GrpcChangeCaptureSchemaSite</code>
 */
class GrpcChangeCaptureSchemaSite extends \Google\Protobuf\Internal\Message
{
    /**
     * The name of intercepted entity
     *
     * Generated from protobuf field <code>.google.protobuf.StringValue entityType = 1;</code>
     */
    protected $entityType = null;
    /**
     * The intercepted type of operation
     *
     * Generated from protobuf field <code>repeated .io.evitadb.externalApi.grpc.generated.GrpcChangeCaptureOperation operation = 2;</code>
     */
    private $operation;
    /**
     * the name of the intercepted container type
     *
     * Generated from protobuf field <code>repeated .io.evitadb.externalApi.grpc.generated.GrpcChangeCaptureContainerType containerType = 3;</code>
     */
    private $containerType;
    /**
     * the name of the container (e.g. attribute name, associated data name, reference name)
     *
     * Generated from protobuf field <code>repeated string containerName = 4;</code>
     */
    private $containerName;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Google\Protobuf\StringValue $entityType
     *           The name of intercepted entity
     *     @type array<int>|\Google\Protobuf\Internal\RepeatedField $operation
     *           The intercepted type of operation
     *     @type array<int>|\Google\Protobuf\Internal\RepeatedField $containerType
     *           the name of the intercepted container type
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $containerName
     *           the name of the container (e.g. attribute name, associated data name, reference name)
     * }
     */
    public function __construct($data = NULL) {
        \Wtsvk\EvitaDbClient\Protocol\GPBMetadata\GrpcChangeCapture::initOnce();
        parent::__construct($data);
    }

    /**
     * The name of intercepted entity
     *
     * Generated from protobuf field <code>.google.protobuf.StringValue entityType = 1;</code>
     * @return \Google\Protobuf\StringValue|null
     */
    public function getEntityType()
    {
        return $this->entityType;
    }

    public function hasEntityType()
    {
        return isset($this->entityType);
    }

    public function clearEntityType()
    {
        unset($this->entityType);
    }

    /**
     * Returns the unboxed value from <code>getEntityType()</code>

     * The name of intercepted entity
     *
     * Generated from protobuf field <code>.google.protobuf.StringValue entityType = 1;</code>
     * @return string|null
     */
    public function getEntityTypeUnwrapped()
    {
        return $this->readWrapperValue("entityType");
    }

    /**
     * The name of intercepted entity
     *
     * Generated from protobuf field <code>.google.protobuf.StringValue entityType = 1;</code>
     * @param \Google\Protobuf\StringValue $var
     * @return $this
     */
    public function setEntityType($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\StringValue::class);
        $this->entityType = $var;

        return $this;
    }

    /**
     * Sets the field by wrapping a primitive type in a Google\Protobuf\StringValue object.

     * The name of intercepted entity
     *
     * Generated from protobuf field <code>.google.protobuf.StringValue entityType = 1;</code>
     * @param string|null $var
     * @return $this
     */
    public function setEntityTypeUnwrapped($var)
    {
        $this->writeWrapperValue("entityType", $var);
        return $this;}

    /**
     * The intercepted type of operation
     *
     * Generated from protobuf field <code>repeated .io.evitadb.externalApi.grpc.generated.GrpcChangeCaptureOperation operation = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getOperation()
    {
        return $this->operation;
    }

    /**
     * The intercepted type of operation
     *
     * Generated from protobuf field <code>repeated .io.evitadb.externalApi.grpc.generated.GrpcChangeCaptureOperation operation = 2;</code>
     * @param array<int>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setOperation($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::ENUM, \Wtsvk\EvitaDbClient\Protocol\GrpcChangeCaptureOperation::class);
        $this->operation = $arr;

        return $this;
    }

    /**
     * the name of the intercepted container type
     *
     * Generated from protobuf field <code>repeated .io.evitadb.externalApi.grpc.generated.GrpcChangeCaptureContainerType containerType = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getContainerType()
    {
        return $this->containerType;
    }

    /**
     * the name of the intercepted container type
     *
     * Generated from protobuf field <code>repeated .io.evitadb.externalApi.grpc.generated.GrpcChangeCaptureContainerType containerType = 3;</code>
     * @param array<int>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setContainerType($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::ENUM, \Wtsvk\EvitaDbClient\Protocol\GrpcChangeCaptureContainerType::class);
        $this->containerType = $arr;

        return $this;
    }

    /**
     * the name of the container (e.g. attribute name, associated data name, reference name)
     *
     * Generated from protobuf field <code>repeated string containerName = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getContainerName()
    {
        return $this->containerName;
    }

    /**
     * the name of the container (e.g. attribute name, associated data name, reference name)
     *
     * Generated from protobuf field <code>repeated string containerName = 4;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setContainerName($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->containerName = $arr;

        return $this;
    }

}

