<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GrpcEntitySchemaMutations.proto

namespace Wtsvk\EvitaDbClient\Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Mutation is responsible for setting a `EntitySchema.withHierarchy` in `EntitySchema`.
 *
 * Generated from protobuf message <code>io.evitadb.externalApi.grpc.generated.GrpcSetEntitySchemaWithHierarchyMutation</code>
 */
class GrpcSetEntitySchemaWithHierarchyMutation extends \Google\Protobuf\Internal\Message
{
    /**
     * Whether entities of this type are organized in a tree like structure (hierarchy) where certain entities
     * are subordinate of other entities.
     * Entities may be organized in hierarchical fashion. That means that entity may refer to single parent entity and may be
     * referred by multiple child entities. Hierarchy is always composed of entities of same type.
     * Each entity must be part of at most single hierarchy (tree).
     * Hierarchy can limit returned entities by using filtering constraints `hierarchy_{reference name}_within`. It's also used for
     * computation of extra data - such as `hierarchyParents`.
     *
     * Generated from protobuf field <code>bool withHierarchy = 1;</code>
     */
    protected $withHierarchy = false;
    /**
     * Contains set of all scopes the entity is indexed in and can be used for filtering entities and computation of
     * extra data. If the hierarchy information is not indexed, it is still available on the entity itself (i.e. entity
     * can define its parent entity), but it is not possible to work with the hierarchy information in any other way
     * (calculating parent chain, children, siblings, etc.).
     *
     * Generated from protobuf field <code>repeated .io.evitadb.externalApi.grpc.generated.GrpcEntityScope indexedInScopes = 2;</code>
     */
    private $indexedInScopes;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $withHierarchy
     *           Whether entities of this type are organized in a tree like structure (hierarchy) where certain entities
     *           are subordinate of other entities.
     *           Entities may be organized in hierarchical fashion. That means that entity may refer to single parent entity and may be
     *           referred by multiple child entities. Hierarchy is always composed of entities of same type.
     *           Each entity must be part of at most single hierarchy (tree).
     *           Hierarchy can limit returned entities by using filtering constraints `hierarchy_{reference name}_within`. It's also used for
     *           computation of extra data - such as `hierarchyParents`.
     *     @type array<int>|\Google\Protobuf\Internal\RepeatedField $indexedInScopes
     *           Contains set of all scopes the entity is indexed in and can be used for filtering entities and computation of
     *           extra data. If the hierarchy information is not indexed, it is still available on the entity itself (i.e. entity
     *           can define its parent entity), but it is not possible to work with the hierarchy information in any other way
     *           (calculating parent chain, children, siblings, etc.).
     * }
     */
    public function __construct($data = NULL) {
        \Wtsvk\EvitaDbClient\Protocol\GPBMetadata\GrpcEntitySchemaMutations::initOnce();
        parent::__construct($data);
    }

    /**
     * Whether entities of this type are organized in a tree like structure (hierarchy) where certain entities
     * are subordinate of other entities.
     * Entities may be organized in hierarchical fashion. That means that entity may refer to single parent entity and may be
     * referred by multiple child entities. Hierarchy is always composed of entities of same type.
     * Each entity must be part of at most single hierarchy (tree).
     * Hierarchy can limit returned entities by using filtering constraints `hierarchy_{reference name}_within`. It's also used for
     * computation of extra data - such as `hierarchyParents`.
     *
     * Generated from protobuf field <code>bool withHierarchy = 1;</code>
     * @return bool
     */
    public function getWithHierarchy()
    {
        return $this->withHierarchy;
    }

    /**
     * Whether entities of this type are organized in a tree like structure (hierarchy) where certain entities
     * are subordinate of other entities.
     * Entities may be organized in hierarchical fashion. That means that entity may refer to single parent entity and may be
     * referred by multiple child entities. Hierarchy is always composed of entities of same type.
     * Each entity must be part of at most single hierarchy (tree).
     * Hierarchy can limit returned entities by using filtering constraints `hierarchy_{reference name}_within`. It's also used for
     * computation of extra data - such as `hierarchyParents`.
     *
     * Generated from protobuf field <code>bool withHierarchy = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setWithHierarchy($var)
    {
        GPBUtil::checkBool($var);
        $this->withHierarchy = $var;

        return $this;
    }

    /**
     * Contains set of all scopes the entity is indexed in and can be used for filtering entities and computation of
     * extra data. If the hierarchy information is not indexed, it is still available on the entity itself (i.e. entity
     * can define its parent entity), but it is not possible to work with the hierarchy information in any other way
     * (calculating parent chain, children, siblings, etc.).
     *
     * Generated from protobuf field <code>repeated .io.evitadb.externalApi.grpc.generated.GrpcEntityScope indexedInScopes = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getIndexedInScopes()
    {
        return $this->indexedInScopes;
    }

    /**
     * Contains set of all scopes the entity is indexed in and can be used for filtering entities and computation of
     * extra data. If the hierarchy information is not indexed, it is still available on the entity itself (i.e. entity
     * can define its parent entity), but it is not possible to work with the hierarchy information in any other way
     * (calculating parent chain, children, siblings, etc.).
     *
     * Generated from protobuf field <code>repeated .io.evitadb.externalApi.grpc.generated.GrpcEntityScope indexedInScopes = 2;</code>
     * @param array<int>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setIndexedInScopes($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::ENUM, \Wtsvk\EvitaDbClient\Protocol\GrpcEntityScope::class);
        $this->indexedInScopes = $arr;

        return $this;
    }

}

