<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GrpcEntitySchemaMutations.proto

namespace Wtsvk\EvitaDbClient\Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Mutation is responsible for adding one or more modes to a `EntitySchema.evolutionMode` in `EntitySchema`.
 *
 * Generated from protobuf message <code>io.evitadb.externalApi.grpc.generated.GrpcAllowEvolutionModeInEntitySchemaMutation</code>
 */
class GrpcAllowEvolutionModeInEntitySchemaMutation extends \Google\Protobuf\Internal\Message
{
    /**
     * Set of allowed evolution modes. These allow to specify how strict is evitaDB when unknown information is
     * presented to her for the first time. When no evolution mode is set, each violation of the `EntitySchema` is
     * reported by an error. This behaviour can be changed by this evolution mode, however.
     *
     * Generated from protobuf field <code>repeated .io.evitadb.externalApi.grpc.generated.GrpcEvolutionMode evolutionModes = 1;</code>
     */
    private $evolutionModes;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<int>|\Google\Protobuf\Internal\RepeatedField $evolutionModes
     *           Set of allowed evolution modes. These allow to specify how strict is evitaDB when unknown information is
     *           presented to her for the first time. When no evolution mode is set, each violation of the `EntitySchema` is
     *           reported by an error. This behaviour can be changed by this evolution mode, however.
     * }
     */
    public function __construct($data = NULL) {
        \Wtsvk\EvitaDbClient\Protocol\GPBMetadata\GrpcEntitySchemaMutations::initOnce();
        parent::__construct($data);
    }

    /**
     * Set of allowed evolution modes. These allow to specify how strict is evitaDB when unknown information is
     * presented to her for the first time. When no evolution mode is set, each violation of the `EntitySchema` is
     * reported by an error. This behaviour can be changed by this evolution mode, however.
     *
     * Generated from protobuf field <code>repeated .io.evitadb.externalApi.grpc.generated.GrpcEvolutionMode evolutionModes = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getEvolutionModes()
    {
        return $this->evolutionModes;
    }

    /**
     * Set of allowed evolution modes. These allow to specify how strict is evitaDB when unknown information is
     * presented to her for the first time. When no evolution mode is set, each violation of the `EntitySchema` is
     * reported by an error. This behaviour can be changed by this evolution mode, however.
     *
     * Generated from protobuf field <code>repeated .io.evitadb.externalApi.grpc.generated.GrpcEvolutionMode evolutionModes = 1;</code>
     * @param array<int>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setEvolutionModes($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::ENUM, \Wtsvk\EvitaDbClient\Protocol\GrpcEvolutionMode::class);
        $this->evolutionModes = $arr;

        return $this;
    }

}

