<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GrpcEnums.proto

namespace Wtsvk\EvitaDbClient\Protocol;

use UnexpectedValueException;

/**
 * Enum defines all supported relation type that can be used in the facet summary impact calculation.
 *
 * Protobuf type <code>io.evitadb.externalApi.grpc.generated.GrpcFacetRelationType</code>
 */
class GrpcFacetRelationType
{
    /**
     * Logical OR relation.
     *
     * Generated from protobuf enum <code>DISJUNCTION = 0;</code>
     */
    const DISJUNCTION = 0;
    /**
     * Logical AND relation.
     *
     * Generated from protobuf enum <code>CONJUNCTION = 1;</code>
     */
    const CONJUNCTION = 1;
    /**
     * Logical AND NOT relation.
     *
     * Generated from protobuf enum <code>NEGATION = 2;</code>
     */
    const NEGATION = 2;
    /**
     * Exclusive relations to other facets on the same level, when selected no other facet on that level can be selected.
     *
     * Generated from protobuf enum <code>EXCLUSIVITY = 3;</code>
     */
    const EXCLUSIVITY = 3;

    private static $valueToName = [
        self::DISJUNCTION => 'DISJUNCTION',
        self::CONJUNCTION => 'CONJUNCTION',
        self::NEGATION => 'NEGATION',
        self::EXCLUSIVITY => 'EXCLUSIVITY',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

