<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GrpcEvitaSessionAPI.proto

namespace Wtsvk\EvitaDbClient\Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Response to DeleteEntities request that deletes all entities that match the sent query..
 *
 * Generated from protobuf message <code>io.evitadb.externalApi.grpc.generated.GrpcDeleteEntitiesResponse</code>
 */
class GrpcDeleteEntitiesResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Count of deleted entities.
     *
     * Generated from protobuf field <code>int32 deletedEntities = 1;</code>
     */
    protected $deletedEntities = 0;
    /**
     * The deleted entity bodies.
     *
     * Generated from protobuf field <code>repeated .io.evitadb.externalApi.grpc.generated.GrpcSealedEntity deletedEntityBodies = 2;</code>
     */
    private $deletedEntityBodies;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $deletedEntities
     *           Count of deleted entities.
     *     @type array<\Wtsvk\EvitaDbClient\Protocol\GrpcSealedEntity>|\Google\Protobuf\Internal\RepeatedField $deletedEntityBodies
     *           The deleted entity bodies.
     * }
     */
    public function __construct($data = NULL) {
        \Wtsvk\EvitaDbClient\Protocol\GPBMetadata\GrpcEvitaSessionAPI::initOnce();
        parent::__construct($data);
    }

    /**
     * Count of deleted entities.
     *
     * Generated from protobuf field <code>int32 deletedEntities = 1;</code>
     * @return int
     */
    public function getDeletedEntities()
    {
        return $this->deletedEntities;
    }

    /**
     * Count of deleted entities.
     *
     * Generated from protobuf field <code>int32 deletedEntities = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setDeletedEntities($var)
    {
        GPBUtil::checkInt32($var);
        $this->deletedEntities = $var;

        return $this;
    }

    /**
     * The deleted entity bodies.
     *
     * Generated from protobuf field <code>repeated .io.evitadb.externalApi.grpc.generated.GrpcSealedEntity deletedEntityBodies = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getDeletedEntityBodies()
    {
        return $this->deletedEntityBodies;
    }

    /**
     * The deleted entity bodies.
     *
     * Generated from protobuf field <code>repeated .io.evitadb.externalApi.grpc.generated.GrpcSealedEntity deletedEntityBodies = 2;</code>
     * @param array<\Wtsvk\EvitaDbClient\Protocol\GrpcSealedEntity>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setDeletedEntityBodies($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Wtsvk\EvitaDbClient\Protocol\GrpcSealedEntity::class);
        $this->deletedEntityBodies = $arr;

        return $this;
    }

}

