<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GrpcEvitaSessionAPI.proto

namespace Wtsvk\EvitaDbClient\Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Request for acquiring the list of all entity types.
 *
 * Generated from protobuf message <code>io.evitadb.externalApi.grpc.generated.GrpcEntityTypesResponse</code>
 */
class GrpcEntityTypesResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * The list of all entity types.
     *
     * Generated from protobuf field <code>repeated string entityTypes = 1;</code>
     */
    private $entityTypes;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $entityTypes
     *           The list of all entity types.
     * }
     */
    public function __construct($data = NULL) {
        \Wtsvk\EvitaDbClient\Protocol\GPBMetadata\GrpcEvitaSessionAPI::initOnce();
        parent::__construct($data);
    }

    /**
     * The list of all entity types.
     *
     * Generated from protobuf field <code>repeated string entityTypes = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getEntityTypes()
    {
        return $this->entityTypes;
    }

    /**
     * The list of all entity types.
     *
     * Generated from protobuf field <code>repeated string entityTypes = 1;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setEntityTypes($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->entityTypes = $arr;

        return $this;
    }

}

