<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GrpcEnums.proto

namespace Wtsvk\EvitaDbClient\Protocol;

use UnexpectedValueException;

/**
 * Determines which prices will be fetched along with entity.
 *
 * Protobuf type <code>io.evitadb.externalApi.grpc.generated.GrpcPriceContentMode</code>
 */
class GrpcPriceContentMode
{
    /**
     * No prices will be fetched.
     *
     * Generated from protobuf enum <code>FETCH_NONE = 0;</code>
     */
    const FETCH_NONE = 0;
    /**
     * Only prices respecting filter constraints in query will be fetched.
     *
     * Generated from protobuf enum <code>RESPECTING_FILTER = 1;</code>
     */
    const RESPECTING_FILTER = 1;
    /**
     * All prices will be fetched.
     *
     * Generated from protobuf enum <code>ALL = 2;</code>
     */
    const ALL = 2;

    private static $valueToName = [
        self::FETCH_NONE => 'FETCH_NONE',
        self::RESPECTING_FILTER => 'RESPECTING_FILTER',
        self::ALL => 'ALL',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

