<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GrpcQueryParam.proto

namespace Wtsvk\EvitaDbClient\Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Structure that supports storing all possible parameters that could be used within query.
 *
 * Generated from protobuf message <code>io.evitadb.externalApi.grpc.generated.GrpcQueryParam</code>
 */
class GrpcQueryParam extends \Google\Protobuf\Internal\Message
{
    protected $queryParam;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $stringValue
     *           The string value.
     *     @type int $integerValue
     *           The integer value.
     *     @type int|string $longValue
     *           The long value.
     *     @type bool $booleanValue
     *           The boolean value.
     *     @type \Wtsvk\EvitaDbClient\Protocol\GrpcBigDecimal $bigDecimalValue
     *           The big decimal value.
     *     @type \Wtsvk\EvitaDbClient\Protocol\GrpcDateTimeRange $dateTimeRangeValue
     *           The date time range value.
     *     @type \Wtsvk\EvitaDbClient\Protocol\GrpcIntegerNumberRange $integerNumberRangeValue
     *           The integer number range value.
     *     @type \Wtsvk\EvitaDbClient\Protocol\GrpcLongNumberRange $longNumberRangeValue
     *           The long number range value.
     *     @type \Wtsvk\EvitaDbClient\Protocol\GrpcBigDecimalNumberRange $bigDecimalNumberRangeValue
     *           The big decimal number range value.
     *     @type \Wtsvk\EvitaDbClient\Protocol\GrpcOffsetDateTime $offsetDateTimeValue
     *           The offset date time value.
     *     @type \Wtsvk\EvitaDbClient\Protocol\GrpcLocale $localeValue
     *           The locale value.
     *     @type \Wtsvk\EvitaDbClient\Protocol\GrpcCurrency $currencyValue
     *           The currency value.
     *     @type int $facetStatisticsDepthValue
     *           The facet statistics depth enum value.
     *     @type int $queryPriceModelValue
     *           The query price mode enum value.
     *     @type int $priceContentModeValue
     *           The price content mode enum value.
     *     @type int $attributeSpecialValue
     *           The attribute special value enum value.
     *     @type int $orderDirectionValue
     *           The order direction enum value.
     *     @type int $emptyHierarchicalEntityBehaviour
     *           The empty hierarchical entity behaviour enum value.
     *     @type int $statisticsBase
     *           The statistics base enum value.
     *     @type int $statisticsType
     *           The statistics type enum value.
     *     @type int $histogramBehavior
     *           The histogram behavior enum value.
     *     @type int $managedReferencesBehaviour
     *           The managed references behaviour
     *     @type string $expressionValue
     *           The expression
     *     @type int $scope
     *           The scope enum value.
     *     @type int $facetRelationType
     *           The facetRelationType enum value.
     *     @type int $facetGroupRelationLevel
     *           The facetGroupRelationLevel enum value.
     *     @type int $traversalMode
     *           The facet traversal mode enum value.
     *     @type \Wtsvk\EvitaDbClient\Protocol\GrpcStringArray $stringArrayValue
     *           The string array value.
     *     @type \Wtsvk\EvitaDbClient\Protocol\GrpcIntegerArray $integerArrayValue
     *           The integer array value.
     *     @type \Wtsvk\EvitaDbClient\Protocol\GrpcLongArray $longArrayValue
     *           The long array value.
     *     @type \Wtsvk\EvitaDbClient\Protocol\GrpcBooleanArray $booleanArrayValue
     *           The boolean array value.
     *     @type \Wtsvk\EvitaDbClient\Protocol\GrpcBigDecimalArray $bigDecimalArrayValue
     *           The big decimal array value.
     *     @type \Wtsvk\EvitaDbClient\Protocol\GrpcDateTimeRangeArray $dateTimeRangeArrayValue
     *           The date time range array value.
     *     @type \Wtsvk\EvitaDbClient\Protocol\GrpcIntegerNumberRangeArray $integerNumberRangeArrayValue
     *           The integer number range array value.
     *     @type \Wtsvk\EvitaDbClient\Protocol\GrpcLongNumberRangeArray $longNumberRangeArrayValue
     *           The long number range array value.
     *     @type \Wtsvk\EvitaDbClient\Protocol\GrpcBigDecimalNumberRangeArray $bigDecimalNumberRangeArrayValue
     *           The big decimal number range array value.
     *     @type \Wtsvk\EvitaDbClient\Protocol\GrpcOffsetDateTimeArray $offsetDateTimeArrayValue
     *           The offset date time array value.
     *     @type \Wtsvk\EvitaDbClient\Protocol\GrpcLocaleArray $localeArrayValue
     *           The locale array value.
     *     @type \Wtsvk\EvitaDbClient\Protocol\GrpcCurrencyArray $currencyArrayValue
     *           The currency array value.
     *     @type \Wtsvk\EvitaDbClient\Protocol\GrpcFacetStatisticsDepthArray $facetStatisticsDepthArrayValue
     *           The facet statistics depth array value.
     *     @type \Wtsvk\EvitaDbClient\Protocol\GrpcQueryPriceModeArray $queryPriceModelArrayValue
     *           The query price mode array value.
     *     @type \Wtsvk\EvitaDbClient\Protocol\GrpcPriceContentModeArray $priceContentModeArrayValue
     *           The price content mode array value.
     *     @type \Wtsvk\EvitaDbClient\Protocol\GrpcAttributeSpecialValueArray $attributeSpecialArrayValue
     *           The attribute special value array value.
     *     @type \Wtsvk\EvitaDbClient\Protocol\GrpcOrderDirectionArray $orderDirectionArrayValue
     *           The order direction array value.
     *     @type \Wtsvk\EvitaDbClient\Protocol\GrpcEmptyHierarchicalEntityBehaviourArray $emptyHierarchicalEntityBehaviourArrayValue
     *           The empty hierarchical entity behaviour array value.
     *     @type \Wtsvk\EvitaDbClient\Protocol\GrpcStatisticsBaseArray $statisticsBaseArrayValue
     *           The statistics base array value.
     *     @type \Wtsvk\EvitaDbClient\Protocol\GrpcStatisticsTypeArray $statisticsTypeArrayValue
     *           The statistics type array value.
     *     @type \Wtsvk\EvitaDbClient\Protocol\GrpcHistogramBehaviorTypeArray $histogramBehaviorTypeArrayValue
     *           The histogram behavior enum value.
     *     @type \Wtsvk\EvitaDbClient\Protocol\GrpcEntityScopeArray $scopeArrayValue
     *           The scope enum value.
     * }
     */
    public function __construct($data = NULL) {
        \Wtsvk\EvitaDbClient\Protocol\GPBMetadata\GrpcQueryParam::initOnce();
        parent::__construct($data);
    }

    /**
     * The string value.
     *
     * Generated from protobuf field <code>string stringValue = 1;</code>
     * @return string
     */
    public function getStringValue()
    {
        return $this->readOneof(1);
    }

    public function hasStringValue()
    {
        return $this->hasOneof(1);
    }

    /**
     * The string value.
     *
     * Generated from protobuf field <code>string stringValue = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setStringValue($var)
    {
        GPBUtil::checkString($var, True);
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * The integer value.
     *
     * Generated from protobuf field <code>int32 integerValue = 2;</code>
     * @return int
     */
    public function getIntegerValue()
    {
        return $this->readOneof(2);
    }

    public function hasIntegerValue()
    {
        return $this->hasOneof(2);
    }

    /**
     * The integer value.
     *
     * Generated from protobuf field <code>int32 integerValue = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setIntegerValue($var)
    {
        GPBUtil::checkInt32($var);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * The long value.
     *
     * Generated from protobuf field <code>int64 longValue = 3;</code>
     * @return int|string
     */
    public function getLongValue()
    {
        return $this->readOneof(3);
    }

    public function hasLongValue()
    {
        return $this->hasOneof(3);
    }

    /**
     * The long value.
     *
     * Generated from protobuf field <code>int64 longValue = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setLongValue($var)
    {
        GPBUtil::checkInt64($var);
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * The boolean value.
     *
     * Generated from protobuf field <code>bool booleanValue = 4;</code>
     * @return bool
     */
    public function getBooleanValue()
    {
        return $this->readOneof(4);
    }

    public function hasBooleanValue()
    {
        return $this->hasOneof(4);
    }

    /**
     * The boolean value.
     *
     * Generated from protobuf field <code>bool booleanValue = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setBooleanValue($var)
    {
        GPBUtil::checkBool($var);
        $this->writeOneof(4, $var);

        return $this;
    }

    /**
     * The big decimal value.
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcBigDecimal bigDecimalValue = 5;</code>
     * @return \Wtsvk\EvitaDbClient\Protocol\GrpcBigDecimal|null
     */
    public function getBigDecimalValue()
    {
        return $this->readOneof(5);
    }

    public function hasBigDecimalValue()
    {
        return $this->hasOneof(5);
    }

    /**
     * The big decimal value.
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcBigDecimal bigDecimalValue = 5;</code>
     * @param \Wtsvk\EvitaDbClient\Protocol\GrpcBigDecimal $var
     * @return $this
     */
    public function setBigDecimalValue($var)
    {
        GPBUtil::checkMessage($var, \Wtsvk\EvitaDbClient\Protocol\GrpcBigDecimal::class);
        $this->writeOneof(5, $var);

        return $this;
    }

    /**
     * The date time range value.
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcDateTimeRange dateTimeRangeValue = 6;</code>
     * @return \Wtsvk\EvitaDbClient\Protocol\GrpcDateTimeRange|null
     */
    public function getDateTimeRangeValue()
    {
        return $this->readOneof(6);
    }

    public function hasDateTimeRangeValue()
    {
        return $this->hasOneof(6);
    }

    /**
     * The date time range value.
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcDateTimeRange dateTimeRangeValue = 6;</code>
     * @param \Wtsvk\EvitaDbClient\Protocol\GrpcDateTimeRange $var
     * @return $this
     */
    public function setDateTimeRangeValue($var)
    {
        GPBUtil::checkMessage($var, \Wtsvk\EvitaDbClient\Protocol\GrpcDateTimeRange::class);
        $this->writeOneof(6, $var);

        return $this;
    }

    /**
     * The integer number range value.
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcIntegerNumberRange integerNumberRangeValue = 7;</code>
     * @return \Wtsvk\EvitaDbClient\Protocol\GrpcIntegerNumberRange|null
     */
    public function getIntegerNumberRangeValue()
    {
        return $this->readOneof(7);
    }

    public function hasIntegerNumberRangeValue()
    {
        return $this->hasOneof(7);
    }

    /**
     * The integer number range value.
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcIntegerNumberRange integerNumberRangeValue = 7;</code>
     * @param \Wtsvk\EvitaDbClient\Protocol\GrpcIntegerNumberRange $var
     * @return $this
     */
    public function setIntegerNumberRangeValue($var)
    {
        GPBUtil::checkMessage($var, \Wtsvk\EvitaDbClient\Protocol\GrpcIntegerNumberRange::class);
        $this->writeOneof(7, $var);

        return $this;
    }

    /**
     * The long number range value.
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcLongNumberRange longNumberRangeValue = 8;</code>
     * @return \Wtsvk\EvitaDbClient\Protocol\GrpcLongNumberRange|null
     */
    public function getLongNumberRangeValue()
    {
        return $this->readOneof(8);
    }

    public function hasLongNumberRangeValue()
    {
        return $this->hasOneof(8);
    }

    /**
     * The long number range value.
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcLongNumberRange longNumberRangeValue = 8;</code>
     * @param \Wtsvk\EvitaDbClient\Protocol\GrpcLongNumberRange $var
     * @return $this
     */
    public function setLongNumberRangeValue($var)
    {
        GPBUtil::checkMessage($var, \Wtsvk\EvitaDbClient\Protocol\GrpcLongNumberRange::class);
        $this->writeOneof(8, $var);

        return $this;
    }

    /**
     * The big decimal number range value.
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcBigDecimalNumberRange bigDecimalNumberRangeValue = 9;</code>
     * @return \Wtsvk\EvitaDbClient\Protocol\GrpcBigDecimalNumberRange|null
     */
    public function getBigDecimalNumberRangeValue()
    {
        return $this->readOneof(9);
    }

    public function hasBigDecimalNumberRangeValue()
    {
        return $this->hasOneof(9);
    }

    /**
     * The big decimal number range value.
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcBigDecimalNumberRange bigDecimalNumberRangeValue = 9;</code>
     * @param \Wtsvk\EvitaDbClient\Protocol\GrpcBigDecimalNumberRange $var
     * @return $this
     */
    public function setBigDecimalNumberRangeValue($var)
    {
        GPBUtil::checkMessage($var, \Wtsvk\EvitaDbClient\Protocol\GrpcBigDecimalNumberRange::class);
        $this->writeOneof(9, $var);

        return $this;
    }

    /**
     * The offset date time value.
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcOffsetDateTime offsetDateTimeValue = 10;</code>
     * @return \Wtsvk\EvitaDbClient\Protocol\GrpcOffsetDateTime|null
     */
    public function getOffsetDateTimeValue()
    {
        return $this->readOneof(10);
    }

    public function hasOffsetDateTimeValue()
    {
        return $this->hasOneof(10);
    }

    /**
     * The offset date time value.
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcOffsetDateTime offsetDateTimeValue = 10;</code>
     * @param \Wtsvk\EvitaDbClient\Protocol\GrpcOffsetDateTime $var
     * @return $this
     */
    public function setOffsetDateTimeValue($var)
    {
        GPBUtil::checkMessage($var, \Wtsvk\EvitaDbClient\Protocol\GrpcOffsetDateTime::class);
        $this->writeOneof(10, $var);

        return $this;
    }

    /**
     * The locale value.
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcLocale localeValue = 11;</code>
     * @return \Wtsvk\EvitaDbClient\Protocol\GrpcLocale|null
     */
    public function getLocaleValue()
    {
        return $this->readOneof(11);
    }

    public function hasLocaleValue()
    {
        return $this->hasOneof(11);
    }

    /**
     * The locale value.
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcLocale localeValue = 11;</code>
     * @param \Wtsvk\EvitaDbClient\Protocol\GrpcLocale $var
     * @return $this
     */
    public function setLocaleValue($var)
    {
        GPBUtil::checkMessage($var, \Wtsvk\EvitaDbClient\Protocol\GrpcLocale::class);
        $this->writeOneof(11, $var);

        return $this;
    }

    /**
     * The currency value.
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcCurrency currencyValue = 12;</code>
     * @return \Wtsvk\EvitaDbClient\Protocol\GrpcCurrency|null
     */
    public function getCurrencyValue()
    {
        return $this->readOneof(12);
    }

    public function hasCurrencyValue()
    {
        return $this->hasOneof(12);
    }

    /**
     * The currency value.
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcCurrency currencyValue = 12;</code>
     * @param \Wtsvk\EvitaDbClient\Protocol\GrpcCurrency $var
     * @return $this
     */
    public function setCurrencyValue($var)
    {
        GPBUtil::checkMessage($var, \Wtsvk\EvitaDbClient\Protocol\GrpcCurrency::class);
        $this->writeOneof(12, $var);

        return $this;
    }

    /**
     * The facet statistics depth enum value.
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcFacetStatisticsDepth facetStatisticsDepthValue = 13;</code>
     * @return int
     */
    public function getFacetStatisticsDepthValue()
    {
        return $this->readOneof(13);
    }

    public function hasFacetStatisticsDepthValue()
    {
        return $this->hasOneof(13);
    }

    /**
     * The facet statistics depth enum value.
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcFacetStatisticsDepth facetStatisticsDepthValue = 13;</code>
     * @param int $var
     * @return $this
     */
    public function setFacetStatisticsDepthValue($var)
    {
        GPBUtil::checkEnum($var, \Wtsvk\EvitaDbClient\Protocol\GrpcFacetStatisticsDepth::class);
        $this->writeOneof(13, $var);

        return $this;
    }

    /**
     * The query price mode enum value.
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcQueryPriceMode queryPriceModelValue = 14;</code>
     * @return int
     */
    public function getQueryPriceModelValue()
    {
        return $this->readOneof(14);
    }

    public function hasQueryPriceModelValue()
    {
        return $this->hasOneof(14);
    }

    /**
     * The query price mode enum value.
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcQueryPriceMode queryPriceModelValue = 14;</code>
     * @param int $var
     * @return $this
     */
    public function setQueryPriceModelValue($var)
    {
        GPBUtil::checkEnum($var, \Wtsvk\EvitaDbClient\Protocol\GrpcQueryPriceMode::class);
        $this->writeOneof(14, $var);

        return $this;
    }

    /**
     * The price content mode enum value.
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcPriceContentMode priceContentModeValue = 15;</code>
     * @return int
     */
    public function getPriceContentModeValue()
    {
        return $this->readOneof(15);
    }

    public function hasPriceContentModeValue()
    {
        return $this->hasOneof(15);
    }

    /**
     * The price content mode enum value.
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcPriceContentMode priceContentModeValue = 15;</code>
     * @param int $var
     * @return $this
     */
    public function setPriceContentModeValue($var)
    {
        GPBUtil::checkEnum($var, \Wtsvk\EvitaDbClient\Protocol\GrpcPriceContentMode::class);
        $this->writeOneof(15, $var);

        return $this;
    }

    /**
     * The attribute special value enum value.
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcAttributeSpecialValue attributeSpecialValue = 16;</code>
     * @return int
     */
    public function getAttributeSpecialValue()
    {
        return $this->readOneof(16);
    }

    public function hasAttributeSpecialValue()
    {
        return $this->hasOneof(16);
    }

    /**
     * The attribute special value enum value.
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcAttributeSpecialValue attributeSpecialValue = 16;</code>
     * @param int $var
     * @return $this
     */
    public function setAttributeSpecialValue($var)
    {
        GPBUtil::checkEnum($var, \Wtsvk\EvitaDbClient\Protocol\GrpcAttributeSpecialValue::class);
        $this->writeOneof(16, $var);

        return $this;
    }

    /**
     * The order direction enum value.
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcOrderDirection orderDirectionValue = 17;</code>
     * @return int
     */
    public function getOrderDirectionValue()
    {
        return $this->readOneof(17);
    }

    public function hasOrderDirectionValue()
    {
        return $this->hasOneof(17);
    }

    /**
     * The order direction enum value.
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcOrderDirection orderDirectionValue = 17;</code>
     * @param int $var
     * @return $this
     */
    public function setOrderDirectionValue($var)
    {
        GPBUtil::checkEnum($var, \Wtsvk\EvitaDbClient\Protocol\GrpcOrderDirection::class);
        $this->writeOneof(17, $var);

        return $this;
    }

    /**
     * The empty hierarchical entity behaviour enum value.
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcEmptyHierarchicalEntityBehaviour emptyHierarchicalEntityBehaviour = 18;</code>
     * @return int
     */
    public function getEmptyHierarchicalEntityBehaviour()
    {
        return $this->readOneof(18);
    }

    public function hasEmptyHierarchicalEntityBehaviour()
    {
        return $this->hasOneof(18);
    }

    /**
     * The empty hierarchical entity behaviour enum value.
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcEmptyHierarchicalEntityBehaviour emptyHierarchicalEntityBehaviour = 18;</code>
     * @param int $var
     * @return $this
     */
    public function setEmptyHierarchicalEntityBehaviour($var)
    {
        GPBUtil::checkEnum($var, \Wtsvk\EvitaDbClient\Protocol\GrpcEmptyHierarchicalEntityBehaviour::class);
        $this->writeOneof(18, $var);

        return $this;
    }

    /**
     * The statistics base enum value.
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcStatisticsBase statisticsBase = 19;</code>
     * @return int
     */
    public function getStatisticsBase()
    {
        return $this->readOneof(19);
    }

    public function hasStatisticsBase()
    {
        return $this->hasOneof(19);
    }

    /**
     * The statistics base enum value.
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcStatisticsBase statisticsBase = 19;</code>
     * @param int $var
     * @return $this
     */
    public function setStatisticsBase($var)
    {
        GPBUtil::checkEnum($var, \Wtsvk\EvitaDbClient\Protocol\GrpcStatisticsBase::class);
        $this->writeOneof(19, $var);

        return $this;
    }

    /**
     * The statistics type enum value.
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcStatisticsType statisticsType = 20;</code>
     * @return int
     */
    public function getStatisticsType()
    {
        return $this->readOneof(20);
    }

    public function hasStatisticsType()
    {
        return $this->hasOneof(20);
    }

    /**
     * The statistics type enum value.
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcStatisticsType statisticsType = 20;</code>
     * @param int $var
     * @return $this
     */
    public function setStatisticsType($var)
    {
        GPBUtil::checkEnum($var, \Wtsvk\EvitaDbClient\Protocol\GrpcStatisticsType::class);
        $this->writeOneof(20, $var);

        return $this;
    }

    /**
     * The histogram behavior enum value.
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcHistogramBehavior histogramBehavior = 21;</code>
     * @return int
     */
    public function getHistogramBehavior()
    {
        return $this->readOneof(21);
    }

    public function hasHistogramBehavior()
    {
        return $this->hasOneof(21);
    }

    /**
     * The histogram behavior enum value.
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcHistogramBehavior histogramBehavior = 21;</code>
     * @param int $var
     * @return $this
     */
    public function setHistogramBehavior($var)
    {
        GPBUtil::checkEnum($var, \Wtsvk\EvitaDbClient\Protocol\GrpcHistogramBehavior::class);
        $this->writeOneof(21, $var);

        return $this;
    }

    /**
     * The managed references behaviour
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcManagedReferencesBehaviour managedReferencesBehaviour = 22;</code>
     * @return int
     */
    public function getManagedReferencesBehaviour()
    {
        return $this->readOneof(22);
    }

    public function hasManagedReferencesBehaviour()
    {
        return $this->hasOneof(22);
    }

    /**
     * The managed references behaviour
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcManagedReferencesBehaviour managedReferencesBehaviour = 22;</code>
     * @param int $var
     * @return $this
     */
    public function setManagedReferencesBehaviour($var)
    {
        GPBUtil::checkEnum($var, \Wtsvk\EvitaDbClient\Protocol\GrpcManagedReferencesBehaviour::class);
        $this->writeOneof(22, $var);

        return $this;
    }

    /**
     * The expression
     *
     * Generated from protobuf field <code>string expressionValue = 23;</code>
     * @return string
     */
    public function getExpressionValue()
    {
        return $this->readOneof(23);
    }

    public function hasExpressionValue()
    {
        return $this->hasOneof(23);
    }

    /**
     * The expression
     *
     * Generated from protobuf field <code>string expressionValue = 23;</code>
     * @param string $var
     * @return $this
     */
    public function setExpressionValue($var)
    {
        GPBUtil::checkString($var, True);
        $this->writeOneof(23, $var);

        return $this;
    }

    /**
     * The scope enum value.
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcEntityScope scope = 24;</code>
     * @return int
     */
    public function getScope()
    {
        return $this->readOneof(24);
    }

    public function hasScope()
    {
        return $this->hasOneof(24);
    }

    /**
     * The scope enum value.
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcEntityScope scope = 24;</code>
     * @param int $var
     * @return $this
     */
    public function setScope($var)
    {
        GPBUtil::checkEnum($var, \Wtsvk\EvitaDbClient\Protocol\GrpcEntityScope::class);
        $this->writeOneof(24, $var);

        return $this;
    }

    /**
     * The facetRelationType enum value.
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcFacetRelationType facetRelationType = 25;</code>
     * @return int
     */
    public function getFacetRelationType()
    {
        return $this->readOneof(25);
    }

    public function hasFacetRelationType()
    {
        return $this->hasOneof(25);
    }

    /**
     * The facetRelationType enum value.
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcFacetRelationType facetRelationType = 25;</code>
     * @param int $var
     * @return $this
     */
    public function setFacetRelationType($var)
    {
        GPBUtil::checkEnum($var, \Wtsvk\EvitaDbClient\Protocol\GrpcFacetRelationType::class);
        $this->writeOneof(25, $var);

        return $this;
    }

    /**
     * The facetGroupRelationLevel enum value.
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcFacetGroupRelationLevel facetGroupRelationLevel = 26;</code>
     * @return int
     */
    public function getFacetGroupRelationLevel()
    {
        return $this->readOneof(26);
    }

    public function hasFacetGroupRelationLevel()
    {
        return $this->hasOneof(26);
    }

    /**
     * The facetGroupRelationLevel enum value.
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcFacetGroupRelationLevel facetGroupRelationLevel = 26;</code>
     * @param int $var
     * @return $this
     */
    public function setFacetGroupRelationLevel($var)
    {
        GPBUtil::checkEnum($var, \Wtsvk\EvitaDbClient\Protocol\GrpcFacetGroupRelationLevel::class);
        $this->writeOneof(26, $var);

        return $this;
    }

    /**
     * The facet traversal mode enum value.
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcTraversalMode traversalMode = 27;</code>
     * @return int
     */
    public function getTraversalMode()
    {
        return $this->readOneof(27);
    }

    public function hasTraversalMode()
    {
        return $this->hasOneof(27);
    }

    /**
     * The facet traversal mode enum value.
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcTraversalMode traversalMode = 27;</code>
     * @param int $var
     * @return $this
     */
    public function setTraversalMode($var)
    {
        GPBUtil::checkEnum($var, \Wtsvk\EvitaDbClient\Protocol\GrpcTraversalMode::class);
        $this->writeOneof(27, $var);

        return $this;
    }

    /**
     * The string array value.
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcStringArray stringArrayValue = 101;</code>
     * @return \Wtsvk\EvitaDbClient\Protocol\GrpcStringArray|null
     */
    public function getStringArrayValue()
    {
        return $this->readOneof(101);
    }

    public function hasStringArrayValue()
    {
        return $this->hasOneof(101);
    }

    /**
     * The string array value.
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcStringArray stringArrayValue = 101;</code>
     * @param \Wtsvk\EvitaDbClient\Protocol\GrpcStringArray $var
     * @return $this
     */
    public function setStringArrayValue($var)
    {
        GPBUtil::checkMessage($var, \Wtsvk\EvitaDbClient\Protocol\GrpcStringArray::class);
        $this->writeOneof(101, $var);

        return $this;
    }

    /**
     * The integer array value.
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcIntegerArray integerArrayValue = 102;</code>
     * @return \Wtsvk\EvitaDbClient\Protocol\GrpcIntegerArray|null
     */
    public function getIntegerArrayValue()
    {
        return $this->readOneof(102);
    }

    public function hasIntegerArrayValue()
    {
        return $this->hasOneof(102);
    }

    /**
     * The integer array value.
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcIntegerArray integerArrayValue = 102;</code>
     * @param \Wtsvk\EvitaDbClient\Protocol\GrpcIntegerArray $var
     * @return $this
     */
    public function setIntegerArrayValue($var)
    {
        GPBUtil::checkMessage($var, \Wtsvk\EvitaDbClient\Protocol\GrpcIntegerArray::class);
        $this->writeOneof(102, $var);

        return $this;
    }

    /**
     * The long array value.
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcLongArray longArrayValue = 103;</code>
     * @return \Wtsvk\EvitaDbClient\Protocol\GrpcLongArray|null
     */
    public function getLongArrayValue()
    {
        return $this->readOneof(103);
    }

    public function hasLongArrayValue()
    {
        return $this->hasOneof(103);
    }

    /**
     * The long array value.
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcLongArray longArrayValue = 103;</code>
     * @param \Wtsvk\EvitaDbClient\Protocol\GrpcLongArray $var
     * @return $this
     */
    public function setLongArrayValue($var)
    {
        GPBUtil::checkMessage($var, \Wtsvk\EvitaDbClient\Protocol\GrpcLongArray::class);
        $this->writeOneof(103, $var);

        return $this;
    }

    /**
     * The boolean array value.
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcBooleanArray booleanArrayValue = 104;</code>
     * @return \Wtsvk\EvitaDbClient\Protocol\GrpcBooleanArray|null
     */
    public function getBooleanArrayValue()
    {
        return $this->readOneof(104);
    }

    public function hasBooleanArrayValue()
    {
        return $this->hasOneof(104);
    }

    /**
     * The boolean array value.
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcBooleanArray booleanArrayValue = 104;</code>
     * @param \Wtsvk\EvitaDbClient\Protocol\GrpcBooleanArray $var
     * @return $this
     */
    public function setBooleanArrayValue($var)
    {
        GPBUtil::checkMessage($var, \Wtsvk\EvitaDbClient\Protocol\GrpcBooleanArray::class);
        $this->writeOneof(104, $var);

        return $this;
    }

    /**
     * The big decimal array value.
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcBigDecimalArray bigDecimalArrayValue = 105;</code>
     * @return \Wtsvk\EvitaDbClient\Protocol\GrpcBigDecimalArray|null
     */
    public function getBigDecimalArrayValue()
    {
        return $this->readOneof(105);
    }

    public function hasBigDecimalArrayValue()
    {
        return $this->hasOneof(105);
    }

    /**
     * The big decimal array value.
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcBigDecimalArray bigDecimalArrayValue = 105;</code>
     * @param \Wtsvk\EvitaDbClient\Protocol\GrpcBigDecimalArray $var
     * @return $this
     */
    public function setBigDecimalArrayValue($var)
    {
        GPBUtil::checkMessage($var, \Wtsvk\EvitaDbClient\Protocol\GrpcBigDecimalArray::class);
        $this->writeOneof(105, $var);

        return $this;
    }

    /**
     * The date time range array value.
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcDateTimeRangeArray dateTimeRangeArrayValue = 106;</code>
     * @return \Wtsvk\EvitaDbClient\Protocol\GrpcDateTimeRangeArray|null
     */
    public function getDateTimeRangeArrayValue()
    {
        return $this->readOneof(106);
    }

    public function hasDateTimeRangeArrayValue()
    {
        return $this->hasOneof(106);
    }

    /**
     * The date time range array value.
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcDateTimeRangeArray dateTimeRangeArrayValue = 106;</code>
     * @param \Wtsvk\EvitaDbClient\Protocol\GrpcDateTimeRangeArray $var
     * @return $this
     */
    public function setDateTimeRangeArrayValue($var)
    {
        GPBUtil::checkMessage($var, \Wtsvk\EvitaDbClient\Protocol\GrpcDateTimeRangeArray::class);
        $this->writeOneof(106, $var);

        return $this;
    }

    /**
     * The integer number range array value.
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcIntegerNumberRangeArray integerNumberRangeArrayValue = 107;</code>
     * @return \Wtsvk\EvitaDbClient\Protocol\GrpcIntegerNumberRangeArray|null
     */
    public function getIntegerNumberRangeArrayValue()
    {
        return $this->readOneof(107);
    }

    public function hasIntegerNumberRangeArrayValue()
    {
        return $this->hasOneof(107);
    }

    /**
     * The integer number range array value.
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcIntegerNumberRangeArray integerNumberRangeArrayValue = 107;</code>
     * @param \Wtsvk\EvitaDbClient\Protocol\GrpcIntegerNumberRangeArray $var
     * @return $this
     */
    public function setIntegerNumberRangeArrayValue($var)
    {
        GPBUtil::checkMessage($var, \Wtsvk\EvitaDbClient\Protocol\GrpcIntegerNumberRangeArray::class);
        $this->writeOneof(107, $var);

        return $this;
    }

    /**
     * The long number range array value.
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcLongNumberRangeArray longNumberRangeArrayValue = 108;</code>
     * @return \Wtsvk\EvitaDbClient\Protocol\GrpcLongNumberRangeArray|null
     */
    public function getLongNumberRangeArrayValue()
    {
        return $this->readOneof(108);
    }

    public function hasLongNumberRangeArrayValue()
    {
        return $this->hasOneof(108);
    }

    /**
     * The long number range array value.
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcLongNumberRangeArray longNumberRangeArrayValue = 108;</code>
     * @param \Wtsvk\EvitaDbClient\Protocol\GrpcLongNumberRangeArray $var
     * @return $this
     */
    public function setLongNumberRangeArrayValue($var)
    {
        GPBUtil::checkMessage($var, \Wtsvk\EvitaDbClient\Protocol\GrpcLongNumberRangeArray::class);
        $this->writeOneof(108, $var);

        return $this;
    }

    /**
     * The big decimal number range array value.
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcBigDecimalNumberRangeArray bigDecimalNumberRangeArrayValue = 109;</code>
     * @return \Wtsvk\EvitaDbClient\Protocol\GrpcBigDecimalNumberRangeArray|null
     */
    public function getBigDecimalNumberRangeArrayValue()
    {
        return $this->readOneof(109);
    }

    public function hasBigDecimalNumberRangeArrayValue()
    {
        return $this->hasOneof(109);
    }

    /**
     * The big decimal number range array value.
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcBigDecimalNumberRangeArray bigDecimalNumberRangeArrayValue = 109;</code>
     * @param \Wtsvk\EvitaDbClient\Protocol\GrpcBigDecimalNumberRangeArray $var
     * @return $this
     */
    public function setBigDecimalNumberRangeArrayValue($var)
    {
        GPBUtil::checkMessage($var, \Wtsvk\EvitaDbClient\Protocol\GrpcBigDecimalNumberRangeArray::class);
        $this->writeOneof(109, $var);

        return $this;
    }

    /**
     * The offset date time array value.
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcOffsetDateTimeArray offsetDateTimeArrayValue = 110;</code>
     * @return \Wtsvk\EvitaDbClient\Protocol\GrpcOffsetDateTimeArray|null
     */
    public function getOffsetDateTimeArrayValue()
    {
        return $this->readOneof(110);
    }

    public function hasOffsetDateTimeArrayValue()
    {
        return $this->hasOneof(110);
    }

    /**
     * The offset date time array value.
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcOffsetDateTimeArray offsetDateTimeArrayValue = 110;</code>
     * @param \Wtsvk\EvitaDbClient\Protocol\GrpcOffsetDateTimeArray $var
     * @return $this
     */
    public function setOffsetDateTimeArrayValue($var)
    {
        GPBUtil::checkMessage($var, \Wtsvk\EvitaDbClient\Protocol\GrpcOffsetDateTimeArray::class);
        $this->writeOneof(110, $var);

        return $this;
    }

    /**
     * The locale array value.
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcLocaleArray localeArrayValue = 111;</code>
     * @return \Wtsvk\EvitaDbClient\Protocol\GrpcLocaleArray|null
     */
    public function getLocaleArrayValue()
    {
        return $this->readOneof(111);
    }

    public function hasLocaleArrayValue()
    {
        return $this->hasOneof(111);
    }

    /**
     * The locale array value.
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcLocaleArray localeArrayValue = 111;</code>
     * @param \Wtsvk\EvitaDbClient\Protocol\GrpcLocaleArray $var
     * @return $this
     */
    public function setLocaleArrayValue($var)
    {
        GPBUtil::checkMessage($var, \Wtsvk\EvitaDbClient\Protocol\GrpcLocaleArray::class);
        $this->writeOneof(111, $var);

        return $this;
    }

    /**
     * The currency array value.
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcCurrencyArray currencyArrayValue = 112;</code>
     * @return \Wtsvk\EvitaDbClient\Protocol\GrpcCurrencyArray|null
     */
    public function getCurrencyArrayValue()
    {
        return $this->readOneof(112);
    }

    public function hasCurrencyArrayValue()
    {
        return $this->hasOneof(112);
    }

    /**
     * The currency array value.
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcCurrencyArray currencyArrayValue = 112;</code>
     * @param \Wtsvk\EvitaDbClient\Protocol\GrpcCurrencyArray $var
     * @return $this
     */
    public function setCurrencyArrayValue($var)
    {
        GPBUtil::checkMessage($var, \Wtsvk\EvitaDbClient\Protocol\GrpcCurrencyArray::class);
        $this->writeOneof(112, $var);

        return $this;
    }

    /**
     * The facet statistics depth array value.
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcFacetStatisticsDepthArray facetStatisticsDepthArrayValue = 113;</code>
     * @return \Wtsvk\EvitaDbClient\Protocol\GrpcFacetStatisticsDepthArray|null
     */
    public function getFacetStatisticsDepthArrayValue()
    {
        return $this->readOneof(113);
    }

    public function hasFacetStatisticsDepthArrayValue()
    {
        return $this->hasOneof(113);
    }

    /**
     * The facet statistics depth array value.
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcFacetStatisticsDepthArray facetStatisticsDepthArrayValue = 113;</code>
     * @param \Wtsvk\EvitaDbClient\Protocol\GrpcFacetStatisticsDepthArray $var
     * @return $this
     */
    public function setFacetStatisticsDepthArrayValue($var)
    {
        GPBUtil::checkMessage($var, \Wtsvk\EvitaDbClient\Protocol\GrpcFacetStatisticsDepthArray::class);
        $this->writeOneof(113, $var);

        return $this;
    }

    /**
     * The query price mode array value.
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcQueryPriceModeArray queryPriceModelArrayValue = 114;</code>
     * @return \Wtsvk\EvitaDbClient\Protocol\GrpcQueryPriceModeArray|null
     */
    public function getQueryPriceModelArrayValue()
    {
        return $this->readOneof(114);
    }

    public function hasQueryPriceModelArrayValue()
    {
        return $this->hasOneof(114);
    }

    /**
     * The query price mode array value.
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcQueryPriceModeArray queryPriceModelArrayValue = 114;</code>
     * @param \Wtsvk\EvitaDbClient\Protocol\GrpcQueryPriceModeArray $var
     * @return $this
     */
    public function setQueryPriceModelArrayValue($var)
    {
        GPBUtil::checkMessage($var, \Wtsvk\EvitaDbClient\Protocol\GrpcQueryPriceModeArray::class);
        $this->writeOneof(114, $var);

        return $this;
    }

    /**
     * The price content mode array value.
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcPriceContentModeArray priceContentModeArrayValue = 115;</code>
     * @return \Wtsvk\EvitaDbClient\Protocol\GrpcPriceContentModeArray|null
     */
    public function getPriceContentModeArrayValue()
    {
        return $this->readOneof(115);
    }

    public function hasPriceContentModeArrayValue()
    {
        return $this->hasOneof(115);
    }

    /**
     * The price content mode array value.
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcPriceContentModeArray priceContentModeArrayValue = 115;</code>
     * @param \Wtsvk\EvitaDbClient\Protocol\GrpcPriceContentModeArray $var
     * @return $this
     */
    public function setPriceContentModeArrayValue($var)
    {
        GPBUtil::checkMessage($var, \Wtsvk\EvitaDbClient\Protocol\GrpcPriceContentModeArray::class);
        $this->writeOneof(115, $var);

        return $this;
    }

    /**
     * The attribute special value array value.
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcAttributeSpecialValueArray attributeSpecialArrayValue = 116;</code>
     * @return \Wtsvk\EvitaDbClient\Protocol\GrpcAttributeSpecialValueArray|null
     */
    public function getAttributeSpecialArrayValue()
    {
        return $this->readOneof(116);
    }

    public function hasAttributeSpecialArrayValue()
    {
        return $this->hasOneof(116);
    }

    /**
     * The attribute special value array value.
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcAttributeSpecialValueArray attributeSpecialArrayValue = 116;</code>
     * @param \Wtsvk\EvitaDbClient\Protocol\GrpcAttributeSpecialValueArray $var
     * @return $this
     */
    public function setAttributeSpecialArrayValue($var)
    {
        GPBUtil::checkMessage($var, \Wtsvk\EvitaDbClient\Protocol\GrpcAttributeSpecialValueArray::class);
        $this->writeOneof(116, $var);

        return $this;
    }

    /**
     * The order direction array value.
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcOrderDirectionArray orderDirectionArrayValue = 117;</code>
     * @return \Wtsvk\EvitaDbClient\Protocol\GrpcOrderDirectionArray|null
     */
    public function getOrderDirectionArrayValue()
    {
        return $this->readOneof(117);
    }

    public function hasOrderDirectionArrayValue()
    {
        return $this->hasOneof(117);
    }

    /**
     * The order direction array value.
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcOrderDirectionArray orderDirectionArrayValue = 117;</code>
     * @param \Wtsvk\EvitaDbClient\Protocol\GrpcOrderDirectionArray $var
     * @return $this
     */
    public function setOrderDirectionArrayValue($var)
    {
        GPBUtil::checkMessage($var, \Wtsvk\EvitaDbClient\Protocol\GrpcOrderDirectionArray::class);
        $this->writeOneof(117, $var);

        return $this;
    }

    /**
     * The empty hierarchical entity behaviour array value.
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcEmptyHierarchicalEntityBehaviourArray emptyHierarchicalEntityBehaviourArrayValue = 118;</code>
     * @return \Wtsvk\EvitaDbClient\Protocol\GrpcEmptyHierarchicalEntityBehaviourArray|null
     */
    public function getEmptyHierarchicalEntityBehaviourArrayValue()
    {
        return $this->readOneof(118);
    }

    public function hasEmptyHierarchicalEntityBehaviourArrayValue()
    {
        return $this->hasOneof(118);
    }

    /**
     * The empty hierarchical entity behaviour array value.
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcEmptyHierarchicalEntityBehaviourArray emptyHierarchicalEntityBehaviourArrayValue = 118;</code>
     * @param \Wtsvk\EvitaDbClient\Protocol\GrpcEmptyHierarchicalEntityBehaviourArray $var
     * @return $this
     */
    public function setEmptyHierarchicalEntityBehaviourArrayValue($var)
    {
        GPBUtil::checkMessage($var, \Wtsvk\EvitaDbClient\Protocol\GrpcEmptyHierarchicalEntityBehaviourArray::class);
        $this->writeOneof(118, $var);

        return $this;
    }

    /**
     * The statistics base array value.
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcStatisticsBaseArray statisticsBaseArrayValue = 119;</code>
     * @return \Wtsvk\EvitaDbClient\Protocol\GrpcStatisticsBaseArray|null
     */
    public function getStatisticsBaseArrayValue()
    {
        return $this->readOneof(119);
    }

    public function hasStatisticsBaseArrayValue()
    {
        return $this->hasOneof(119);
    }

    /**
     * The statistics base array value.
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcStatisticsBaseArray statisticsBaseArrayValue = 119;</code>
     * @param \Wtsvk\EvitaDbClient\Protocol\GrpcStatisticsBaseArray $var
     * @return $this
     */
    public function setStatisticsBaseArrayValue($var)
    {
        GPBUtil::checkMessage($var, \Wtsvk\EvitaDbClient\Protocol\GrpcStatisticsBaseArray::class);
        $this->writeOneof(119, $var);

        return $this;
    }

    /**
     * The statistics type array value.
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcStatisticsTypeArray statisticsTypeArrayValue = 120;</code>
     * @return \Wtsvk\EvitaDbClient\Protocol\GrpcStatisticsTypeArray|null
     */
    public function getStatisticsTypeArrayValue()
    {
        return $this->readOneof(120);
    }

    public function hasStatisticsTypeArrayValue()
    {
        return $this->hasOneof(120);
    }

    /**
     * The statistics type array value.
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcStatisticsTypeArray statisticsTypeArrayValue = 120;</code>
     * @param \Wtsvk\EvitaDbClient\Protocol\GrpcStatisticsTypeArray $var
     * @return $this
     */
    public function setStatisticsTypeArrayValue($var)
    {
        GPBUtil::checkMessage($var, \Wtsvk\EvitaDbClient\Protocol\GrpcStatisticsTypeArray::class);
        $this->writeOneof(120, $var);

        return $this;
    }

    /**
     * The histogram behavior enum value.
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcHistogramBehaviorTypeArray histogramBehaviorTypeArrayValue = 121;</code>
     * @return \Wtsvk\EvitaDbClient\Protocol\GrpcHistogramBehaviorTypeArray|null
     */
    public function getHistogramBehaviorTypeArrayValue()
    {
        return $this->readOneof(121);
    }

    public function hasHistogramBehaviorTypeArrayValue()
    {
        return $this->hasOneof(121);
    }

    /**
     * The histogram behavior enum value.
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcHistogramBehaviorTypeArray histogramBehaviorTypeArrayValue = 121;</code>
     * @param \Wtsvk\EvitaDbClient\Protocol\GrpcHistogramBehaviorTypeArray $var
     * @return $this
     */
    public function setHistogramBehaviorTypeArrayValue($var)
    {
        GPBUtil::checkMessage($var, \Wtsvk\EvitaDbClient\Protocol\GrpcHistogramBehaviorTypeArray::class);
        $this->writeOneof(121, $var);

        return $this;
    }

    /**
     * The scope enum value.
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcEntityScopeArray scopeArrayValue = 122;</code>
     * @return \Wtsvk\EvitaDbClient\Protocol\GrpcEntityScopeArray|null
     */
    public function getScopeArrayValue()
    {
        return $this->readOneof(122);
    }

    public function hasScopeArrayValue()
    {
        return $this->hasOneof(122);
    }

    /**
     * The scope enum value.
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcEntityScopeArray scopeArrayValue = 122;</code>
     * @param \Wtsvk\EvitaDbClient\Protocol\GrpcEntityScopeArray $var
     * @return $this
     */
    public function setScopeArrayValue($var)
    {
        GPBUtil::checkMessage($var, \Wtsvk\EvitaDbClient\Protocol\GrpcEntityScopeArray::class);
        $this->writeOneof(122, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getQueryParam()
    {
        return $this->whichOneof("queryParam");
    }

}

