<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GrpcEntity.proto

namespace Wtsvk\EvitaDbClient\Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Represents a pair of reference keys used for tracking reassigned internal primary keys.
 * The 'original' key contains the temporary internal PK, while the 'reassigned' key contains
 * the permanent internal PK assigned after persistence.
 *
 * Generated from protobuf message <code>io.evitadb.externalApi.grpc.generated.GrpcReferenceKeyPair</code>
 */
class GrpcReferenceKeyPair extends \Google\Protobuf\Internal\Message
{
    /**
     * Name of the reference (e.g., "category", "brand").
     * References the reference schema name that defines the type of relationship.
     *
     * Generated from protobuf field <code>string referenceName = 1;</code>
     */
    protected $referenceName = '';
    /**
     * Primary key of the referenced entity.
     * May be either an evitaDB entity primary key or an external resource identifier.
     *
     * Generated from protobuf field <code>int32 primaryKey = 2;</code>
     */
    protected $primaryKey = 0;
    /**
     * Original reference key with temporary internal primary key (negative number).
     *
     * Generated from protobuf field <code>int32 originalInternalPrimaryKey = 3;</code>
     */
    protected $originalInternalPrimaryKey = 0;
    /**
     * Reassigned reference key with permanent internal primary key (positive number) assigned by the server.
     *
     * Generated from protobuf field <code>int32 reassignedInternalPrimaryKey = 4;</code>
     */
    protected $reassignedInternalPrimaryKey = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $referenceName
     *           Name of the reference (e.g., "category", "brand").
     *           References the reference schema name that defines the type of relationship.
     *     @type int $primaryKey
     *           Primary key of the referenced entity.
     *           May be either an evitaDB entity primary key or an external resource identifier.
     *     @type int $originalInternalPrimaryKey
     *           Original reference key with temporary internal primary key (negative number).
     *     @type int $reassignedInternalPrimaryKey
     *           Reassigned reference key with permanent internal primary key (positive number) assigned by the server.
     * }
     */
    public function __construct($data = NULL) {
        \Wtsvk\EvitaDbClient\Protocol\GPBMetadata\GrpcEntity::initOnce();
        parent::__construct($data);
    }

    /**
     * Name of the reference (e.g., "category", "brand").
     * References the reference schema name that defines the type of relationship.
     *
     * Generated from protobuf field <code>string referenceName = 1;</code>
     * @return string
     */
    public function getReferenceName()
    {
        return $this->referenceName;
    }

    /**
     * Name of the reference (e.g., "category", "brand").
     * References the reference schema name that defines the type of relationship.
     *
     * Generated from protobuf field <code>string referenceName = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setReferenceName($var)
    {
        GPBUtil::checkString($var, True);
        $this->referenceName = $var;

        return $this;
    }

    /**
     * Primary key of the referenced entity.
     * May be either an evitaDB entity primary key or an external resource identifier.
     *
     * Generated from protobuf field <code>int32 primaryKey = 2;</code>
     * @return int
     */
    public function getPrimaryKey()
    {
        return $this->primaryKey;
    }

    /**
     * Primary key of the referenced entity.
     * May be either an evitaDB entity primary key or an external resource identifier.
     *
     * Generated from protobuf field <code>int32 primaryKey = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setPrimaryKey($var)
    {
        GPBUtil::checkInt32($var);
        $this->primaryKey = $var;

        return $this;
    }

    /**
     * Original reference key with temporary internal primary key (negative number).
     *
     * Generated from protobuf field <code>int32 originalInternalPrimaryKey = 3;</code>
     * @return int
     */
    public function getOriginalInternalPrimaryKey()
    {
        return $this->originalInternalPrimaryKey;
    }

    /**
     * Original reference key with temporary internal primary key (negative number).
     *
     * Generated from protobuf field <code>int32 originalInternalPrimaryKey = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setOriginalInternalPrimaryKey($var)
    {
        GPBUtil::checkInt32($var);
        $this->originalInternalPrimaryKey = $var;

        return $this;
    }

    /**
     * Reassigned reference key with permanent internal primary key (positive number) assigned by the server.
     *
     * Generated from protobuf field <code>int32 reassignedInternalPrimaryKey = 4;</code>
     * @return int
     */
    public function getReassignedInternalPrimaryKey()
    {
        return $this->reassignedInternalPrimaryKey;
    }

    /**
     * Reassigned reference key with permanent internal primary key (positive number) assigned by the server.
     *
     * Generated from protobuf field <code>int32 reassignedInternalPrimaryKey = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setReassignedInternalPrimaryKey($var)
    {
        GPBUtil::checkInt32($var);
        $this->reassignedInternalPrimaryKey = $var;

        return $this;
    }

}

