<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GrpcReferenceMutations.proto

namespace Wtsvk\EvitaDbClient\Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * This mutation allows to create a reference in the entity.
 *
 * Generated from protobuf message <code>io.evitadb.externalApi.grpc.generated.GrpcInsertReferenceMutation</code>
 */
class GrpcInsertReferenceMutation extends \Google\Protobuf\Internal\Message
{
    /**
     * Unique identifier of the reference.
     *
     * Generated from protobuf field <code>string referenceName = 1;</code>
     */
    protected $referenceName = '';
    /**
     * Primary key of the referenced entity. Might be also any integer that uniquely identifies some external
     * resource not maintained by Evita.
     *
     * Generated from protobuf field <code>int32 referencePrimaryKey = 2;</code>
     */
    protected $referencePrimaryKey = 0;
    /**
     * Contains information about reference cardinality. This value is usually NULL except the case when the reference
     * is created for the first time and `EvolutionMode.ADDING_REFERENCES` is allowed.
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcCardinality referenceCardinality = 3;</code>
     */
    protected $referenceCardinality = 0;
    /**
     * Contains information about target entity type. This value is usually NULL except the case when the reference
     * is created for the first time and `EvolutionMode.ADDING_REFERENCES` is allowed.
     *
     * Generated from protobuf field <code>.google.protobuf.StringValue referencedEntityType = 4;</code>
     */
    protected $referencedEntityType = null;
    /**
     * internal PK is assigned by evitaDB engine and is used to uniquely identify the
     * reference among other references. It is used when multiple references share same
     * business key - entityType and primaryKey - but differ by other properties (fe. reference group or attributes).
     * When a reference is created for the first time, internal id is set to a unique
     * negative number that is not used by the server side, which assigns positive unique
     * numbers to the references on first reference persistence. This allows distinguishing
     * references that are not yet persisted from those that are already persistent.
     * When standalone key is used:
     * - negative number: means that the reference is new and hasn't been yet persisted
     * - zero: means we don't know the internal PK
     * - positive number: means that the reference is persistent and has been already stored
     *   in the database
     *
     * Generated from protobuf field <code>int32 internalPrimaryKey = 5;</code>
     */
    protected $internalPrimaryKey = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $referenceName
     *           Unique identifier of the reference.
     *     @type int $referencePrimaryKey
     *           Primary key of the referenced entity. Might be also any integer that uniquely identifies some external
     *           resource not maintained by Evita.
     *     @type int $referenceCardinality
     *           Contains information about reference cardinality. This value is usually NULL except the case when the reference
     *           is created for the first time and `EvolutionMode.ADDING_REFERENCES` is allowed.
     *     @type \Google\Protobuf\StringValue $referencedEntityType
     *           Contains information about target entity type. This value is usually NULL except the case when the reference
     *           is created for the first time and `EvolutionMode.ADDING_REFERENCES` is allowed.
     *     @type int $internalPrimaryKey
     *           internal PK is assigned by evitaDB engine and is used to uniquely identify the
     *           reference among other references. It is used when multiple references share same
     *           business key - entityType and primaryKey - but differ by other properties (fe. reference group or attributes).
     *           When a reference is created for the first time, internal id is set to a unique
     *           negative number that is not used by the server side, which assigns positive unique
     *           numbers to the references on first reference persistence. This allows distinguishing
     *           references that are not yet persisted from those that are already persistent.
     *           When standalone key is used:
     *           - negative number: means that the reference is new and hasn't been yet persisted
     *           - zero: means we don't know the internal PK
     *           - positive number: means that the reference is persistent and has been already stored
     *             in the database
     * }
     */
    public function __construct($data = NULL) {
        \Wtsvk\EvitaDbClient\Protocol\GPBMetadata\GrpcReferenceMutations::initOnce();
        parent::__construct($data);
    }

    /**
     * Unique identifier of the reference.
     *
     * Generated from protobuf field <code>string referenceName = 1;</code>
     * @return string
     */
    public function getReferenceName()
    {
        return $this->referenceName;
    }

    /**
     * Unique identifier of the reference.
     *
     * Generated from protobuf field <code>string referenceName = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setReferenceName($var)
    {
        GPBUtil::checkString($var, True);
        $this->referenceName = $var;

        return $this;
    }

    /**
     * Primary key of the referenced entity. Might be also any integer that uniquely identifies some external
     * resource not maintained by Evita.
     *
     * Generated from protobuf field <code>int32 referencePrimaryKey = 2;</code>
     * @return int
     */
    public function getReferencePrimaryKey()
    {
        return $this->referencePrimaryKey;
    }

    /**
     * Primary key of the referenced entity. Might be also any integer that uniquely identifies some external
     * resource not maintained by Evita.
     *
     * Generated from protobuf field <code>int32 referencePrimaryKey = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setReferencePrimaryKey($var)
    {
        GPBUtil::checkInt32($var);
        $this->referencePrimaryKey = $var;

        return $this;
    }

    /**
     * Contains information about reference cardinality. This value is usually NULL except the case when the reference
     * is created for the first time and `EvolutionMode.ADDING_REFERENCES` is allowed.
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcCardinality referenceCardinality = 3;</code>
     * @return int
     */
    public function getReferenceCardinality()
    {
        return $this->referenceCardinality;
    }

    /**
     * Contains information about reference cardinality. This value is usually NULL except the case when the reference
     * is created for the first time and `EvolutionMode.ADDING_REFERENCES` is allowed.
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcCardinality referenceCardinality = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setReferenceCardinality($var)
    {
        GPBUtil::checkEnum($var, \Wtsvk\EvitaDbClient\Protocol\GrpcCardinality::class);
        $this->referenceCardinality = $var;

        return $this;
    }

    /**
     * Contains information about target entity type. This value is usually NULL except the case when the reference
     * is created for the first time and `EvolutionMode.ADDING_REFERENCES` is allowed.
     *
     * Generated from protobuf field <code>.google.protobuf.StringValue referencedEntityType = 4;</code>
     * @return \Google\Protobuf\StringValue|null
     */
    public function getReferencedEntityType()
    {
        return $this->referencedEntityType;
    }

    public function hasReferencedEntityType()
    {
        return isset($this->referencedEntityType);
    }

    public function clearReferencedEntityType()
    {
        unset($this->referencedEntityType);
    }

    /**
     * Returns the unboxed value from <code>getReferencedEntityType()</code>

     * Contains information about target entity type. This value is usually NULL except the case when the reference
     * is created for the first time and `EvolutionMode.ADDING_REFERENCES` is allowed.
     *
     * Generated from protobuf field <code>.google.protobuf.StringValue referencedEntityType = 4;</code>
     * @return string|null
     */
    public function getReferencedEntityTypeUnwrapped()
    {
        return $this->readWrapperValue("referencedEntityType");
    }

    /**
     * Contains information about target entity type. This value is usually NULL except the case when the reference
     * is created for the first time and `EvolutionMode.ADDING_REFERENCES` is allowed.
     *
     * Generated from protobuf field <code>.google.protobuf.StringValue referencedEntityType = 4;</code>
     * @param \Google\Protobuf\StringValue $var
     * @return $this
     */
    public function setReferencedEntityType($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\StringValue::class);
        $this->referencedEntityType = $var;

        return $this;
    }

    /**
     * Sets the field by wrapping a primitive type in a Google\Protobuf\StringValue object.

     * Contains information about target entity type. This value is usually NULL except the case when the reference
     * is created for the first time and `EvolutionMode.ADDING_REFERENCES` is allowed.
     *
     * Generated from protobuf field <code>.google.protobuf.StringValue referencedEntityType = 4;</code>
     * @param string|null $var
     * @return $this
     */
    public function setReferencedEntityTypeUnwrapped($var)
    {
        $this->writeWrapperValue("referencedEntityType", $var);
        return $this;}

    /**
     * internal PK is assigned by evitaDB engine and is used to uniquely identify the
     * reference among other references. It is used when multiple references share same
     * business key - entityType and primaryKey - but differ by other properties (fe. reference group or attributes).
     * When a reference is created for the first time, internal id is set to a unique
     * negative number that is not used by the server side, which assigns positive unique
     * numbers to the references on first reference persistence. This allows distinguishing
     * references that are not yet persisted from those that are already persistent.
     * When standalone key is used:
     * - negative number: means that the reference is new and hasn't been yet persisted
     * - zero: means we don't know the internal PK
     * - positive number: means that the reference is persistent and has been already stored
     *   in the database
     *
     * Generated from protobuf field <code>int32 internalPrimaryKey = 5;</code>
     * @return int
     */
    public function getInternalPrimaryKey()
    {
        return $this->internalPrimaryKey;
    }

    /**
     * internal PK is assigned by evitaDB engine and is used to uniquely identify the
     * reference among other references. It is used when multiple references share same
     * business key - entityType and primaryKey - but differ by other properties (fe. reference group or attributes).
     * When a reference is created for the first time, internal id is set to a unique
     * negative number that is not used by the server side, which assigns positive unique
     * numbers to the references on first reference persistence. This allows distinguishing
     * references that are not yet persisted from those that are already persistent.
     * When standalone key is used:
     * - negative number: means that the reference is new and hasn't been yet persisted
     * - zero: means we don't know the internal PK
     * - positive number: means that the reference is persistent and has been already stored
     *   in the database
     *
     * Generated from protobuf field <code>int32 internalPrimaryKey = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setInternalPrimaryKey($var)
    {
        GPBUtil::checkInt32($var);
        $this->internalPrimaryKey = $var;

        return $this;
    }

}

