<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GrpcEvitaDataTypes.proto

namespace Wtsvk\EvitaDbClient\Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Structure that holds a array of values stored inside array of the complex object.
 *
 * Generated from protobuf message <code>io.evitadb.externalApi.grpc.generated.GrpcDataItemArray</code>
 */
class GrpcDataItemArray extends \Google\Protobuf\Internal\Message
{
    /**
     * The stored array of values.
     *
     * Generated from protobuf field <code>repeated .io.evitadb.externalApi.grpc.generated.GrpcDataItem children = 1;</code>
     */
    private $children;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\Wtsvk\EvitaDbClient\Protocol\GrpcDataItem>|\Google\Protobuf\Internal\RepeatedField $children
     *           The stored array of values.
     * }
     */
    public function __construct($data = NULL) {
        \Wtsvk\EvitaDbClient\Protocol\GPBMetadata\GrpcEvitaDataTypes::initOnce();
        parent::__construct($data);
    }

    /**
     * The stored array of values.
     *
     * Generated from protobuf field <code>repeated .io.evitadb.externalApi.grpc.generated.GrpcDataItem children = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getChildren()
    {
        return $this->children;
    }

    /**
     * The stored array of values.
     *
     * Generated from protobuf field <code>repeated .io.evitadb.externalApi.grpc.generated.GrpcDataItem children = 1;</code>
     * @param array<\Wtsvk\EvitaDbClient\Protocol\GrpcDataItem>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setChildren($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Wtsvk\EvitaDbClient\Protocol\GrpcDataItem::class);
        $this->children = $arr;

        return $this;
    }

}

