<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GrpcInfrastrutureMutation.proto

namespace Wtsvk\EvitaDbClient\Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * This transaction mutation delimits mutations of one transaction from another. It contains data that allow to recognize
 * the scope of the transaction and verify its integrity.
 *
 * Generated from protobuf message <code>io.evitadb.externalApi.grpc.generated.GrpcTransactionMutation</code>
 */
class GrpcTransactionMutation extends \Google\Protobuf\Internal\Message
{
    /**
     * Represents the unique identifier of a transaction.
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcUuid transactionId = 1;</code>
     */
    protected $transactionId = null;
    /**
     * Represents the next version the transaction transitions the state to.
     *
     * Generated from protobuf field <code>int64 version = 2;</code>
     */
    protected $version = 0;
    /**
     * Represents the number of mutations in this particular transaction.
     *
     * Generated from protobuf field <code>int32 mutationCount = 3;</code>
     */
    protected $mutationCount = 0;
    /**
     * Represents the size of the serialized transaction mutations that follow this mutation in bytes.
     *
     * Generated from protobuf field <code>int64 walSizeInBytes = 4;</code>
     */
    protected $walSizeInBytes = 0;
    /**
     * Represents the timestamp of the commit.
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcOffsetDateTime commitTimestamp = 5;</code>
     */
    protected $commitTimestamp = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Wtsvk\EvitaDbClient\Protocol\GrpcUuid $transactionId
     *           Represents the unique identifier of a transaction.
     *     @type int|string $version
     *           Represents the next version the transaction transitions the state to.
     *     @type int $mutationCount
     *           Represents the number of mutations in this particular transaction.
     *     @type int|string $walSizeInBytes
     *           Represents the size of the serialized transaction mutations that follow this mutation in bytes.
     *     @type \Wtsvk\EvitaDbClient\Protocol\GrpcOffsetDateTime $commitTimestamp
     *           Represents the timestamp of the commit.
     * }
     */
    public function __construct($data = NULL) {
        \Wtsvk\EvitaDbClient\Protocol\GPBMetadata\GrpcInfrastrutureMutation::initOnce();
        parent::__construct($data);
    }

    /**
     * Represents the unique identifier of a transaction.
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcUuid transactionId = 1;</code>
     * @return \Wtsvk\EvitaDbClient\Protocol\GrpcUuid|null
     */
    public function getTransactionId()
    {
        return $this->transactionId;
    }

    public function hasTransactionId()
    {
        return isset($this->transactionId);
    }

    public function clearTransactionId()
    {
        unset($this->transactionId);
    }

    /**
     * Represents the unique identifier of a transaction.
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcUuid transactionId = 1;</code>
     * @param \Wtsvk\EvitaDbClient\Protocol\GrpcUuid $var
     * @return $this
     */
    public function setTransactionId($var)
    {
        GPBUtil::checkMessage($var, \Wtsvk\EvitaDbClient\Protocol\GrpcUuid::class);
        $this->transactionId = $var;

        return $this;
    }

    /**
     * Represents the next version the transaction transitions the state to.
     *
     * Generated from protobuf field <code>int64 version = 2;</code>
     * @return int|string
     */
    public function getVersion()
    {
        return $this->version;
    }

    /**
     * Represents the next version the transaction transitions the state to.
     *
     * Generated from protobuf field <code>int64 version = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setVersion($var)
    {
        GPBUtil::checkInt64($var);
        $this->version = $var;

        return $this;
    }

    /**
     * Represents the number of mutations in this particular transaction.
     *
     * Generated from protobuf field <code>int32 mutationCount = 3;</code>
     * @return int
     */
    public function getMutationCount()
    {
        return $this->mutationCount;
    }

    /**
     * Represents the number of mutations in this particular transaction.
     *
     * Generated from protobuf field <code>int32 mutationCount = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setMutationCount($var)
    {
        GPBUtil::checkInt32($var);
        $this->mutationCount = $var;

        return $this;
    }

    /**
     * Represents the size of the serialized transaction mutations that follow this mutation in bytes.
     *
     * Generated from protobuf field <code>int64 walSizeInBytes = 4;</code>
     * @return int|string
     */
    public function getWalSizeInBytes()
    {
        return $this->walSizeInBytes;
    }

    /**
     * Represents the size of the serialized transaction mutations that follow this mutation in bytes.
     *
     * Generated from protobuf field <code>int64 walSizeInBytes = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setWalSizeInBytes($var)
    {
        GPBUtil::checkInt64($var);
        $this->walSizeInBytes = $var;

        return $this;
    }

    /**
     * Represents the timestamp of the commit.
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcOffsetDateTime commitTimestamp = 5;</code>
     * @return \Wtsvk\EvitaDbClient\Protocol\GrpcOffsetDateTime|null
     */
    public function getCommitTimestamp()
    {
        return $this->commitTimestamp;
    }

    public function hasCommitTimestamp()
    {
        return isset($this->commitTimestamp);
    }

    public function clearCommitTimestamp()
    {
        unset($this->commitTimestamp);
    }

    /**
     * Represents the timestamp of the commit.
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcOffsetDateTime commitTimestamp = 5;</code>
     * @param \Wtsvk\EvitaDbClient\Protocol\GrpcOffsetDateTime $var
     * @return $this
     */
    public function setCommitTimestamp($var)
    {
        GPBUtil::checkMessage($var, \Wtsvk\EvitaDbClient\Protocol\GrpcOffsetDateTime::class);
        $this->commitTimestamp = $var;

        return $this;
    }

}

