<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GrpcEntitySchema.proto

namespace Wtsvk\EvitaDbClient\Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Attribute element is a part of the sortable compound. It defines the attribute name, the direction of the
 * sorting and the behaviour of the null values. The attribute name refers to the existing attribute defined in the
 * schema.
 *
 * Generated from protobuf message <code>io.evitadb.externalApi.grpc.generated.GrpcAttributeElement</code>
 */
class GrpcAttributeElement extends \Google\Protobuf\Internal\Message
{
    /**
     * Name of the existing attribute in the same schema.
     *
     * Generated from protobuf field <code>string attributeName = 1;</code>
     */
    protected $attributeName = '';
    /**
     * Direction of the sorting.
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcOrderDirection direction = 2;</code>
     */
    protected $direction = 0;
    /**
     * Behaviour of the null values.
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcOrderBehaviour behaviour = 3;</code>
     */
    protected $behaviour = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $attributeName
     *           Name of the existing attribute in the same schema.
     *     @type int $direction
     *           Direction of the sorting.
     *     @type int $behaviour
     *           Behaviour of the null values.
     * }
     */
    public function __construct($data = NULL) {
        \Wtsvk\EvitaDbClient\Protocol\GPBMetadata\GrpcEntitySchema::initOnce();
        parent::__construct($data);
    }

    /**
     * Name of the existing attribute in the same schema.
     *
     * Generated from protobuf field <code>string attributeName = 1;</code>
     * @return string
     */
    public function getAttributeName()
    {
        return $this->attributeName;
    }

    /**
     * Name of the existing attribute in the same schema.
     *
     * Generated from protobuf field <code>string attributeName = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setAttributeName($var)
    {
        GPBUtil::checkString($var, True);
        $this->attributeName = $var;

        return $this;
    }

    /**
     * Direction of the sorting.
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcOrderDirection direction = 2;</code>
     * @return int
     */
    public function getDirection()
    {
        return $this->direction;
    }

    /**
     * Direction of the sorting.
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcOrderDirection direction = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setDirection($var)
    {
        GPBUtil::checkEnum($var, \Wtsvk\EvitaDbClient\Protocol\GrpcOrderDirection::class);
        $this->direction = $var;

        return $this;
    }

    /**
     * Behaviour of the null values.
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcOrderBehaviour behaviour = 3;</code>
     * @return int
     */
    public function getBehaviour()
    {
        return $this->behaviour;
    }

    /**
     * Behaviour of the null values.
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcOrderBehaviour behaviour = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setBehaviour($var)
    {
        GPBUtil::checkEnum($var, \Wtsvk\EvitaDbClient\Protocol\GrpcOrderBehaviour::class);
        $this->behaviour = $var;

        return $this;
    }

}

