<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GrpcEvitaSessionAPI.proto

namespace Wtsvk\EvitaDbClient\Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Response to a catalog backup request.
 *
 * Generated from protobuf message <code>io.evitadb.externalApi.grpc.generated.GrpcBackupCatalogRequest</code>
 */
class GrpcBackupCatalogRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * The moment in time to which the catalog should be backed up. Might be null for current time.
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcOffsetDateTime pastMoment = 1;</code>
     */
    protected $pastMoment = null;
    /**
     * True, if the WAL should be included in the backup. Use false if you want to restore catalog in exact state as
     * it was at the pastMoment.
     *
     * Generated from protobuf field <code>bool includingWAL = 2;</code>
     */
    protected $includingWAL = false;
    /**
     * precise catalog version to create backup for, or null to create backup for the latest version,
     * when set not null, the pastMoment parameter is ignored
     *
     * Generated from protobuf field <code>.google.protobuf.Int64Value catalogVersion = 3;</code>
     */
    protected $catalogVersion = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Wtsvk\EvitaDbClient\Protocol\GrpcOffsetDateTime $pastMoment
     *           The moment in time to which the catalog should be backed up. Might be null for current time.
     *     @type bool $includingWAL
     *           True, if the WAL should be included in the backup. Use false if you want to restore catalog in exact state as
     *           it was at the pastMoment.
     *     @type \Google\Protobuf\Int64Value $catalogVersion
     *           precise catalog version to create backup for, or null to create backup for the latest version,
     *           when set not null, the pastMoment parameter is ignored
     * }
     */
    public function __construct($data = NULL) {
        \Wtsvk\EvitaDbClient\Protocol\GPBMetadata\GrpcEvitaSessionAPI::initOnce();
        parent::__construct($data);
    }

    /**
     * The moment in time to which the catalog should be backed up. Might be null for current time.
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcOffsetDateTime pastMoment = 1;</code>
     * @return \Wtsvk\EvitaDbClient\Protocol\GrpcOffsetDateTime|null
     */
    public function getPastMoment()
    {
        return $this->pastMoment;
    }

    public function hasPastMoment()
    {
        return isset($this->pastMoment);
    }

    public function clearPastMoment()
    {
        unset($this->pastMoment);
    }

    /**
     * The moment in time to which the catalog should be backed up. Might be null for current time.
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcOffsetDateTime pastMoment = 1;</code>
     * @param \Wtsvk\EvitaDbClient\Protocol\GrpcOffsetDateTime $var
     * @return $this
     */
    public function setPastMoment($var)
    {
        GPBUtil::checkMessage($var, \Wtsvk\EvitaDbClient\Protocol\GrpcOffsetDateTime::class);
        $this->pastMoment = $var;

        return $this;
    }

    /**
     * True, if the WAL should be included in the backup. Use false if you want to restore catalog in exact state as
     * it was at the pastMoment.
     *
     * Generated from protobuf field <code>bool includingWAL = 2;</code>
     * @return bool
     */
    public function getIncludingWAL()
    {
        return $this->includingWAL;
    }

    /**
     * True, if the WAL should be included in the backup. Use false if you want to restore catalog in exact state as
     * it was at the pastMoment.
     *
     * Generated from protobuf field <code>bool includingWAL = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setIncludingWAL($var)
    {
        GPBUtil::checkBool($var);
        $this->includingWAL = $var;

        return $this;
    }

    /**
     * precise catalog version to create backup for, or null to create backup for the latest version,
     * when set not null, the pastMoment parameter is ignored
     *
     * Generated from protobuf field <code>.google.protobuf.Int64Value catalogVersion = 3;</code>
     * @return \Google\Protobuf\Int64Value|null
     */
    public function getCatalogVersion()
    {
        return $this->catalogVersion;
    }

    public function hasCatalogVersion()
    {
        return isset($this->catalogVersion);
    }

    public function clearCatalogVersion()
    {
        unset($this->catalogVersion);
    }

    /**
     * Returns the unboxed value from <code>getCatalogVersion()</code>

     * precise catalog version to create backup for, or null to create backup for the latest version,
     * when set not null, the pastMoment parameter is ignored
     *
     * Generated from protobuf field <code>.google.protobuf.Int64Value catalogVersion = 3;</code>
     * @return int|string|null
     */
    public function getCatalogVersionUnwrapped()
    {
        return $this->readWrapperValue("catalogVersion");
    }

    /**
     * precise catalog version to create backup for, or null to create backup for the latest version,
     * when set not null, the pastMoment parameter is ignored
     *
     * Generated from protobuf field <code>.google.protobuf.Int64Value catalogVersion = 3;</code>
     * @param \Google\Protobuf\Int64Value $var
     * @return $this
     */
    public function setCatalogVersion($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Int64Value::class);
        $this->catalogVersion = $var;

        return $this;
    }

    /**
     * Sets the field by wrapping a primitive type in a Google\Protobuf\Int64Value object.

     * precise catalog version to create backup for, or null to create backup for the latest version,
     * when set not null, the pastMoment parameter is ignored
     *
     * Generated from protobuf field <code>.google.protobuf.Int64Value catalogVersion = 3;</code>
     * @param int|string|null $var
     * @return $this
     */
    public function setCatalogVersionUnwrapped($var)
    {
        $this->writeWrapperValue("catalogVersion", $var);
        return $this;}

}

