<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GrpcEvitaSessionAPI.proto

namespace Wtsvk\EvitaDbClient\Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Request for defining the schema of a new entity type.
 *
 * Generated from protobuf message <code>io.evitadb.externalApi.grpc.generated.GrpcDefineEntitySchemaRequest</code>
 */
class GrpcDefineEntitySchemaRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * The schema of the new entity type.
     *
     * Generated from protobuf field <code>string entityType = 1;</code>
     */
    protected $entityType = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $entityType
     *           The schema of the new entity type.
     * }
     */
    public function __construct($data = NULL) {
        \Wtsvk\EvitaDbClient\Protocol\GPBMetadata\GrpcEvitaSessionAPI::initOnce();
        parent::__construct($data);
    }

    /**
     * The schema of the new entity type.
     *
     * Generated from protobuf field <code>string entityType = 1;</code>
     * @return string
     */
    public function getEntityType()
    {
        return $this->entityType;
    }

    /**
     * The schema of the new entity type.
     *
     * Generated from protobuf field <code>string entityType = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setEntityType($var)
    {
        GPBUtil::checkString($var, True);
        $this->entityType = $var;

        return $this;
    }

}

