<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GrpcEvitaAPI.proto

namespace Wtsvk\EvitaDbClient\Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Request to make a catalog mutable.
 *
 * Generated from protobuf message <code>io.evitadb.externalApi.grpc.generated.GrpcMakeCatalogMutableRequest</code>
 */
class GrpcMakeCatalogMutableRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Name of the catalog to make mutable.
     *
     * Generated from protobuf field <code>string catalogName = 1;</code>
     */
    protected $catalogName = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $catalogName
     *           Name of the catalog to make mutable.
     * }
     */
    public function __construct($data = NULL) {
        \Wtsvk\EvitaDbClient\Protocol\GPBMetadata\GrpcEvitaAPI::initOnce();
        parent::__construct($data);
    }

    /**
     * Name of the catalog to make mutable.
     *
     * Generated from protobuf field <code>string catalogName = 1;</code>
     * @return string
     */
    public function getCatalogName()
    {
        return $this->catalogName;
    }

    /**
     * Name of the catalog to make mutable.
     *
     * Generated from protobuf field <code>string catalogName = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setCatalogName($var)
    {
        GPBUtil::checkString($var, True);
        $this->catalogName = $var;

        return $this;
    }

}

