<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GrpcEvitaSessionAPI.proto

namespace Wtsvk\EvitaDbClient\Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Request for deleting an entity that should return the restored entity with required richness.
 *
 * Generated from protobuf message <code>io.evitadb.externalApi.grpc.generated.GrpcRestoreEntityRequest</code>
 */
class GrpcRestoreEntityRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Entity type of the entity to be restored.
     *
     * Generated from protobuf field <code>string entityType = 1;</code>
     */
    protected $entityType = '';
    /**
     * Primary key of the entity to be restored.
     *
     * Generated from protobuf field <code>.google.protobuf.Int32Value primaryKey = 2;</code>
     */
    protected $primaryKey = null;
    /**
     * The string part of the parametrised query require part.
     *
     * Generated from protobuf field <code>string require = 3;</code>
     */
    protected $require = '';
    /**
     * The positional query parameters.
     *
     * Generated from protobuf field <code>repeated .io.evitadb.externalApi.grpc.generated.GrpcQueryParam positionalQueryParams = 4;</code>
     */
    private $positionalQueryParams;
    /**
     * The named query parameters.
     *
     * Generated from protobuf field <code>map<string, .io.evitadb.externalApi.grpc.generated.GrpcQueryParam> namedQueryParams = 5;</code>
     */
    private $namedQueryParams;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $entityType
     *           Entity type of the entity to be restored.
     *     @type \Google\Protobuf\Int32Value $primaryKey
     *           Primary key of the entity to be restored.
     *     @type string $require
     *           The string part of the parametrised query require part.
     *     @type array<\Wtsvk\EvitaDbClient\Protocol\GrpcQueryParam>|\Google\Protobuf\Internal\RepeatedField $positionalQueryParams
     *           The positional query parameters.
     *     @type array|\Google\Protobuf\Internal\MapField $namedQueryParams
     *           The named query parameters.
     * }
     */
    public function __construct($data = NULL) {
        \Wtsvk\EvitaDbClient\Protocol\GPBMetadata\GrpcEvitaSessionAPI::initOnce();
        parent::__construct($data);
    }

    /**
     * Entity type of the entity to be restored.
     *
     * Generated from protobuf field <code>string entityType = 1;</code>
     * @return string
     */
    public function getEntityType()
    {
        return $this->entityType;
    }

    /**
     * Entity type of the entity to be restored.
     *
     * Generated from protobuf field <code>string entityType = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setEntityType($var)
    {
        GPBUtil::checkString($var, True);
        $this->entityType = $var;

        return $this;
    }

    /**
     * Primary key of the entity to be restored.
     *
     * Generated from protobuf field <code>.google.protobuf.Int32Value primaryKey = 2;</code>
     * @return \Google\Protobuf\Int32Value|null
     */
    public function getPrimaryKey()
    {
        return $this->primaryKey;
    }

    public function hasPrimaryKey()
    {
        return isset($this->primaryKey);
    }

    public function clearPrimaryKey()
    {
        unset($this->primaryKey);
    }

    /**
     * Returns the unboxed value from <code>getPrimaryKey()</code>

     * Primary key of the entity to be restored.
     *
     * Generated from protobuf field <code>.google.protobuf.Int32Value primaryKey = 2;</code>
     * @return int|null
     */
    public function getPrimaryKeyUnwrapped()
    {
        return $this->readWrapperValue("primaryKey");
    }

    /**
     * Primary key of the entity to be restored.
     *
     * Generated from protobuf field <code>.google.protobuf.Int32Value primaryKey = 2;</code>
     * @param \Google\Protobuf\Int32Value $var
     * @return $this
     */
    public function setPrimaryKey($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Int32Value::class);
        $this->primaryKey = $var;

        return $this;
    }

    /**
     * Sets the field by wrapping a primitive type in a Google\Protobuf\Int32Value object.

     * Primary key of the entity to be restored.
     *
     * Generated from protobuf field <code>.google.protobuf.Int32Value primaryKey = 2;</code>
     * @param int|null $var
     * @return $this
     */
    public function setPrimaryKeyUnwrapped($var)
    {
        $this->writeWrapperValue("primaryKey", $var);
        return $this;}

    /**
     * The string part of the parametrised query require part.
     *
     * Generated from protobuf field <code>string require = 3;</code>
     * @return string
     */
    public function getRequire()
    {
        return $this->require;
    }

    /**
     * The string part of the parametrised query require part.
     *
     * Generated from protobuf field <code>string require = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setRequire($var)
    {
        GPBUtil::checkString($var, True);
        $this->require = $var;

        return $this;
    }

    /**
     * The positional query parameters.
     *
     * Generated from protobuf field <code>repeated .io.evitadb.externalApi.grpc.generated.GrpcQueryParam positionalQueryParams = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getPositionalQueryParams()
    {
        return $this->positionalQueryParams;
    }

    /**
     * The positional query parameters.
     *
     * Generated from protobuf field <code>repeated .io.evitadb.externalApi.grpc.generated.GrpcQueryParam positionalQueryParams = 4;</code>
     * @param array<\Wtsvk\EvitaDbClient\Protocol\GrpcQueryParam>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setPositionalQueryParams($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Wtsvk\EvitaDbClient\Protocol\GrpcQueryParam::class);
        $this->positionalQueryParams = $arr;

        return $this;
    }

    /**
     * The named query parameters.
     *
     * Generated from protobuf field <code>map<string, .io.evitadb.externalApi.grpc.generated.GrpcQueryParam> namedQueryParams = 5;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getNamedQueryParams()
    {
        return $this->namedQueryParams;
    }

    /**
     * The named query parameters.
     *
     * Generated from protobuf field <code>map<string, .io.evitadb.externalApi.grpc.generated.GrpcQueryParam> namedQueryParams = 5;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setNamedQueryParams($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::MESSAGE, \Wtsvk\EvitaDbClient\Protocol\GrpcQueryParam::class);
        $this->namedQueryParams = $arr;

        return $this;
    }

}

