<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GrpcAttributeSchemaMutations.proto

namespace Wtsvk\EvitaDbClient\Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Mutation is responsible for setting value to a `AttributeSchema.defaultValue` in `EntitySchema`.
 * Mutation can be used for altering also the existing `AttributeSchema` or GlobalAttributeSchema` alone.
 *
 * Generated from protobuf message <code>io.evitadb.externalApi.grpc.generated.GrpcModifyAttributeSchemaDefaultValueMutation</code>
 */
class GrpcModifyAttributeSchemaDefaultValueMutation extends \Google\Protobuf\Internal\Message
{
    /**
     * Name of the attribute the mutation is targeting.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     */
    protected $name = '';
    /**
     * Default value is used when the entity is created without this attribute specified. Default values allow to pass
     * non-null checks even if no attributes of such name are specified.
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcEvitaValue defaultValue = 2;</code>
     */
    protected $defaultValue = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *           Name of the attribute the mutation is targeting.
     *     @type \Wtsvk\EvitaDbClient\Protocol\GrpcEvitaValue $defaultValue
     *           Default value is used when the entity is created without this attribute specified. Default values allow to pass
     *           non-null checks even if no attributes of such name are specified.
     * }
     */
    public function __construct($data = NULL) {
        \Wtsvk\EvitaDbClient\Protocol\GPBMetadata\GrpcAttributeSchemaMutations::initOnce();
        parent::__construct($data);
    }

    /**
     * Name of the attribute the mutation is targeting.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Name of the attribute the mutation is targeting.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Default value is used when the entity is created without this attribute specified. Default values allow to pass
     * non-null checks even if no attributes of such name are specified.
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcEvitaValue defaultValue = 2;</code>
     * @return \Wtsvk\EvitaDbClient\Protocol\GrpcEvitaValue|null
     */
    public function getDefaultValue()
    {
        return $this->defaultValue;
    }

    public function hasDefaultValue()
    {
        return isset($this->defaultValue);
    }

    public function clearDefaultValue()
    {
        unset($this->defaultValue);
    }

    /**
     * Default value is used when the entity is created without this attribute specified. Default values allow to pass
     * non-null checks even if no attributes of such name are specified.
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcEvitaValue defaultValue = 2;</code>
     * @param \Wtsvk\EvitaDbClient\Protocol\GrpcEvitaValue $var
     * @return $this
     */
    public function setDefaultValue($var)
    {
        GPBUtil::checkMessage($var, \Wtsvk\EvitaDbClient\Protocol\GrpcEvitaValue::class);
        $this->defaultValue = $var;

        return $this;
    }

}

