<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GrpcEvitaAPI.proto

namespace Wtsvk\EvitaDbClient\Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Response to a server status request.
 *
 * Generated from protobuf message <code>io.evitadb.externalApi.grpc.generated.GrpcReadyResponse</code>
 */
class GrpcReadyResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Always true when returned
     *
     * Generated from protobuf field <code>bool ready = 1;</code>
     */
    protected $ready = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $ready
     *           Always true when returned
     * }
     */
    public function __construct($data = NULL) {
        \Wtsvk\EvitaDbClient\Protocol\GPBMetadata\GrpcEvitaAPI::initOnce();
        parent::__construct($data);
    }

    /**
     * Always true when returned
     *
     * Generated from protobuf field <code>bool ready = 1;</code>
     * @return bool
     */
    public function getReady()
    {
        return $this->ready;
    }

    /**
     * Always true when returned
     *
     * Generated from protobuf field <code>bool ready = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setReady($var)
    {
        GPBUtil::checkBool($var);
        $this->ready = $var;

        return $this;
    }

}

