<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GrpcEnums.proto

namespace Wtsvk\EvitaDbClient\Protocol;

use UnexpectedValueException;

/**
 * Defines the behaviour of null values in an attribute element of the sortable attribute compound.
 *
 * Protobuf type <code>io.evitadb.externalApi.grpc.generated.GrpcOrderBehaviour</code>
 */
class GrpcOrderBehaviour
{
    /**
     * Null values are sorted before non-null values.
     *
     * Generated from protobuf enum <code>NULLS_FIRST = 0;</code>
     */
    const NULLS_FIRST = 0;
    /**
     * Null values are sorted after non-null values.
     *
     * Generated from protobuf enum <code>NULLS_LAST = 1;</code>
     */
    const NULLS_LAST = 1;

    private static $valueToName = [
        self::NULLS_FIRST => 'NULLS_FIRST',
        self::NULLS_LAST => 'NULLS_LAST',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

