<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GrpcEngineMutation.proto

namespace Wtsvk\EvitaDbClient\Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Mutation is responsible for renaming an existing CatalogSchema.
 *
 * Generated from protobuf message <code>io.evitadb.externalApi.grpc.generated.GrpcModifyCatalogSchemaNameMutation</code>
 */
class GrpcModifyCatalogSchemaNameMutation extends \Google\Protobuf\Internal\Message
{
    /**
     * Name of the catalog schema the mutation is targeting (will rename).
     *
     * Generated from protobuf field <code>string catalogName = 1;</code>
     */
    protected $catalogName = '';
    /**
     * The new name of the catalog schema.
     *
     * Generated from protobuf field <code>string newCatalogName = 2;</code>
     */
    protected $newCatalogName = '';
    /**
     * Flag indicating whether to replace the existing catalog or just to rename it.
     *
     * Generated from protobuf field <code>bool overwriteTarget = 3;</code>
     */
    protected $overwriteTarget = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $catalogName
     *           Name of the catalog schema the mutation is targeting (will rename).
     *     @type string $newCatalogName
     *           The new name of the catalog schema.
     *     @type bool $overwriteTarget
     *           Flag indicating whether to replace the existing catalog or just to rename it.
     * }
     */
    public function __construct($data = NULL) {
        \Wtsvk\EvitaDbClient\Protocol\GPBMetadata\GrpcEngineMutation::initOnce();
        parent::__construct($data);
    }

    /**
     * Name of the catalog schema the mutation is targeting (will rename).
     *
     * Generated from protobuf field <code>string catalogName = 1;</code>
     * @return string
     */
    public function getCatalogName()
    {
        return $this->catalogName;
    }

    /**
     * Name of the catalog schema the mutation is targeting (will rename).
     *
     * Generated from protobuf field <code>string catalogName = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setCatalogName($var)
    {
        GPBUtil::checkString($var, True);
        $this->catalogName = $var;

        return $this;
    }

    /**
     * The new name of the catalog schema.
     *
     * Generated from protobuf field <code>string newCatalogName = 2;</code>
     * @return string
     */
    public function getNewCatalogName()
    {
        return $this->newCatalogName;
    }

    /**
     * The new name of the catalog schema.
     *
     * Generated from protobuf field <code>string newCatalogName = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setNewCatalogName($var)
    {
        GPBUtil::checkString($var, True);
        $this->newCatalogName = $var;

        return $this;
    }

    /**
     * Flag indicating whether to replace the existing catalog or just to rename it.
     *
     * Generated from protobuf field <code>bool overwriteTarget = 3;</code>
     * @return bool
     */
    public function getOverwriteTarget()
    {
        return $this->overwriteTarget;
    }

    /**
     * Flag indicating whether to replace the existing catalog or just to rename it.
     *
     * Generated from protobuf field <code>bool overwriteTarget = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setOverwriteTarget($var)
    {
        GPBUtil::checkBool($var);
        $this->overwriteTarget = $var;

        return $this;
    }

}

