<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GrpcEvitaDataTypes.proto

namespace Wtsvk\EvitaDbClient\Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Wrapper for representing an array of Currencies.
 *
 * Generated from protobuf message <code>io.evitadb.externalApi.grpc.generated.GrpcCurrencyArray</code>
 */
class GrpcCurrencyArray extends \Google\Protobuf\Internal\Message
{
    /**
     * Value that supports storing a Currency array.
     *
     * Generated from protobuf field <code>repeated .io.evitadb.externalApi.grpc.generated.GrpcCurrency value = 1;</code>
     */
    private $value;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\Wtsvk\EvitaDbClient\Protocol\GrpcCurrency>|\Google\Protobuf\Internal\RepeatedField $value
     *           Value that supports storing a Currency array.
     * }
     */
    public function __construct($data = NULL) {
        \Wtsvk\EvitaDbClient\Protocol\GPBMetadata\GrpcEvitaDataTypes::initOnce();
        parent::__construct($data);
    }

    /**
     * Value that supports storing a Currency array.
     *
     * Generated from protobuf field <code>repeated .io.evitadb.externalApi.grpc.generated.GrpcCurrency value = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getValue()
    {
        return $this->value;
    }

    /**
     * Value that supports storing a Currency array.
     *
     * Generated from protobuf field <code>repeated .io.evitadb.externalApi.grpc.generated.GrpcCurrency value = 1;</code>
     * @param array<\Wtsvk\EvitaDbClient\Protocol\GrpcCurrency>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setValue($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Wtsvk\EvitaDbClient\Protocol\GrpcCurrency::class);
        $this->value = $arr;

        return $this;
    }

}

