<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GrpcEvitaSessionAPI.proto

namespace Wtsvk\EvitaDbClient\Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Response to GetEntity request.
 *
 * Generated from protobuf message <code>io.evitadb.externalApi.grpc.generated.GrpcEntityResponse</code>
 */
class GrpcEntityResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * The found entity.
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcSealedEntity entity = 1;</code>
     */
    protected $entity = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Wtsvk\EvitaDbClient\Protocol\GrpcSealedEntity $entity
     *           The found entity.
     * }
     */
    public function __construct($data = NULL) {
        \Wtsvk\EvitaDbClient\Protocol\GPBMetadata\GrpcEvitaSessionAPI::initOnce();
        parent::__construct($data);
    }

    /**
     * The found entity.
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcSealedEntity entity = 1;</code>
     * @return \Wtsvk\EvitaDbClient\Protocol\GrpcSealedEntity|null
     */
    public function getEntity()
    {
        return $this->entity;
    }

    public function hasEntity()
    {
        return isset($this->entity);
    }

    public function clearEntity()
    {
        unset($this->entity);
    }

    /**
     * The found entity.
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcSealedEntity entity = 1;</code>
     * @param \Wtsvk\EvitaDbClient\Protocol\GrpcSealedEntity $var
     * @return $this
     */
    public function setEntity($var)
    {
        GPBUtil::checkMessage($var, \Wtsvk\EvitaDbClient\Protocol\GrpcSealedEntity::class);
        $this->entity = $var;

        return $this;
    }

}

