<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GrpcEvitaSessionAPI.proto

namespace Wtsvk\EvitaDbClient\Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Response to UpsertEntity request. The used field is decided by the require block in the query.
 *
 * Generated from protobuf message <code>io.evitadb.externalApi.grpc.generated.GrpcUpsertEntityResponse</code>
 */
class GrpcUpsertEntityResponse extends \Google\Protobuf\Internal\Message
{
    protected $response;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Wtsvk\EvitaDbClient\Protocol\GrpcEntityReference $entityReference
     *           The upserted entity reference.
     *     @type \Wtsvk\EvitaDbClient\Protocol\GrpcSealedEntity $entity
     *           The upserted entity.
     *     @type \Wtsvk\EvitaDbClient\Protocol\GrpcEntityReferenceWithAssignedPrimaryKeys $entityReferenceWithAssignedPrimaryKeys
     *           The upserted entity reference with reassigned primary keys
     * }
     */
    public function __construct($data = NULL) {
        \Wtsvk\EvitaDbClient\Protocol\GPBMetadata\GrpcEvitaSessionAPI::initOnce();
        parent::__construct($data);
    }

    /**
     * The upserted entity reference.
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcEntityReference entityReference = 1;</code>
     * @return \Wtsvk\EvitaDbClient\Protocol\GrpcEntityReference|null
     */
    public function getEntityReference()
    {
        return $this->readOneof(1);
    }

    public function hasEntityReference()
    {
        return $this->hasOneof(1);
    }

    /**
     * The upserted entity reference.
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcEntityReference entityReference = 1;</code>
     * @param \Wtsvk\EvitaDbClient\Protocol\GrpcEntityReference $var
     * @return $this
     */
    public function setEntityReference($var)
    {
        GPBUtil::checkMessage($var, \Wtsvk\EvitaDbClient\Protocol\GrpcEntityReference::class);
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * The upserted entity.
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcSealedEntity entity = 2;</code>
     * @return \Wtsvk\EvitaDbClient\Protocol\GrpcSealedEntity|null
     */
    public function getEntity()
    {
        return $this->readOneof(2);
    }

    public function hasEntity()
    {
        return $this->hasOneof(2);
    }

    /**
     * The upserted entity.
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcSealedEntity entity = 2;</code>
     * @param \Wtsvk\EvitaDbClient\Protocol\GrpcSealedEntity $var
     * @return $this
     */
    public function setEntity($var)
    {
        GPBUtil::checkMessage($var, \Wtsvk\EvitaDbClient\Protocol\GrpcSealedEntity::class);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * The upserted entity reference with reassigned primary keys
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcEntityReferenceWithAssignedPrimaryKeys entityReferenceWithAssignedPrimaryKeys = 3;</code>
     * @return \Wtsvk\EvitaDbClient\Protocol\GrpcEntityReferenceWithAssignedPrimaryKeys|null
     */
    public function getEntityReferenceWithAssignedPrimaryKeys()
    {
        return $this->readOneof(3);
    }

    public function hasEntityReferenceWithAssignedPrimaryKeys()
    {
        return $this->hasOneof(3);
    }

    /**
     * The upserted entity reference with reassigned primary keys
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcEntityReferenceWithAssignedPrimaryKeys entityReferenceWithAssignedPrimaryKeys = 3;</code>
     * @param \Wtsvk\EvitaDbClient\Protocol\GrpcEntityReferenceWithAssignedPrimaryKeys $var
     * @return $this
     */
    public function setEntityReferenceWithAssignedPrimaryKeys($var)
    {
        GPBUtil::checkMessage($var, \Wtsvk\EvitaDbClient\Protocol\GrpcEntityReferenceWithAssignedPrimaryKeys::class);
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getResponse()
    {
        return $this->whichOneof("response");
    }

}

