<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GrpcEvitaManagementAPI.proto

namespace Wtsvk\EvitaDbClient\Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Request to restore a catalog.
 *
 * Generated from protobuf message <code>io.evitadb.externalApi.grpc.generated.GrpcRestoreCatalogRequest</code>
 */
class GrpcRestoreCatalogRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Name of the catalog where the backup will be restored
     * The name must not clash with any of existing catalogs
     *
     * Generated from protobuf field <code>string catalogName = 1;</code>
     */
    protected $catalogName = '';
    /**
     * Binary contents of the backup file.
     *
     * Generated from protobuf field <code>bytes backupFile = 2;</code>
     */
    protected $backupFile = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $catalogName
     *           Name of the catalog where the backup will be restored
     *           The name must not clash with any of existing catalogs
     *     @type string $backupFile
     *           Binary contents of the backup file.
     * }
     */
    public function __construct($data = NULL) {
        \Wtsvk\EvitaDbClient\Protocol\GPBMetadata\GrpcEvitaManagementAPI::initOnce();
        parent::__construct($data);
    }

    /**
     * Name of the catalog where the backup will be restored
     * The name must not clash with any of existing catalogs
     *
     * Generated from protobuf field <code>string catalogName = 1;</code>
     * @return string
     */
    public function getCatalogName()
    {
        return $this->catalogName;
    }

    /**
     * Name of the catalog where the backup will be restored
     * The name must not clash with any of existing catalogs
     *
     * Generated from protobuf field <code>string catalogName = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setCatalogName($var)
    {
        GPBUtil::checkString($var, True);
        $this->catalogName = $var;

        return $this;
    }

    /**
     * Binary contents of the backup file.
     *
     * Generated from protobuf field <code>bytes backupFile = 2;</code>
     * @return string
     */
    public function getBackupFile()
    {
        return $this->backupFile;
    }

    /**
     * Binary contents of the backup file.
     *
     * Generated from protobuf field <code>bytes backupFile = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setBackupFile($var)
    {
        GPBUtil::checkString($var, False);
        $this->backupFile = $var;

        return $this;
    }

}

