<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GrpcTrafficRecording.proto

namespace Wtsvk\EvitaDbClient\Protocol;

use UnexpectedValueException;

/**
 * List of all possible traffic recording types.
 *
 * Protobuf type <code>io.evitadb.externalApi.grpc.generated.GrpcTrafficRecordingType</code>
 */
class GrpcTrafficRecordingType
{
    /**
     * evitaDB session opened.
     *
     * Generated from protobuf enum <code>TRAFFIC_RECORDING_SESSION_START = 0;</code>
     */
    const TRAFFIC_RECORDING_SESSION_START = 0;
    /**
     ** evitaDB session closed.
     *
     * Generated from protobuf enum <code>TRAFFIC_RECORDING_SESSION_FINISH = 1;</code>
     */
    const TRAFFIC_RECORDING_SESSION_FINISH = 1;
    /**
     * Query received via. API from the client - container contains original string of the client query.
     * API might call multiple queries related to the same source query.
     *
     * Generated from protobuf enum <code>TRAFFIC_RECORDING_SOURCE_QUERY = 2;</code>
     */
    const TRAFFIC_RECORDING_SOURCE_QUERY = 2;
    /**
     * Query received via. API from the client is finalized and sent to the client. Container contains the final
     * statistics aggregated over all operations related to the source query.
     *
     * Generated from protobuf enum <code>TRAFFIC_RECORDING_SOURCE_QUERY_STATISTICS = 3;</code>
     */
    const TRAFFIC_RECORDING_SOURCE_QUERY_STATISTICS = 3;
    /**
     * Internal evitaDB query (evitaQL) was executed.
     *
     * Generated from protobuf enum <code>TRAFFIC_RECORDING_QUERY = 4;</code>
     */
    const TRAFFIC_RECORDING_QUERY = 4;
    /**
     * Internal call to retrieve single evitaDB entity. Record is not created for entities fetched as a part of
     * a query.
     *
     * Generated from protobuf enum <code>TRAFFIC_RECORDING_FETCH = 5;</code>
     */
    const TRAFFIC_RECORDING_FETCH = 5;
    /**
     * Internal call to enrich contents of the evitaDB entity.
     *
     * Generated from protobuf enum <code>TRAFFIC_RECORDING_ENRICHMENT = 6;</code>
     */
    const TRAFFIC_RECORDING_ENRICHMENT = 6;
    /**
     * Internal call to mutate the evitaDB entity or catalog schema.
     *
     * Generated from protobuf enum <code>TRAFFIC_RECORDING_MUTATION = 7;</code>
     */
    const TRAFFIC_RECORDING_MUTATION = 7;

    private static $valueToName = [
        self::TRAFFIC_RECORDING_SESSION_START => 'TRAFFIC_RECORDING_SESSION_START',
        self::TRAFFIC_RECORDING_SESSION_FINISH => 'TRAFFIC_RECORDING_SESSION_FINISH',
        self::TRAFFIC_RECORDING_SOURCE_QUERY => 'TRAFFIC_RECORDING_SOURCE_QUERY',
        self::TRAFFIC_RECORDING_SOURCE_QUERY_STATISTICS => 'TRAFFIC_RECORDING_SOURCE_QUERY_STATISTICS',
        self::TRAFFIC_RECORDING_QUERY => 'TRAFFIC_RECORDING_QUERY',
        self::TRAFFIC_RECORDING_FETCH => 'TRAFFIC_RECORDING_FETCH',
        self::TRAFFIC_RECORDING_ENRICHMENT => 'TRAFFIC_RECORDING_ENRICHMENT',
        self::TRAFFIC_RECORDING_MUTATION => 'TRAFFIC_RECORDING_MUTATION',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

