<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GrpcAssociatedDataSchemaMutations.proto

namespace Wtsvk\EvitaDbClient\Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Mutation is responsible for setting value to a `AssociatedDataSchema.nullable` in `EntitySchema`.
 * Mutation can be used for altering also the existing `AssociatedDataSchema` alone.
 *
 * Generated from protobuf message <code>io.evitadb.externalApi.grpc.generated.GrpcSetAssociatedDataSchemaNullableMutation</code>
 */
class GrpcSetAssociatedDataSchemaNullableMutation extends \Google\Protobuf\Internal\Message
{
    /**
     * Contains unique name of the model. Case-sensitive. Distinguishes one model item from another
     * within single entity instance.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     */
    protected $name = '';
    /**
     * When associated data is nullable, its values may be missing in the entities. Otherwise, the system will enforce
     * non-null checks upon upserting of the entity.
     *
     * Generated from protobuf field <code>bool nullable = 2;</code>
     */
    protected $nullable = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *           Contains unique name of the model. Case-sensitive. Distinguishes one model item from another
     *           within single entity instance.
     *     @type bool $nullable
     *           When associated data is nullable, its values may be missing in the entities. Otherwise, the system will enforce
     *           non-null checks upon upserting of the entity.
     * }
     */
    public function __construct($data = NULL) {
        \Wtsvk\EvitaDbClient\Protocol\GPBMetadata\GrpcAssociatedDataSchemaMutations::initOnce();
        parent::__construct($data);
    }

    /**
     * Contains unique name of the model. Case-sensitive. Distinguishes one model item from another
     * within single entity instance.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Contains unique name of the model. Case-sensitive. Distinguishes one model item from another
     * within single entity instance.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * When associated data is nullable, its values may be missing in the entities. Otherwise, the system will enforce
     * non-null checks upon upserting of the entity.
     *
     * Generated from protobuf field <code>bool nullable = 2;</code>
     * @return bool
     */
    public function getNullable()
    {
        return $this->nullable;
    }

    /**
     * When associated data is nullable, its values may be missing in the entities. Otherwise, the system will enforce
     * non-null checks upon upserting of the entity.
     *
     * Generated from protobuf field <code>bool nullable = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setNullable($var)
    {
        GPBUtil::checkBool($var);
        $this->nullable = $var;

        return $this;
    }

}

