<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GrpcEvitaManagementAPI.proto

namespace Wtsvk\EvitaDbClient\Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Response to a server status request.
 *
 * Generated from protobuf message <code>io.evitadb.externalApi.grpc.generated.GrpcEvitaServerStatusResponse</code>
 */
class GrpcEvitaServerStatusResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Version of evitaDB server taken from the MANIFEST.MF file
     *
     * Generated from protobuf field <code>string version = 1;</code>
     */
    protected $version = '';
    /**
     * Date and time when the server was started
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcOffsetDateTime startedAt = 2;</code>
     */
    protected $startedAt = null;
    /**
     * Duration of time since the server was started (seconds)
     *
     * Generated from protobuf field <code>int64 uptime = 3;</code>
     */
    protected $uptime = 0;
    /**
     * Unique identifier of the server instance
     *
     * Generated from protobuf field <code>string instanceId = 4;</code>
     */
    protected $instanceId = '';
    /**
     * Number of corrupted catalogs
     *
     * Generated from protobuf field <code>int32 catalogsCorrupted = 5;</code>
     */
    protected $catalogsCorrupted = 0;
    /**
     * Number of catalogs that are active and has been successfully loaded, renamed to `catalogsActive`
     *
     * Generated from protobuf field <code>int32 catalogsOk = 6 [deprecated = true];</code>
     * @deprecated
     */
    protected $catalogsOk = 0;
    /**
     * Health problems
     *
     * Generated from protobuf field <code>repeated .io.evitadb.externalApi.grpc.generated.GrpcHealthProblem healthProblems = 7;</code>
     */
    private $healthProblems;
    /**
     * Overall readiness of the evitaDB server
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcReadiness readiness = 8;</code>
     */
    protected $readiness = 0;
    /**
     * Information about all available APIs
     *
     * Generated from protobuf field <code>map<string, .io.evitadb.externalApi.grpc.generated.GrpcApiStatus> api = 9;</code>
     */
    private $api;
    /**
     * Flag indicating that the server is in read-only mode
     *
     * Generated from protobuf field <code>bool readOnly = 10;</code>
     */
    protected $readOnly = false;
    /**
     * Number of catalogs that are active and has been successfully loaded
     *
     * Generated from protobuf field <code>int32 catalogsActive = 11;</code>
     */
    protected $catalogsActive = 0;
    /**
     * Number of inactive catalogs
     *
     * Generated from protobuf field <code>int32 catalogsInactive = 12;</code>
     */
    protected $catalogsInactive = 0;
    /**
     * The version of the current evitaDB server engine state (change in engine state).
     *
     * Generated from protobuf field <code>int64 engineVersion = 13;</code>
     */
    protected $engineVersion = 0;
    /**
     * The date and time when the current engine version was introduced (last engine level change occurred).
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcOffsetDateTime introducedAt = 14;</code>
     */
    protected $introducedAt = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $version
     *           Version of evitaDB server taken from the MANIFEST.MF file
     *     @type \Wtsvk\EvitaDbClient\Protocol\GrpcOffsetDateTime $startedAt
     *           Date and time when the server was started
     *     @type int|string $uptime
     *           Duration of time since the server was started (seconds)
     *     @type string $instanceId
     *           Unique identifier of the server instance
     *     @type int $catalogsCorrupted
     *           Number of corrupted catalogs
     *     @type int $catalogsOk
     *           Number of catalogs that are active and has been successfully loaded, renamed to `catalogsActive`
     *     @type array<int>|\Google\Protobuf\Internal\RepeatedField $healthProblems
     *           Health problems
     *     @type int $readiness
     *           Overall readiness of the evitaDB server
     *     @type array|\Google\Protobuf\Internal\MapField $api
     *           Information about all available APIs
     *     @type bool $readOnly
     *           Flag indicating that the server is in read-only mode
     *     @type int $catalogsActive
     *           Number of catalogs that are active and has been successfully loaded
     *     @type int $catalogsInactive
     *           Number of inactive catalogs
     *     @type int|string $engineVersion
     *           The version of the current evitaDB server engine state (change in engine state).
     *     @type \Wtsvk\EvitaDbClient\Protocol\GrpcOffsetDateTime $introducedAt
     *           The date and time when the current engine version was introduced (last engine level change occurred).
     * }
     */
    public function __construct($data = NULL) {
        \Wtsvk\EvitaDbClient\Protocol\GPBMetadata\GrpcEvitaManagementAPI::initOnce();
        parent::__construct($data);
    }

    /**
     * Version of evitaDB server taken from the MANIFEST.MF file
     *
     * Generated from protobuf field <code>string version = 1;</code>
     * @return string
     */
    public function getVersion()
    {
        return $this->version;
    }

    /**
     * Version of evitaDB server taken from the MANIFEST.MF file
     *
     * Generated from protobuf field <code>string version = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setVersion($var)
    {
        GPBUtil::checkString($var, True);
        $this->version = $var;

        return $this;
    }

    /**
     * Date and time when the server was started
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcOffsetDateTime startedAt = 2;</code>
     * @return \Wtsvk\EvitaDbClient\Protocol\GrpcOffsetDateTime|null
     */
    public function getStartedAt()
    {
        return $this->startedAt;
    }

    public function hasStartedAt()
    {
        return isset($this->startedAt);
    }

    public function clearStartedAt()
    {
        unset($this->startedAt);
    }

    /**
     * Date and time when the server was started
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcOffsetDateTime startedAt = 2;</code>
     * @param \Wtsvk\EvitaDbClient\Protocol\GrpcOffsetDateTime $var
     * @return $this
     */
    public function setStartedAt($var)
    {
        GPBUtil::checkMessage($var, \Wtsvk\EvitaDbClient\Protocol\GrpcOffsetDateTime::class);
        $this->startedAt = $var;

        return $this;
    }

    /**
     * Duration of time since the server was started (seconds)
     *
     * Generated from protobuf field <code>int64 uptime = 3;</code>
     * @return int|string
     */
    public function getUptime()
    {
        return $this->uptime;
    }

    /**
     * Duration of time since the server was started (seconds)
     *
     * Generated from protobuf field <code>int64 uptime = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUptime($var)
    {
        GPBUtil::checkInt64($var);
        $this->uptime = $var;

        return $this;
    }

    /**
     * Unique identifier of the server instance
     *
     * Generated from protobuf field <code>string instanceId = 4;</code>
     * @return string
     */
    public function getInstanceId()
    {
        return $this->instanceId;
    }

    /**
     * Unique identifier of the server instance
     *
     * Generated from protobuf field <code>string instanceId = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setInstanceId($var)
    {
        GPBUtil::checkString($var, True);
        $this->instanceId = $var;

        return $this;
    }

    /**
     * Number of corrupted catalogs
     *
     * Generated from protobuf field <code>int32 catalogsCorrupted = 5;</code>
     * @return int
     */
    public function getCatalogsCorrupted()
    {
        return $this->catalogsCorrupted;
    }

    /**
     * Number of corrupted catalogs
     *
     * Generated from protobuf field <code>int32 catalogsCorrupted = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setCatalogsCorrupted($var)
    {
        GPBUtil::checkInt32($var);
        $this->catalogsCorrupted = $var;

        return $this;
    }

    /**
     * Number of catalogs that are active and has been successfully loaded, renamed to `catalogsActive`
     *
     * Generated from protobuf field <code>int32 catalogsOk = 6 [deprecated = true];</code>
     * @return int
     * @deprecated
     */
    public function getCatalogsOk()
    {
        @trigger_error('catalogsOk is deprecated.', E_USER_DEPRECATED);
        return $this->catalogsOk;
    }

    /**
     * Number of catalogs that are active and has been successfully loaded, renamed to `catalogsActive`
     *
     * Generated from protobuf field <code>int32 catalogsOk = 6 [deprecated = true];</code>
     * @param int $var
     * @return $this
     * @deprecated
     */
    public function setCatalogsOk($var)
    {
        @trigger_error('catalogsOk is deprecated.', E_USER_DEPRECATED);
        GPBUtil::checkInt32($var);
        $this->catalogsOk = $var;

        return $this;
    }

    /**
     * Health problems
     *
     * Generated from protobuf field <code>repeated .io.evitadb.externalApi.grpc.generated.GrpcHealthProblem healthProblems = 7;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getHealthProblems()
    {
        return $this->healthProblems;
    }

    /**
     * Health problems
     *
     * Generated from protobuf field <code>repeated .io.evitadb.externalApi.grpc.generated.GrpcHealthProblem healthProblems = 7;</code>
     * @param array<int>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setHealthProblems($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::ENUM, \Wtsvk\EvitaDbClient\Protocol\GrpcHealthProblem::class);
        $this->healthProblems = $arr;

        return $this;
    }

    /**
     * Overall readiness of the evitaDB server
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcReadiness readiness = 8;</code>
     * @return int
     */
    public function getReadiness()
    {
        return $this->readiness;
    }

    /**
     * Overall readiness of the evitaDB server
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcReadiness readiness = 8;</code>
     * @param int $var
     * @return $this
     */
    public function setReadiness($var)
    {
        GPBUtil::checkEnum($var, \Wtsvk\EvitaDbClient\Protocol\GrpcReadiness::class);
        $this->readiness = $var;

        return $this;
    }

    /**
     * Information about all available APIs
     *
     * Generated from protobuf field <code>map<string, .io.evitadb.externalApi.grpc.generated.GrpcApiStatus> api = 9;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getApi()
    {
        return $this->api;
    }

    /**
     * Information about all available APIs
     *
     * Generated from protobuf field <code>map<string, .io.evitadb.externalApi.grpc.generated.GrpcApiStatus> api = 9;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setApi($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::MESSAGE, \Wtsvk\EvitaDbClient\Protocol\GrpcApiStatus::class);
        $this->api = $arr;

        return $this;
    }

    /**
     * Flag indicating that the server is in read-only mode
     *
     * Generated from protobuf field <code>bool readOnly = 10;</code>
     * @return bool
     */
    public function getReadOnly()
    {
        return $this->readOnly;
    }

    /**
     * Flag indicating that the server is in read-only mode
     *
     * Generated from protobuf field <code>bool readOnly = 10;</code>
     * @param bool $var
     * @return $this
     */
    public function setReadOnly($var)
    {
        GPBUtil::checkBool($var);
        $this->readOnly = $var;

        return $this;
    }

    /**
     * Number of catalogs that are active and has been successfully loaded
     *
     * Generated from protobuf field <code>int32 catalogsActive = 11;</code>
     * @return int
     */
    public function getCatalogsActive()
    {
        return $this->catalogsActive;
    }

    /**
     * Number of catalogs that are active and has been successfully loaded
     *
     * Generated from protobuf field <code>int32 catalogsActive = 11;</code>
     * @param int $var
     * @return $this
     */
    public function setCatalogsActive($var)
    {
        GPBUtil::checkInt32($var);
        $this->catalogsActive = $var;

        return $this;
    }

    /**
     * Number of inactive catalogs
     *
     * Generated from protobuf field <code>int32 catalogsInactive = 12;</code>
     * @return int
     */
    public function getCatalogsInactive()
    {
        return $this->catalogsInactive;
    }

    /**
     * Number of inactive catalogs
     *
     * Generated from protobuf field <code>int32 catalogsInactive = 12;</code>
     * @param int $var
     * @return $this
     */
    public function setCatalogsInactive($var)
    {
        GPBUtil::checkInt32($var);
        $this->catalogsInactive = $var;

        return $this;
    }

    /**
     * The version of the current evitaDB server engine state (change in engine state).
     *
     * Generated from protobuf field <code>int64 engineVersion = 13;</code>
     * @return int|string
     */
    public function getEngineVersion()
    {
        return $this->engineVersion;
    }

    /**
     * The version of the current evitaDB server engine state (change in engine state).
     *
     * Generated from protobuf field <code>int64 engineVersion = 13;</code>
     * @param int|string $var
     * @return $this
     */
    public function setEngineVersion($var)
    {
        GPBUtil::checkInt64($var);
        $this->engineVersion = $var;

        return $this;
    }

    /**
     * The date and time when the current engine version was introduced (last engine level change occurred).
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcOffsetDateTime introducedAt = 14;</code>
     * @return \Wtsvk\EvitaDbClient\Protocol\GrpcOffsetDateTime|null
     */
    public function getIntroducedAt()
    {
        return $this->introducedAt;
    }

    public function hasIntroducedAt()
    {
        return isset($this->introducedAt);
    }

    public function clearIntroducedAt()
    {
        unset($this->introducedAt);
    }

    /**
     * The date and time when the current engine version was introduced (last engine level change occurred).
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcOffsetDateTime introducedAt = 14;</code>
     * @param \Wtsvk\EvitaDbClient\Protocol\GrpcOffsetDateTime $var
     * @return $this
     */
    public function setIntroducedAt($var)
    {
        GPBUtil::checkMessage($var, \Wtsvk\EvitaDbClient\Protocol\GrpcOffsetDateTime::class);
        $this->introducedAt = $var;

        return $this;
    }

}

