<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GrpcAttributeSchemaMutations.proto

namespace Wtsvk\EvitaDbClient\Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Mutation is responsible for setting value to a `AttributeSchema.type` in `EntitySchema`.
 * Mutation can be used for altering also the existing `AttributeSchema` or `GlobalAttributeSchema` alone.
 *
 * Generated from protobuf message <code>io.evitadb.externalApi.grpc.generated.GrpcModifyAttributeSchemaTypeMutation</code>
 */
class GrpcModifyAttributeSchemaTypeMutation extends \Google\Protobuf\Internal\Message
{
    /**
     * Name of the attribute the mutation is targeting.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     */
    protected $name = '';
    /**
     * Type of the attribute. Must be one of supported data types or its array.
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcEvitaDataType type = 2;</code>
     */
    protected $type = 0;
    /**
     * Determines how many fractional places are important when entities are compared during filtering or sorting.
     *
     * Generated from protobuf field <code>int32 indexedDecimalPlaces = 3;</code>
     */
    protected $indexedDecimalPlaces = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *           Name of the attribute the mutation is targeting.
     *     @type int $type
     *           Type of the attribute. Must be one of supported data types or its array.
     *     @type int $indexedDecimalPlaces
     *           Determines how many fractional places are important when entities are compared during filtering or sorting.
     * }
     */
    public function __construct($data = NULL) {
        \Wtsvk\EvitaDbClient\Protocol\GPBMetadata\GrpcAttributeSchemaMutations::initOnce();
        parent::__construct($data);
    }

    /**
     * Name of the attribute the mutation is targeting.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Name of the attribute the mutation is targeting.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Type of the attribute. Must be one of supported data types or its array.
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcEvitaDataType type = 2;</code>
     * @return int
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Type of the attribute. Must be one of supported data types or its array.
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcEvitaDataType type = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkEnum($var, \Wtsvk\EvitaDbClient\Protocol\GrpcEvitaDataType::class);
        $this->type = $var;

        return $this;
    }

    /**
     * Determines how many fractional places are important when entities are compared during filtering or sorting.
     *
     * Generated from protobuf field <code>int32 indexedDecimalPlaces = 3;</code>
     * @return int
     */
    public function getIndexedDecimalPlaces()
    {
        return $this->indexedDecimalPlaces;
    }

    /**
     * Determines how many fractional places are important when entities are compared during filtering or sorting.
     *
     * Generated from protobuf field <code>int32 indexedDecimalPlaces = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setIndexedDecimalPlaces($var)
    {
        GPBUtil::checkInt32($var);
        $this->indexedDecimalPlaces = $var;

        return $this;
    }

}

