<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GrpcTrafficRecording.proto

namespace Wtsvk\EvitaDbClient\Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Container for a query and its metadata.
 *
 * Generated from protobuf message <code>io.evitadb.externalApi.grpc.generated.GrpcTrafficQueryContainer</code>
 */
class GrpcTrafficQueryContainer extends \Google\Protobuf\Internal\Message
{
    /**
     * The shortened description of the query and its purpose
     *
     * Generated from protobuf field <code>string queryDescription = 1;</code>
     */
    protected $queryDescription = '';
    /**
     * The query operation.
     *
     * Generated from protobuf field <code>string query = 2;</code>
     */
    protected $query = '';
    /**
     * The total number of records calculated by the query.
     *
     * Generated from protobuf field <code>int32 totalRecordCount = 3;</code>
     */
    protected $totalRecordCount = 0;
    /**
     * The primary keys of the records returned by the query (in returned data chunk). I.e. number of records actually
     * returned by the pagination requirement of the query.
     *
     * Generated from protobuf field <code>repeated int32 primaryKeys = 4;</code>
     */
    private $primaryKeys;
    /**
     * The client labels associated with the query.
     *
     * Generated from protobuf field <code>repeated .io.evitadb.externalApi.grpc.generated.GrpcQueryLabel labels = 5;</code>
     */
    private $labels;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $queryDescription
     *           The shortened description of the query and its purpose
     *     @type string $query
     *           The query operation.
     *     @type int $totalRecordCount
     *           The total number of records calculated by the query.
     *     @type array<int>|\Google\Protobuf\Internal\RepeatedField $primaryKeys
     *           The primary keys of the records returned by the query (in returned data chunk). I.e. number of records actually
     *           returned by the pagination requirement of the query.
     *     @type array<\Wtsvk\EvitaDbClient\Protocol\GrpcQueryLabel>|\Google\Protobuf\Internal\RepeatedField $labels
     *           The client labels associated with the query.
     * }
     */
    public function __construct($data = NULL) {
        \Wtsvk\EvitaDbClient\Protocol\GPBMetadata\GrpcTrafficRecording::initOnce();
        parent::__construct($data);
    }

    /**
     * The shortened description of the query and its purpose
     *
     * Generated from protobuf field <code>string queryDescription = 1;</code>
     * @return string
     */
    public function getQueryDescription()
    {
        return $this->queryDescription;
    }

    /**
     * The shortened description of the query and its purpose
     *
     * Generated from protobuf field <code>string queryDescription = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setQueryDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->queryDescription = $var;

        return $this;
    }

    /**
     * The query operation.
     *
     * Generated from protobuf field <code>string query = 2;</code>
     * @return string
     */
    public function getQuery()
    {
        return $this->query;
    }

    /**
     * The query operation.
     *
     * Generated from protobuf field <code>string query = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setQuery($var)
    {
        GPBUtil::checkString($var, True);
        $this->query = $var;

        return $this;
    }

    /**
     * The total number of records calculated by the query.
     *
     * Generated from protobuf field <code>int32 totalRecordCount = 3;</code>
     * @return int
     */
    public function getTotalRecordCount()
    {
        return $this->totalRecordCount;
    }

    /**
     * The total number of records calculated by the query.
     *
     * Generated from protobuf field <code>int32 totalRecordCount = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setTotalRecordCount($var)
    {
        GPBUtil::checkInt32($var);
        $this->totalRecordCount = $var;

        return $this;
    }

    /**
     * The primary keys of the records returned by the query (in returned data chunk). I.e. number of records actually
     * returned by the pagination requirement of the query.
     *
     * Generated from protobuf field <code>repeated int32 primaryKeys = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getPrimaryKeys()
    {
        return $this->primaryKeys;
    }

    /**
     * The primary keys of the records returned by the query (in returned data chunk). I.e. number of records actually
     * returned by the pagination requirement of the query.
     *
     * Generated from protobuf field <code>repeated int32 primaryKeys = 4;</code>
     * @param array<int>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setPrimaryKeys($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT32);
        $this->primaryKeys = $arr;

        return $this;
    }

    /**
     * The client labels associated with the query.
     *
     * Generated from protobuf field <code>repeated .io.evitadb.externalApi.grpc.generated.GrpcQueryLabel labels = 5;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getLabels()
    {
        return $this->labels;
    }

    /**
     * The client labels associated with the query.
     *
     * Generated from protobuf field <code>repeated .io.evitadb.externalApi.grpc.generated.GrpcQueryLabel labels = 5;</code>
     * @param array<\Wtsvk\EvitaDbClient\Protocol\GrpcQueryLabel>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setLabels($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Wtsvk\EvitaDbClient\Protocol\GrpcQueryLabel::class);
        $this->labels = $arr;

        return $this;
    }

}

