<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GrpcChangeCapture.proto

namespace Wtsvk\EvitaDbClient\Protocol;

use UnexpectedValueException;

/**
 * Enum to specify the depth of details sent in the CDC event.
 *
 * Protobuf type <code>io.evitadb.externalApi.grpc.generated.GrpcChangeCaptureContent</code>
 */
class GrpcChangeCaptureContent
{
    /**
     * Only the header of the event is sent.
     *
     * Generated from protobuf enum <code>CHANGE_HEADER = 0;</code>
     */
    const CHANGE_HEADER = 0;
    /**
     * Entire mutation triggering the event is sent. In case of mutations with the large content (associated data
     * update), the size of the event can be significant. Consider whether you need the entire mutation or just the
     * header.
     *
     * Generated from protobuf enum <code>CHANGE_BODY = 1;</code>
     */
    const CHANGE_BODY = 1;

    private static $valueToName = [
        self::CHANGE_HEADER => 'CHANGE_HEADER',
        self::CHANGE_BODY => 'CHANGE_BODY',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

