<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GrpcEnums.proto

namespace Wtsvk\EvitaDbClient\Protocol;

use UnexpectedValueException;

/**
 * Determines which price will be used for filtering.
 *
 * Protobuf type <code>io.evitadb.externalApi.grpc.generated.GrpcQueryPriceMode</code>
 */
class GrpcQueryPriceMode
{
    /**
     * Price computation operations will use actual price with tax added for filtering.
     *
     * Generated from protobuf enum <code>WITH_TAX = 0;</code>
     */
    const WITH_TAX = 0;
    /**
     * Price computation operations will use actual price without tax added for filtering.
     *
     * Generated from protobuf enum <code>WITHOUT_TAX = 1;</code>
     */
    const WITHOUT_TAX = 1;

    private static $valueToName = [
        self::WITH_TAX => 'WITH_TAX',
        self::WITHOUT_TAX => 'WITHOUT_TAX',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

