<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GrpcAttributeSchemaMutations.proto

namespace Wtsvk\EvitaDbClient\Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Mutation is responsible for setting value to a `AttributeSchema.sortable` in `EntitySchema`.
 * Mutation can be used for altering also the existing `AttributeSchema` or `GlobalAttributeSchema` alone.
 *
 * Generated from protobuf message <code>io.evitadb.externalApi.grpc.generated.GrpcSetAttributeSchemaSortableMutation</code>
 */
class GrpcSetAttributeSchemaSortableMutation extends \Google\Protobuf\Internal\Message
{
    /**
     * Name of the attribute the mutation is targeting.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     */
    protected $name = '';
    /**
     * When attribute is sortable, it is possible to sort entities by this attribute. Do not mark attribute
     * as sortable unless you know that you'll sort entities along this attribute. Each sortable attribute occupies
     * (memory/disk) space in the form of index.
     * deprecated in favor of `sortableInScopes`
     *
     * Generated from protobuf field <code>bool sortable = 2 [deprecated = true];</code>
     * @deprecated
     */
    protected $sortable = false;
    /**
     * When attribute is sortable, it is possible to sort entities by this attribute. Do not mark attribute
     * as sortable unless you know that you'll sort entities along this attribute. Each sortable attribute occupies
     * (memory/disk) space in the form of index.
     *
     * Generated from protobuf field <code>repeated .io.evitadb.externalApi.grpc.generated.GrpcEntityScope sortableInScopes = 3;</code>
     */
    private $sortableInScopes;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *           Name of the attribute the mutation is targeting.
     *     @type bool $sortable
     *           When attribute is sortable, it is possible to sort entities by this attribute. Do not mark attribute
     *           as sortable unless you know that you'll sort entities along this attribute. Each sortable attribute occupies
     *           (memory/disk) space in the form of index.
     *           deprecated in favor of `sortableInScopes`
     *     @type array<int>|\Google\Protobuf\Internal\RepeatedField $sortableInScopes
     *           When attribute is sortable, it is possible to sort entities by this attribute. Do not mark attribute
     *           as sortable unless you know that you'll sort entities along this attribute. Each sortable attribute occupies
     *           (memory/disk) space in the form of index.
     * }
     */
    public function __construct($data = NULL) {
        \Wtsvk\EvitaDbClient\Protocol\GPBMetadata\GrpcAttributeSchemaMutations::initOnce();
        parent::__construct($data);
    }

    /**
     * Name of the attribute the mutation is targeting.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Name of the attribute the mutation is targeting.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * When attribute is sortable, it is possible to sort entities by this attribute. Do not mark attribute
     * as sortable unless you know that you'll sort entities along this attribute. Each sortable attribute occupies
     * (memory/disk) space in the form of index.
     * deprecated in favor of `sortableInScopes`
     *
     * Generated from protobuf field <code>bool sortable = 2 [deprecated = true];</code>
     * @return bool
     * @deprecated
     */
    public function getSortable()
    {
        @trigger_error('sortable is deprecated.', E_USER_DEPRECATED);
        return $this->sortable;
    }

    /**
     * When attribute is sortable, it is possible to sort entities by this attribute. Do not mark attribute
     * as sortable unless you know that you'll sort entities along this attribute. Each sortable attribute occupies
     * (memory/disk) space in the form of index.
     * deprecated in favor of `sortableInScopes`
     *
     * Generated from protobuf field <code>bool sortable = 2 [deprecated = true];</code>
     * @param bool $var
     * @return $this
     * @deprecated
     */
    public function setSortable($var)
    {
        @trigger_error('sortable is deprecated.', E_USER_DEPRECATED);
        GPBUtil::checkBool($var);
        $this->sortable = $var;

        return $this;
    }

    /**
     * When attribute is sortable, it is possible to sort entities by this attribute. Do not mark attribute
     * as sortable unless you know that you'll sort entities along this attribute. Each sortable attribute occupies
     * (memory/disk) space in the form of index.
     *
     * Generated from protobuf field <code>repeated .io.evitadb.externalApi.grpc.generated.GrpcEntityScope sortableInScopes = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSortableInScopes()
    {
        return $this->sortableInScopes;
    }

    /**
     * When attribute is sortable, it is possible to sort entities by this attribute. Do not mark attribute
     * as sortable unless you know that you'll sort entities along this attribute. Each sortable attribute occupies
     * (memory/disk) space in the form of index.
     *
     * Generated from protobuf field <code>repeated .io.evitadb.externalApi.grpc.generated.GrpcEntityScope sortableInScopes = 3;</code>
     * @param array<int>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSortableInScopes($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::ENUM, \Wtsvk\EvitaDbClient\Protocol\GrpcEntityScope::class);
        $this->sortableInScopes = $arr;

        return $this;
    }

}

