<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GrpcTrafficRecording.proto

namespace Wtsvk\EvitaDbClient\Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * This container holds information about the session start.
 *
 * Generated from protobuf message <code>io.evitadb.externalApi.grpc.generated.GrpcTrafficSessionStartContainer</code>
 */
class GrpcTrafficSessionStartContainer extends \Google\Protobuf\Internal\Message
{
    /**
     * The version of the catalog that will be used for the entire session.
     *
     * Generated from protobuf field <code>int64 catalogVersion = 1;</code>
     */
    protected $catalogVersion = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $catalogVersion
     *           The version of the catalog that will be used for the entire session.
     * }
     */
    public function __construct($data = NULL) {
        \Wtsvk\EvitaDbClient\Protocol\GPBMetadata\GrpcTrafficRecording::initOnce();
        parent::__construct($data);
    }

    /**
     * The version of the catalog that will be used for the entire session.
     *
     * Generated from protobuf field <code>int64 catalogVersion = 1;</code>
     * @return int|string
     */
    public function getCatalogVersion()
    {
        return $this->catalogVersion;
    }

    /**
     * The version of the catalog that will be used for the entire session.
     *
     * Generated from protobuf field <code>int64 catalogVersion = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCatalogVersion($var)
    {
        GPBUtil::checkInt64($var);
        $this->catalogVersion = $var;

        return $this;
    }

}

