<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GrpcReferenceSchemaMutations.proto

namespace Wtsvk\EvitaDbClient\Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Mutation is responsible for setting value to a `ReferenceSchema.indexed` in `EntitySchema`.
 * Mutation can be used for altering also the existing `ReferenceSchema` alone.
 *
 * Generated from protobuf message <code>io.evitadb.externalApi.grpc.generated.GrpcSetReferenceSchemaIndexedMutation</code>
 */
class GrpcSetReferenceSchemaIndexedMutation extends \Google\Protobuf\Internal\Message
{
    /**
     * Name of the reference the mutation is targeting.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     */
    protected $name = '';
    /**
     * Set to true when the filterable property should be inherited from the original.
     * This property makes sense only for inherited reference attributes on reflected reference. For all other cases it
     * must be left as false. When set to TRUE the value of `filterable` field is ignored.
     *
     * Generated from protobuf field <code>bool inherited = 2;</code>
     */
    protected $inherited = false;
    /**
     * Whether the index for this reference should be created and maintained allowing to filter by
     * `referenceHaving` filtering constraints. Index is also required when reference is `faceted`.
     * Do not mark reference as faceted unless you know that you'll need to filter / sort entities by this reference.
     * Each indexed reference occupies (memory/disk) space in the form of index. When reference is not indexed,
     * the entity cannot be looked up by reference attributes or relation existence itself, but the data is loaded
     * alongside other references if requested.
     * deprecated in favor of `scopedIndexTypes`
     *
     * Generated from protobuf field <code>repeated .io.evitadb.externalApi.grpc.generated.GrpcEntityScope indexedInScopes = 3 [deprecated = true];</code>
     * @deprecated
     */
    private $indexedInScopes;
    /**
     * Scoped reference index types that define both the scope and the type of index for the reference.
     * This replaces the deprecated `indexedInScopes` field with more granular control over indexing.
     * When `inherited` is true, this field is ignored.
     *
     * Generated from protobuf field <code>repeated .io.evitadb.externalApi.grpc.generated.GrpcScopedReferenceIndexType scopedIndexTypes = 4;</code>
     */
    private $scopedIndexTypes;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *           Name of the reference the mutation is targeting.
     *     @type bool $inherited
     *           Set to true when the filterable property should be inherited from the original.
     *           This property makes sense only for inherited reference attributes on reflected reference. For all other cases it
     *           must be left as false. When set to TRUE the value of `filterable` field is ignored.
     *     @type array<int>|\Google\Protobuf\Internal\RepeatedField $indexedInScopes
     *           Whether the index for this reference should be created and maintained allowing to filter by
     *           `referenceHaving` filtering constraints. Index is also required when reference is `faceted`.
     *           Do not mark reference as faceted unless you know that you'll need to filter / sort entities by this reference.
     *           Each indexed reference occupies (memory/disk) space in the form of index. When reference is not indexed,
     *           the entity cannot be looked up by reference attributes or relation existence itself, but the data is loaded
     *           alongside other references if requested.
     *           deprecated in favor of `scopedIndexTypes`
     *     @type array<\Wtsvk\EvitaDbClient\Protocol\GrpcScopedReferenceIndexType>|\Google\Protobuf\Internal\RepeatedField $scopedIndexTypes
     *           Scoped reference index types that define both the scope and the type of index for the reference.
     *           This replaces the deprecated `indexedInScopes` field with more granular control over indexing.
     *           When `inherited` is true, this field is ignored.
     * }
     */
    public function __construct($data = NULL) {
        \Wtsvk\EvitaDbClient\Protocol\GPBMetadata\GrpcReferenceSchemaMutations::initOnce();
        parent::__construct($data);
    }

    /**
     * Name of the reference the mutation is targeting.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Name of the reference the mutation is targeting.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Set to true when the filterable property should be inherited from the original.
     * This property makes sense only for inherited reference attributes on reflected reference. For all other cases it
     * must be left as false. When set to TRUE the value of `filterable` field is ignored.
     *
     * Generated from protobuf field <code>bool inherited = 2;</code>
     * @return bool
     */
    public function getInherited()
    {
        return $this->inherited;
    }

    /**
     * Set to true when the filterable property should be inherited from the original.
     * This property makes sense only for inherited reference attributes on reflected reference. For all other cases it
     * must be left as false. When set to TRUE the value of `filterable` field is ignored.
     *
     * Generated from protobuf field <code>bool inherited = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setInherited($var)
    {
        GPBUtil::checkBool($var);
        $this->inherited = $var;

        return $this;
    }

    /**
     * Whether the index for this reference should be created and maintained allowing to filter by
     * `referenceHaving` filtering constraints. Index is also required when reference is `faceted`.
     * Do not mark reference as faceted unless you know that you'll need to filter / sort entities by this reference.
     * Each indexed reference occupies (memory/disk) space in the form of index. When reference is not indexed,
     * the entity cannot be looked up by reference attributes or relation existence itself, but the data is loaded
     * alongside other references if requested.
     * deprecated in favor of `scopedIndexTypes`
     *
     * Generated from protobuf field <code>repeated .io.evitadb.externalApi.grpc.generated.GrpcEntityScope indexedInScopes = 3 [deprecated = true];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     * @deprecated
     */
    public function getIndexedInScopes()
    {
        @trigger_error('indexedInScopes is deprecated.', E_USER_DEPRECATED);
        return $this->indexedInScopes;
    }

    /**
     * Whether the index for this reference should be created and maintained allowing to filter by
     * `referenceHaving` filtering constraints. Index is also required when reference is `faceted`.
     * Do not mark reference as faceted unless you know that you'll need to filter / sort entities by this reference.
     * Each indexed reference occupies (memory/disk) space in the form of index. When reference is not indexed,
     * the entity cannot be looked up by reference attributes or relation existence itself, but the data is loaded
     * alongside other references if requested.
     * deprecated in favor of `scopedIndexTypes`
     *
     * Generated from protobuf field <code>repeated .io.evitadb.externalApi.grpc.generated.GrpcEntityScope indexedInScopes = 3 [deprecated = true];</code>
     * @param array<int>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     * @deprecated
     */
    public function setIndexedInScopes($var)
    {
        @trigger_error('indexedInScopes is deprecated.', E_USER_DEPRECATED);
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::ENUM, \Wtsvk\EvitaDbClient\Protocol\GrpcEntityScope::class);
        $this->indexedInScopes = $arr;

        return $this;
    }

    /**
     * Scoped reference index types that define both the scope and the type of index for the reference.
     * This replaces the deprecated `indexedInScopes` field with more granular control over indexing.
     * When `inherited` is true, this field is ignored.
     *
     * Generated from protobuf field <code>repeated .io.evitadb.externalApi.grpc.generated.GrpcScopedReferenceIndexType scopedIndexTypes = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getScopedIndexTypes()
    {
        return $this->scopedIndexTypes;
    }

    /**
     * Scoped reference index types that define both the scope and the type of index for the reference.
     * This replaces the deprecated `indexedInScopes` field with more granular control over indexing.
     * When `inherited` is true, this field is ignored.
     *
     * Generated from protobuf field <code>repeated .io.evitadb.externalApi.grpc.generated.GrpcScopedReferenceIndexType scopedIndexTypes = 4;</code>
     * @param array<\Wtsvk\EvitaDbClient\Protocol\GrpcScopedReferenceIndexType>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setScopedIndexTypes($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Wtsvk\EvitaDbClient\Protocol\GrpcScopedReferenceIndexType::class);
        $this->scopedIndexTypes = $arr;

        return $this;
    }

}

