<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GrpcEnums.proto

namespace Wtsvk\EvitaDbClient\Protocol;

use UnexpectedValueException;

/**
 * Contains set of all possible close method behavior types when the session is committed/closed
 *
 * Protobuf type <code>io.evitadb.externalApi.grpc.generated.GrpcCommitBehavior</code>
 */
class GrpcCommitBehavior
{
    /**
     * Changes performed in the transaction are passed to evitaDB server, checked for conflicts and if no conflict
     * is found the transaction is marked as completed and commit is finished. This behaviour is fastest, but does
     * not guarantee that the changes are persisted on disk and durable. If the server crashes before the changes
     * are written to disk, the changes are lost.
     *
     * Generated from protobuf enum <code>WAIT_FOR_CONFLICT_RESOLUTION = 0;</code>
     */
    const WAIT_FOR_CONFLICT_RESOLUTION = 0;
    /**
     * Changes performed in the transaction are passed to evitaDB server, checked for conflicts and if no conflict
     * is found, they are written to Write Ahead Log (WAL) and transaction waits until the WAL is persisted on disk
     * (fsynced). After that the transaction is marked as completed and commit is finished. This behaviour is
     * slower than {&#64;link #NO_WAIT} but guarantees that the changes are persisted on disk and durable. The server
     * may decide to fsync changes from multiple transactions at once, so the transaction may wait longer than
     * necessary. This behaviour still does not guarantee that the changes will be visible immediately after
     * the commit - because they still need to be propagated to indexes in order new data can be found by queries.
     * This behaviour is default.
     *
     * Generated from protobuf enum <code>WAIT_FOR_LOG_PERSISTENCE = 1;</code>
     */
    const WAIT_FOR_LOG_PERSISTENCE = 1;
    /**
     * Changes performed in the transaction are passed to evitaDB server, checked for conflicts and if no conflict
     * is found, they are written to Write Ahead Log (WAL). Then the WAL is processed and all changes are propagated
     * to indexes. After that the transaction is marked as completed and commit is finished. This behaviour is
     * slowest but guarantees that the changes are persisted on disk and durable and that they are visible
     * immediately after the commit is marked as completed.
     *
     * Generated from protobuf enum <code>WAIT_FOR_CHANGES_VISIBLE = 2;</code>
     */
    const WAIT_FOR_CHANGES_VISIBLE = 2;

    private static $valueToName = [
        self::WAIT_FOR_CONFLICT_RESOLUTION => 'WAIT_FOR_CONFLICT_RESOLUTION',
        self::WAIT_FOR_LOG_PERSISTENCE => 'WAIT_FOR_LOG_PERSISTENCE',
        self::WAIT_FOR_CHANGES_VISIBLE => 'WAIT_FOR_CHANGES_VISIBLE',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

