<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GrpcEnums.proto

namespace Wtsvk\EvitaDbClient\Protocol;

use UnexpectedValueException;

/**
 * Enum specifies different modes for reference attributes inheritance in reflected schema.
 *
 * Protobuf type <code>io.evitadb.externalApi.grpc.generated.GrpcAttributeInheritanceBehavior</code>
 */
class GrpcAttributeInheritanceBehavior
{
    /**
     **
     * Inherit all attributes by default except those listed in the {&#64;link #getAttributeInheritanceFilter()} array.
     *
     * Generated from protobuf enum <code>INHERIT_ALL_EXCEPT = 0;</code>
     */
    const INHERIT_ALL_EXCEPT = 0;
    /**
     **
     * Do not inherit any attributes by default except those listed in the {&#64;link #getAttributeInheritanceFilter()} array.
     *
     * Generated from protobuf enum <code>INHERIT_ONLY_SPECIFIED = 1;</code>
     */
    const INHERIT_ONLY_SPECIFIED = 1;

    private static $valueToName = [
        self::INHERIT_ALL_EXCEPT => 'INHERIT_ALL_EXCEPT',
        self::INHERIT_ONLY_SPECIFIED => 'INHERIT_ONLY_SPECIFIED',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

