<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GrpcEntityMutation.proto

namespace Wtsvk\EvitaDbClient\Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Represents a terminal mutation that wraps a list of mutation that are to be performed on an entity.
 *
 * Generated from protobuf message <code>io.evitadb.externalApi.grpc.generated.GrpcEntityUpsertMutation</code>
 */
class GrpcEntityUpsertMutation extends \Google\Protobuf\Internal\Message
{
    /**
     * The type of the entity to be mutated.
     *
     * Generated from protobuf field <code>string entityType = 1;</code>
     */
    protected $entityType = '';
    /**
     * The primary key of the entity to be mutated.
     *
     * Generated from protobuf field <code>.google.protobuf.Int32Value entityPrimaryKey = 2;</code>
     */
    protected $entityPrimaryKey = null;
    /**
     * Controls behaviour of the upsert operation.
     * - MUST_NOT_EXIST: use when you know you'll be inserting a new value
     * - MUST_EXIST: use when you know you'll be updating an existing value
     * - MAY_EXIST: use when you're not sure
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcEntityExistence entityExistence = 3;</code>
     */
    protected $entityExistence = 0;
    /**
     * List of all local mutations that modify internal data of the entity.
     *
     * Generated from protobuf field <code>repeated .io.evitadb.externalApi.grpc.generated.GrpcLocalMutation mutations = 4;</code>
     */
    private $mutations;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $entityType
     *           The type of the entity to be mutated.
     *     @type \Google\Protobuf\Int32Value $entityPrimaryKey
     *           The primary key of the entity to be mutated.
     *     @type int $entityExistence
     *           Controls behaviour of the upsert operation.
     *           - MUST_NOT_EXIST: use when you know you'll be inserting a new value
     *           - MUST_EXIST: use when you know you'll be updating an existing value
     *           - MAY_EXIST: use when you're not sure
     *     @type array<\Wtsvk\EvitaDbClient\Protocol\GrpcLocalMutation>|\Google\Protobuf\Internal\RepeatedField $mutations
     *           List of all local mutations that modify internal data of the entity.
     * }
     */
    public function __construct($data = NULL) {
        \Wtsvk\EvitaDbClient\Protocol\GPBMetadata\GrpcEntityMutation::initOnce();
        parent::__construct($data);
    }

    /**
     * The type of the entity to be mutated.
     *
     * Generated from protobuf field <code>string entityType = 1;</code>
     * @return string
     */
    public function getEntityType()
    {
        return $this->entityType;
    }

    /**
     * The type of the entity to be mutated.
     *
     * Generated from protobuf field <code>string entityType = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setEntityType($var)
    {
        GPBUtil::checkString($var, True);
        $this->entityType = $var;

        return $this;
    }

    /**
     * The primary key of the entity to be mutated.
     *
     * Generated from protobuf field <code>.google.protobuf.Int32Value entityPrimaryKey = 2;</code>
     * @return \Google\Protobuf\Int32Value|null
     */
    public function getEntityPrimaryKey()
    {
        return $this->entityPrimaryKey;
    }

    public function hasEntityPrimaryKey()
    {
        return isset($this->entityPrimaryKey);
    }

    public function clearEntityPrimaryKey()
    {
        unset($this->entityPrimaryKey);
    }

    /**
     * Returns the unboxed value from <code>getEntityPrimaryKey()</code>

     * The primary key of the entity to be mutated.
     *
     * Generated from protobuf field <code>.google.protobuf.Int32Value entityPrimaryKey = 2;</code>
     * @return int|null
     */
    public function getEntityPrimaryKeyUnwrapped()
    {
        return $this->readWrapperValue("entityPrimaryKey");
    }

    /**
     * The primary key of the entity to be mutated.
     *
     * Generated from protobuf field <code>.google.protobuf.Int32Value entityPrimaryKey = 2;</code>
     * @param \Google\Protobuf\Int32Value $var
     * @return $this
     */
    public function setEntityPrimaryKey($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Int32Value::class);
        $this->entityPrimaryKey = $var;

        return $this;
    }

    /**
     * Sets the field by wrapping a primitive type in a Google\Protobuf\Int32Value object.

     * The primary key of the entity to be mutated.
     *
     * Generated from protobuf field <code>.google.protobuf.Int32Value entityPrimaryKey = 2;</code>
     * @param int|null $var
     * @return $this
     */
    public function setEntityPrimaryKeyUnwrapped($var)
    {
        $this->writeWrapperValue("entityPrimaryKey", $var);
        return $this;}

    /**
     * Controls behaviour of the upsert operation.
     * - MUST_NOT_EXIST: use when you know you'll be inserting a new value
     * - MUST_EXIST: use when you know you'll be updating an existing value
     * - MAY_EXIST: use when you're not sure
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcEntityExistence entityExistence = 3;</code>
     * @return int
     */
    public function getEntityExistence()
    {
        return $this->entityExistence;
    }

    /**
     * Controls behaviour of the upsert operation.
     * - MUST_NOT_EXIST: use when you know you'll be inserting a new value
     * - MUST_EXIST: use when you know you'll be updating an existing value
     * - MAY_EXIST: use when you're not sure
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcEntityExistence entityExistence = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setEntityExistence($var)
    {
        GPBUtil::checkEnum($var, \Wtsvk\EvitaDbClient\Protocol\GrpcEntityExistence::class);
        $this->entityExistence = $var;

        return $this;
    }

    /**
     * List of all local mutations that modify internal data of the entity.
     *
     * Generated from protobuf field <code>repeated .io.evitadb.externalApi.grpc.generated.GrpcLocalMutation mutations = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getMutations()
    {
        return $this->mutations;
    }

    /**
     * List of all local mutations that modify internal data of the entity.
     *
     * Generated from protobuf field <code>repeated .io.evitadb.externalApi.grpc.generated.GrpcLocalMutation mutations = 4;</code>
     * @param array<\Wtsvk\EvitaDbClient\Protocol\GrpcLocalMutation>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setMutations($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Wtsvk\EvitaDbClient\Protocol\GrpcLocalMutation::class);
        $this->mutations = $arr;

        return $this;
    }

}

