<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GrpcEvitaSessionAPI.proto

namespace Wtsvk\EvitaDbClient\Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Request for updating the entity schema and its afterwards fetching.
 *
 * Generated from protobuf message <code>io.evitadb.externalApi.grpc.generated.GrpcUpdateAndFetchEntitySchemaResponse</code>
 */
class GrpcUpdateAndFetchEntitySchemaResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Modified entity schema.
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcEntitySchema entitySchema = 1;</code>
     */
    protected $entitySchema = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Wtsvk\EvitaDbClient\Protocol\GrpcEntitySchema $entitySchema
     *           Modified entity schema.
     * }
     */
    public function __construct($data = NULL) {
        \Wtsvk\EvitaDbClient\Protocol\GPBMetadata\GrpcEvitaSessionAPI::initOnce();
        parent::__construct($data);
    }

    /**
     * Modified entity schema.
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcEntitySchema entitySchema = 1;</code>
     * @return \Wtsvk\EvitaDbClient\Protocol\GrpcEntitySchema|null
     */
    public function getEntitySchema()
    {
        return $this->entitySchema;
    }

    public function hasEntitySchema()
    {
        return isset($this->entitySchema);
    }

    public function clearEntitySchema()
    {
        unset($this->entitySchema);
    }

    /**
     * Modified entity schema.
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcEntitySchema entitySchema = 1;</code>
     * @param \Wtsvk\EvitaDbClient\Protocol\GrpcEntitySchema $var
     * @return $this
     */
    public function setEntitySchema($var)
    {
        GPBUtil::checkMessage($var, \Wtsvk\EvitaDbClient\Protocol\GrpcEntitySchema::class);
        $this->entitySchema = $var;

        return $this;
    }

}

