<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GrpcEvitaSessionAPI.proto

namespace Wtsvk\EvitaDbClient\Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Response for GoLiveAndClose request that switches the catalog to ALIVE state and closes the session.
 *
 * Generated from protobuf message <code>io.evitadb.externalApi.grpc.generated.GrpcGoLiveAndCloseResponse</code>
 */
class GrpcGoLiveAndCloseResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * True, if the catalog was switched to ALIVE state.
     *
     * Generated from protobuf field <code>bool success = 1;</code>
     */
    protected $success = false;
    /**
     * Contains next catalog version
     *
     * Generated from protobuf field <code>int64 catalogVersion = 2;</code>
     */
    protected $catalogVersion = 0;
    /**
     * Contains the version of the catalog schema that will be valid at the moment of closing the session.
     * If session relates to a writable transaction, this schema version becomes valid at the moment the next catalog
     * version (i.e. the one that is returned in the response) becomes visible.
     *
     * Generated from protobuf field <code>int32 catalogSchemaVersion = 3;</code>
     */
    protected $catalogSchemaVersion = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $success
     *           True, if the catalog was switched to ALIVE state.
     *     @type int|string $catalogVersion
     *           Contains next catalog version
     *     @type int $catalogSchemaVersion
     *           Contains the version of the catalog schema that will be valid at the moment of closing the session.
     *           If session relates to a writable transaction, this schema version becomes valid at the moment the next catalog
     *           version (i.e. the one that is returned in the response) becomes visible.
     * }
     */
    public function __construct($data = NULL) {
        \Wtsvk\EvitaDbClient\Protocol\GPBMetadata\GrpcEvitaSessionAPI::initOnce();
        parent::__construct($data);
    }

    /**
     * True, if the catalog was switched to ALIVE state.
     *
     * Generated from protobuf field <code>bool success = 1;</code>
     * @return bool
     */
    public function getSuccess()
    {
        return $this->success;
    }

    /**
     * True, if the catalog was switched to ALIVE state.
     *
     * Generated from protobuf field <code>bool success = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setSuccess($var)
    {
        GPBUtil::checkBool($var);
        $this->success = $var;

        return $this;
    }

    /**
     * Contains next catalog version
     *
     * Generated from protobuf field <code>int64 catalogVersion = 2;</code>
     * @return int|string
     */
    public function getCatalogVersion()
    {
        return $this->catalogVersion;
    }

    /**
     * Contains next catalog version
     *
     * Generated from protobuf field <code>int64 catalogVersion = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCatalogVersion($var)
    {
        GPBUtil::checkInt64($var);
        $this->catalogVersion = $var;

        return $this;
    }

    /**
     * Contains the version of the catalog schema that will be valid at the moment of closing the session.
     * If session relates to a writable transaction, this schema version becomes valid at the moment the next catalog
     * version (i.e. the one that is returned in the response) becomes visible.
     *
     * Generated from protobuf field <code>int32 catalogSchemaVersion = 3;</code>
     * @return int
     */
    public function getCatalogSchemaVersion()
    {
        return $this->catalogSchemaVersion;
    }

    /**
     * Contains the version of the catalog schema that will be valid at the moment of closing the session.
     * If session relates to a writable transaction, this schema version becomes valid at the moment the next catalog
     * version (i.e. the one that is returned in the response) becomes visible.
     *
     * Generated from protobuf field <code>int32 catalogSchemaVersion = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setCatalogSchemaVersion($var)
    {
        GPBUtil::checkInt32($var);
        $this->catalogSchemaVersion = $var;

        return $this;
    }

}

