<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GrpcExtraResults.proto

namespace Wtsvk\EvitaDbClient\Protocol;

if (false) {
    /**
     * This class is deprecated. Use Wtsvk\EvitaDbClient\Protocol\GrpcHistogram\GrpcBucket instead.
     * @deprecated
     */
    class GrpcHistogram_GrpcBucket {}
}
class_exists(GrpcHistogram\GrpcBucket::class);
@trigger_error('Wtsvk\EvitaDbClient\Protocol\GrpcHistogram_GrpcBucket is deprecated and will be removed in the next major release. Use Wtsvk\EvitaDbClient\Protocol\GrpcHistogram\GrpcBucket instead', E_USER_DEPRECATED);

