<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GrpcEnums.proto

namespace Wtsvk\EvitaDbClient\Protocol;

use UnexpectedValueException;

/**
 * The enumeration controls HierarchyOfReference behaviour whether the hierarchical nodes that are not referred
 * by any of the queried entities should be part of the result hierarchy statistics tree.
 *
 * Protobuf type <code>io.evitadb.externalApi.grpc.generated.GrpcEmptyHierarchicalEntityBehaviour</code>
 */
class GrpcEmptyHierarchicalEntityBehaviour
{
    /**
     * The hierarchy nodes that are not referred by any of the queried entities will be part of the result hierarchy
     *
     * Generated from protobuf enum <code>LEAVE_EMPTY = 0;</code>
     */
    const LEAVE_EMPTY = 0;
    /**
     * The hierarchy nodes that are not referred by any of the queried entities will be removed from the result hierarchy
     *
     * Generated from protobuf enum <code>REMOVE_EMPTY = 1;</code>
     */
    const REMOVE_EMPTY = 1;

    private static $valueToName = [
        self::LEAVE_EMPTY => 'LEAVE_EMPTY',
        self::REMOVE_EMPTY => 'REMOVE_EMPTY',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

