<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GrpcAssociatedDataSchemaMutations.proto

namespace Wtsvk\EvitaDbClient\Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Mutation is responsible for setting value to a `AssociatedDataSchemaContract.deprecationNotice`
 * in `EntitySchema`.
 * Mutation can be used for altering also the existing `AssociatedDataSchema` alone.
 *
 * Generated from protobuf message <code>io.evitadb.externalApi.grpc.generated.GrpcModifyAssociatedDataSchemaDeprecationNoticeMutation</code>
 */
class GrpcModifyAssociatedDataSchemaDeprecationNoticeMutation extends \Google\Protobuf\Internal\Message
{
    /**
     * Contains unique name of the model. Case-sensitive. Distinguishes one model item from another
     * within single entity instance.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     */
    protected $name = '';
    /**
     * Deprecation notice contains information about planned removal of this associated data from the model / client API.
     * This allows to plan and evolve the schema allowing clients to adapt early to planned breaking changes.
     *
     * Generated from protobuf field <code>.google.protobuf.StringValue deprecationNotice = 2;</code>
     */
    protected $deprecationNotice = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *           Contains unique name of the model. Case-sensitive. Distinguishes one model item from another
     *           within single entity instance.
     *     @type \Google\Protobuf\StringValue $deprecationNotice
     *           Deprecation notice contains information about planned removal of this associated data from the model / client API.
     *           This allows to plan and evolve the schema allowing clients to adapt early to planned breaking changes.
     * }
     */
    public function __construct($data = NULL) {
        \Wtsvk\EvitaDbClient\Protocol\GPBMetadata\GrpcAssociatedDataSchemaMutations::initOnce();
        parent::__construct($data);
    }

    /**
     * Contains unique name of the model. Case-sensitive. Distinguishes one model item from another
     * within single entity instance.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Contains unique name of the model. Case-sensitive. Distinguishes one model item from another
     * within single entity instance.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Deprecation notice contains information about planned removal of this associated data from the model / client API.
     * This allows to plan and evolve the schema allowing clients to adapt early to planned breaking changes.
     *
     * Generated from protobuf field <code>.google.protobuf.StringValue deprecationNotice = 2;</code>
     * @return \Google\Protobuf\StringValue|null
     */
    public function getDeprecationNotice()
    {
        return $this->deprecationNotice;
    }

    public function hasDeprecationNotice()
    {
        return isset($this->deprecationNotice);
    }

    public function clearDeprecationNotice()
    {
        unset($this->deprecationNotice);
    }

    /**
     * Returns the unboxed value from <code>getDeprecationNotice()</code>

     * Deprecation notice contains information about planned removal of this associated data from the model / client API.
     * This allows to plan and evolve the schema allowing clients to adapt early to planned breaking changes.
     *
     * Generated from protobuf field <code>.google.protobuf.StringValue deprecationNotice = 2;</code>
     * @return string|null
     */
    public function getDeprecationNoticeUnwrapped()
    {
        return $this->readWrapperValue("deprecationNotice");
    }

    /**
     * Deprecation notice contains information about planned removal of this associated data from the model / client API.
     * This allows to plan and evolve the schema allowing clients to adapt early to planned breaking changes.
     *
     * Generated from protobuf field <code>.google.protobuf.StringValue deprecationNotice = 2;</code>
     * @param \Google\Protobuf\StringValue $var
     * @return $this
     */
    public function setDeprecationNotice($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\StringValue::class);
        $this->deprecationNotice = $var;

        return $this;
    }

    /**
     * Sets the field by wrapping a primitive type in a Google\Protobuf\StringValue object.

     * Deprecation notice contains information about planned removal of this associated data from the model / client API.
     * This allows to plan and evolve the schema allowing clients to adapt early to planned breaking changes.
     *
     * Generated from protobuf field <code>.google.protobuf.StringValue deprecationNotice = 2;</code>
     * @param string|null $var
     * @return $this
     */
    public function setDeprecationNoticeUnwrapped($var)
    {
        $this->writeWrapperValue("deprecationNotice", $var);
        return $this;}

}

