<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GrpcAssociatedDataSchemaMutations.proto

namespace Wtsvk\EvitaDbClient\Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Mutation is responsible for setting up a new `AssociatedDataSchema` in the `EntitySchema`.
 * Mutation can be used for altering also the existing `AssociatedDataSchema` alone.
 *
 * Generated from protobuf message <code>io.evitadb.externalApi.grpc.generated.GrpcCreateAssociatedDataSchemaMutation</code>
 */
class GrpcCreateAssociatedDataSchemaMutation extends \Google\Protobuf\Internal\Message
{
    /**
     * Contains unique name of the model. Case-sensitive. Distinguishes one model item from another
     * within single entity instance.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     */
    protected $name = '';
    /**
     * Contains description of the model is optional but helps authors of the schema / client API to better
     * explain the original purpose of the model to the consumers.
     *
     * Generated from protobuf field <code>.google.protobuf.StringValue description = 2;</code>
     */
    protected $description = null;
    /**
     * Deprecation notice contains information about planned removal of this associated data from the model / client API.
     * This allows to plan and evolve the schema allowing clients to adapt early to planned breaking changes.
     *
     * Generated from protobuf field <code>.google.protobuf.StringValue deprecationNotice = 3;</code>
     */
    protected $deprecationNotice = null;
    /**
     * Contains the data type of the entity. Must be one of supported types or may
     * represent complex type - which is JSON object that can be automatically converted
     * to the set of basic types.
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcEvitaAssociatedDataDataType.GrpcEvitaDataType type = 4;</code>
     */
    protected $type = 0;
    /**
     * Localized associated data has to be ALWAYS used in connection with specific `locale`. In other
     * words - it cannot be stored unless associated locale is also provided.
     *
     * Generated from protobuf field <code>bool localized = 5;</code>
     */
    protected $localized = false;
    /**
     * When associated data is nullable, its values may be missing in the entities. Otherwise, the system will enforce
     * non-null checks upon upserting of the entity.
     *
     * Generated from protobuf field <code>bool nullable = 6;</code>
     */
    protected $nullable = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *           Contains unique name of the model. Case-sensitive. Distinguishes one model item from another
     *           within single entity instance.
     *     @type \Google\Protobuf\StringValue $description
     *           Contains description of the model is optional but helps authors of the schema / client API to better
     *           explain the original purpose of the model to the consumers.
     *     @type \Google\Protobuf\StringValue $deprecationNotice
     *           Deprecation notice contains information about planned removal of this associated data from the model / client API.
     *           This allows to plan and evolve the schema allowing clients to adapt early to planned breaking changes.
     *     @type int $type
     *           Contains the data type of the entity. Must be one of supported types or may
     *           represent complex type - which is JSON object that can be automatically converted
     *           to the set of basic types.
     *     @type bool $localized
     *           Localized associated data has to be ALWAYS used in connection with specific `locale`. In other
     *           words - it cannot be stored unless associated locale is also provided.
     *     @type bool $nullable
     *           When associated data is nullable, its values may be missing in the entities. Otherwise, the system will enforce
     *           non-null checks upon upserting of the entity.
     * }
     */
    public function __construct($data = NULL) {
        \Wtsvk\EvitaDbClient\Protocol\GPBMetadata\GrpcAssociatedDataSchemaMutations::initOnce();
        parent::__construct($data);
    }

    /**
     * Contains unique name of the model. Case-sensitive. Distinguishes one model item from another
     * within single entity instance.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Contains unique name of the model. Case-sensitive. Distinguishes one model item from another
     * within single entity instance.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Contains description of the model is optional but helps authors of the schema / client API to better
     * explain the original purpose of the model to the consumers.
     *
     * Generated from protobuf field <code>.google.protobuf.StringValue description = 2;</code>
     * @return \Google\Protobuf\StringValue|null
     */
    public function getDescription()
    {
        return $this->description;
    }

    public function hasDescription()
    {
        return isset($this->description);
    }

    public function clearDescription()
    {
        unset($this->description);
    }

    /**
     * Returns the unboxed value from <code>getDescription()</code>

     * Contains description of the model is optional but helps authors of the schema / client API to better
     * explain the original purpose of the model to the consumers.
     *
     * Generated from protobuf field <code>.google.protobuf.StringValue description = 2;</code>
     * @return string|null
     */
    public function getDescriptionUnwrapped()
    {
        return $this->readWrapperValue("description");
    }

    /**
     * Contains description of the model is optional but helps authors of the schema / client API to better
     * explain the original purpose of the model to the consumers.
     *
     * Generated from protobuf field <code>.google.protobuf.StringValue description = 2;</code>
     * @param \Google\Protobuf\StringValue $var
     * @return $this
     */
    public function setDescription($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\StringValue::class);
        $this->description = $var;

        return $this;
    }

    /**
     * Sets the field by wrapping a primitive type in a Google\Protobuf\StringValue object.

     * Contains description of the model is optional but helps authors of the schema / client API to better
     * explain the original purpose of the model to the consumers.
     *
     * Generated from protobuf field <code>.google.protobuf.StringValue description = 2;</code>
     * @param string|null $var
     * @return $this
     */
    public function setDescriptionUnwrapped($var)
    {
        $this->writeWrapperValue("description", $var);
        return $this;}

    /**
     * Deprecation notice contains information about planned removal of this associated data from the model / client API.
     * This allows to plan and evolve the schema allowing clients to adapt early to planned breaking changes.
     *
     * Generated from protobuf field <code>.google.protobuf.StringValue deprecationNotice = 3;</code>
     * @return \Google\Protobuf\StringValue|null
     */
    public function getDeprecationNotice()
    {
        return $this->deprecationNotice;
    }

    public function hasDeprecationNotice()
    {
        return isset($this->deprecationNotice);
    }

    public function clearDeprecationNotice()
    {
        unset($this->deprecationNotice);
    }

    /**
     * Returns the unboxed value from <code>getDeprecationNotice()</code>

     * Deprecation notice contains information about planned removal of this associated data from the model / client API.
     * This allows to plan and evolve the schema allowing clients to adapt early to planned breaking changes.
     *
     * Generated from protobuf field <code>.google.protobuf.StringValue deprecationNotice = 3;</code>
     * @return string|null
     */
    public function getDeprecationNoticeUnwrapped()
    {
        return $this->readWrapperValue("deprecationNotice");
    }

    /**
     * Deprecation notice contains information about planned removal of this associated data from the model / client API.
     * This allows to plan and evolve the schema allowing clients to adapt early to planned breaking changes.
     *
     * Generated from protobuf field <code>.google.protobuf.StringValue deprecationNotice = 3;</code>
     * @param \Google\Protobuf\StringValue $var
     * @return $this
     */
    public function setDeprecationNotice($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\StringValue::class);
        $this->deprecationNotice = $var;

        return $this;
    }

    /**
     * Sets the field by wrapping a primitive type in a Google\Protobuf\StringValue object.

     * Deprecation notice contains information about planned removal of this associated data from the model / client API.
     * This allows to plan and evolve the schema allowing clients to adapt early to planned breaking changes.
     *
     * Generated from protobuf field <code>.google.protobuf.StringValue deprecationNotice = 3;</code>
     * @param string|null $var
     * @return $this
     */
    public function setDeprecationNoticeUnwrapped($var)
    {
        $this->writeWrapperValue("deprecationNotice", $var);
        return $this;}

    /**
     * Contains the data type of the entity. Must be one of supported types or may
     * represent complex type - which is JSON object that can be automatically converted
     * to the set of basic types.
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcEvitaAssociatedDataDataType.GrpcEvitaDataType type = 4;</code>
     * @return int
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Contains the data type of the entity. Must be one of supported types or may
     * represent complex type - which is JSON object that can be automatically converted
     * to the set of basic types.
     *
     * Generated from protobuf field <code>.io.evitadb.externalApi.grpc.generated.GrpcEvitaAssociatedDataDataType.GrpcEvitaDataType type = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkEnum($var, \Wtsvk\EvitaDbClient\Protocol\GrpcEvitaAssociatedDataDataType\GrpcEvitaDataType::class);
        $this->type = $var;

        return $this;
    }

    /**
     * Localized associated data has to be ALWAYS used in connection with specific `locale`. In other
     * words - it cannot be stored unless associated locale is also provided.
     *
     * Generated from protobuf field <code>bool localized = 5;</code>
     * @return bool
     */
    public function getLocalized()
    {
        return $this->localized;
    }

    /**
     * Localized associated data has to be ALWAYS used in connection with specific `locale`. In other
     * words - it cannot be stored unless associated locale is also provided.
     *
     * Generated from protobuf field <code>bool localized = 5;</code>
     * @param bool $var
     * @return $this
     */
    public function setLocalized($var)
    {
        GPBUtil::checkBool($var);
        $this->localized = $var;

        return $this;
    }

    /**
     * When associated data is nullable, its values may be missing in the entities. Otherwise, the system will enforce
     * non-null checks upon upserting of the entity.
     *
     * Generated from protobuf field <code>bool nullable = 6;</code>
     * @return bool
     */
    public function getNullable()
    {
        return $this->nullable;
    }

    /**
     * When associated data is nullable, its values may be missing in the entities. Otherwise, the system will enforce
     * non-null checks upon upserting of the entity.
     *
     * Generated from protobuf field <code>bool nullable = 6;</code>
     * @param bool $var
     * @return $this
     */
    public function setNullable($var)
    {
        GPBUtil::checkBool($var);
        $this->nullable = $var;

        return $this;
    }

}

