<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GrpcEntitySchema.proto

namespace Wtsvk\EvitaDbClient\Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Sortable attribute compounds are used to sort entities or references by multiple attributes at once. evitaDB
 * requires a pre-sorted index in order to be able to sort entities or references by particular attribute or
 * combination of attributes, so it can deliver the results as fast as possible. Sortable attribute compounds
 * are filtered the same way as attributes - using natural ordering constraint.
 *
 * Generated from protobuf message <code>io.evitadb.externalApi.grpc.generated.GrpcSortableAttributeCompoundSchema</code>
 */
class GrpcSortableAttributeCompoundSchema extends \Google\Protobuf\Internal\Message
{
    /**
     * Contains unique name of the model. Case-sensitive. Distinguishes one model item from another
     * within single entity instance.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     */
    protected $name = '';
    /**
     * Contains description of the model is optional but helps authors of the schema / client API to better
     * explain the original purpose of the model to the consumers.
     *
     * Generated from protobuf field <code>.google.protobuf.StringValue description = 2;</code>
     */
    protected $description = null;
    /**
     * Deprecation notice contains information about planned removal of this entity from the model / client API.
     * This allows to plan and evolve the schema allowing clients to adapt early to planned breaking changes.
     * If notice is `null`, this schema is considered not deprecated.
     *
     * Generated from protobuf field <code>.google.protobuf.StringValue deprecationNotice = 3;</code>
     */
    protected $deprecationNotice = null;
    /**
     * Collection of attribute elements that define the sortable compound. The order of the elements
     * is important, as it defines the order of the sorting.
     *
     * Generated from protobuf field <code>repeated .io.evitadb.externalApi.grpc.generated.GrpcAttributeElement attributeElements = 4;</code>
     */
    private $attributeElements;
    /**
     * Contains attribute compound name converted to different naming conventions.
     *
     * Generated from protobuf field <code>repeated .io.evitadb.externalApi.grpc.generated.GrpcNameVariant nameVariant = 5;</code>
     */
    private $nameVariant;
    /**
     * Contains true if the attribute was inherited from the original object via reflected reference relation
     *
     * Generated from protobuf field <code>bool inherited = 6;</code>
     */
    protected $inherited = false;
    /**
     * When attribute sortable compound is indexed, it is possible to sort entities by this calculated attribute compound.
     * This property contains set of all scopes this attribute compound is indexed in.
     *
     * Generated from protobuf field <code>repeated .io.evitadb.externalApi.grpc.generated.GrpcEntityScope indexedInScopes = 7;</code>
     */
    private $indexedInScopes;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *           Contains unique name of the model. Case-sensitive. Distinguishes one model item from another
     *           within single entity instance.
     *     @type \Google\Protobuf\StringValue $description
     *           Contains description of the model is optional but helps authors of the schema / client API to better
     *           explain the original purpose of the model to the consumers.
     *     @type \Google\Protobuf\StringValue $deprecationNotice
     *           Deprecation notice contains information about planned removal of this entity from the model / client API.
     *           This allows to plan and evolve the schema allowing clients to adapt early to planned breaking changes.
     *           If notice is `null`, this schema is considered not deprecated.
     *     @type array<\Wtsvk\EvitaDbClient\Protocol\GrpcAttributeElement>|\Google\Protobuf\Internal\RepeatedField $attributeElements
     *           Collection of attribute elements that define the sortable compound. The order of the elements
     *           is important, as it defines the order of the sorting.
     *     @type array<\Wtsvk\EvitaDbClient\Protocol\GrpcNameVariant>|\Google\Protobuf\Internal\RepeatedField $nameVariant
     *           Contains attribute compound name converted to different naming conventions.
     *     @type bool $inherited
     *           Contains true if the attribute was inherited from the original object via reflected reference relation
     *     @type array<int>|\Google\Protobuf\Internal\RepeatedField $indexedInScopes
     *           When attribute sortable compound is indexed, it is possible to sort entities by this calculated attribute compound.
     *           This property contains set of all scopes this attribute compound is indexed in.
     * }
     */
    public function __construct($data = NULL) {
        \Wtsvk\EvitaDbClient\Protocol\GPBMetadata\GrpcEntitySchema::initOnce();
        parent::__construct($data);
    }

    /**
     * Contains unique name of the model. Case-sensitive. Distinguishes one model item from another
     * within single entity instance.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Contains unique name of the model. Case-sensitive. Distinguishes one model item from another
     * within single entity instance.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Contains description of the model is optional but helps authors of the schema / client API to better
     * explain the original purpose of the model to the consumers.
     *
     * Generated from protobuf field <code>.google.protobuf.StringValue description = 2;</code>
     * @return \Google\Protobuf\StringValue|null
     */
    public function getDescription()
    {
        return $this->description;
    }

    public function hasDescription()
    {
        return isset($this->description);
    }

    public function clearDescription()
    {
        unset($this->description);
    }

    /**
     * Returns the unboxed value from <code>getDescription()</code>

     * Contains description of the model is optional but helps authors of the schema / client API to better
     * explain the original purpose of the model to the consumers.
     *
     * Generated from protobuf field <code>.google.protobuf.StringValue description = 2;</code>
     * @return string|null
     */
    public function getDescriptionUnwrapped()
    {
        return $this->readWrapperValue("description");
    }

    /**
     * Contains description of the model is optional but helps authors of the schema / client API to better
     * explain the original purpose of the model to the consumers.
     *
     * Generated from protobuf field <code>.google.protobuf.StringValue description = 2;</code>
     * @param \Google\Protobuf\StringValue $var
     * @return $this
     */
    public function setDescription($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\StringValue::class);
        $this->description = $var;

        return $this;
    }

    /**
     * Sets the field by wrapping a primitive type in a Google\Protobuf\StringValue object.

     * Contains description of the model is optional but helps authors of the schema / client API to better
     * explain the original purpose of the model to the consumers.
     *
     * Generated from protobuf field <code>.google.protobuf.StringValue description = 2;</code>
     * @param string|null $var
     * @return $this
     */
    public function setDescriptionUnwrapped($var)
    {
        $this->writeWrapperValue("description", $var);
        return $this;}

    /**
     * Deprecation notice contains information about planned removal of this entity from the model / client API.
     * This allows to plan and evolve the schema allowing clients to adapt early to planned breaking changes.
     * If notice is `null`, this schema is considered not deprecated.
     *
     * Generated from protobuf field <code>.google.protobuf.StringValue deprecationNotice = 3;</code>
     * @return \Google\Protobuf\StringValue|null
     */
    public function getDeprecationNotice()
    {
        return $this->deprecationNotice;
    }

    public function hasDeprecationNotice()
    {
        return isset($this->deprecationNotice);
    }

    public function clearDeprecationNotice()
    {
        unset($this->deprecationNotice);
    }

    /**
     * Returns the unboxed value from <code>getDeprecationNotice()</code>

     * Deprecation notice contains information about planned removal of this entity from the model / client API.
     * This allows to plan and evolve the schema allowing clients to adapt early to planned breaking changes.
     * If notice is `null`, this schema is considered not deprecated.
     *
     * Generated from protobuf field <code>.google.protobuf.StringValue deprecationNotice = 3;</code>
     * @return string|null
     */
    public function getDeprecationNoticeUnwrapped()
    {
        return $this->readWrapperValue("deprecationNotice");
    }

    /**
     * Deprecation notice contains information about planned removal of this entity from the model / client API.
     * This allows to plan and evolve the schema allowing clients to adapt early to planned breaking changes.
     * If notice is `null`, this schema is considered not deprecated.
     *
     * Generated from protobuf field <code>.google.protobuf.StringValue deprecationNotice = 3;</code>
     * @param \Google\Protobuf\StringValue $var
     * @return $this
     */
    public function setDeprecationNotice($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\StringValue::class);
        $this->deprecationNotice = $var;

        return $this;
    }

    /**
     * Sets the field by wrapping a primitive type in a Google\Protobuf\StringValue object.

     * Deprecation notice contains information about planned removal of this entity from the model / client API.
     * This allows to plan and evolve the schema allowing clients to adapt early to planned breaking changes.
     * If notice is `null`, this schema is considered not deprecated.
     *
     * Generated from protobuf field <code>.google.protobuf.StringValue deprecationNotice = 3;</code>
     * @param string|null $var
     * @return $this
     */
    public function setDeprecationNoticeUnwrapped($var)
    {
        $this->writeWrapperValue("deprecationNotice", $var);
        return $this;}

    /**
     * Collection of attribute elements that define the sortable compound. The order of the elements
     * is important, as it defines the order of the sorting.
     *
     * Generated from protobuf field <code>repeated .io.evitadb.externalApi.grpc.generated.GrpcAttributeElement attributeElements = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAttributeElements()
    {
        return $this->attributeElements;
    }

    /**
     * Collection of attribute elements that define the sortable compound. The order of the elements
     * is important, as it defines the order of the sorting.
     *
     * Generated from protobuf field <code>repeated .io.evitadb.externalApi.grpc.generated.GrpcAttributeElement attributeElements = 4;</code>
     * @param array<\Wtsvk\EvitaDbClient\Protocol\GrpcAttributeElement>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAttributeElements($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Wtsvk\EvitaDbClient\Protocol\GrpcAttributeElement::class);
        $this->attributeElements = $arr;

        return $this;
    }

    /**
     * Contains attribute compound name converted to different naming conventions.
     *
     * Generated from protobuf field <code>repeated .io.evitadb.externalApi.grpc.generated.GrpcNameVariant nameVariant = 5;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getNameVariant()
    {
        return $this->nameVariant;
    }

    /**
     * Contains attribute compound name converted to different naming conventions.
     *
     * Generated from protobuf field <code>repeated .io.evitadb.externalApi.grpc.generated.GrpcNameVariant nameVariant = 5;</code>
     * @param array<\Wtsvk\EvitaDbClient\Protocol\GrpcNameVariant>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setNameVariant($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Wtsvk\EvitaDbClient\Protocol\GrpcNameVariant::class);
        $this->nameVariant = $arr;

        return $this;
    }

    /**
     * Contains true if the attribute was inherited from the original object via reflected reference relation
     *
     * Generated from protobuf field <code>bool inherited = 6;</code>
     * @return bool
     */
    public function getInherited()
    {
        return $this->inherited;
    }

    /**
     * Contains true if the attribute was inherited from the original object via reflected reference relation
     *
     * Generated from protobuf field <code>bool inherited = 6;</code>
     * @param bool $var
     * @return $this
     */
    public function setInherited($var)
    {
        GPBUtil::checkBool($var);
        $this->inherited = $var;

        return $this;
    }

    /**
     * When attribute sortable compound is indexed, it is possible to sort entities by this calculated attribute compound.
     * This property contains set of all scopes this attribute compound is indexed in.
     *
     * Generated from protobuf field <code>repeated .io.evitadb.externalApi.grpc.generated.GrpcEntityScope indexedInScopes = 7;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getIndexedInScopes()
    {
        return $this->indexedInScopes;
    }

    /**
     * When attribute sortable compound is indexed, it is possible to sort entities by this calculated attribute compound.
     * This property contains set of all scopes this attribute compound is indexed in.
     *
     * Generated from protobuf field <code>repeated .io.evitadb.externalApi.grpc.generated.GrpcEntityScope indexedInScopes = 7;</code>
     * @param array<int>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setIndexedInScopes($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::ENUM, \Wtsvk\EvitaDbClient\Protocol\GrpcEntityScope::class);
        $this->indexedInScopes = $arr;

        return $this;
    }

}

